### ISSUE TITLE
Improve test suite 

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#100]
The test suite of Agents.jl is not on par its base code or documentation. At the moment I think our test suite (located under `tests/`) suffers from the following problems:

1. Some of the _basic_ API is not tested. What is tested is the high level function `step!`. But good tests should be testing each of the individual basic functions that `step!` uses, e.g. if the scheduling works properly, if `move_agent!` does what it should, etc. Same goes for data collection.
2. There are too many model specific tests. It is fine to test one "real" model, but more than that is not necessary. In the end of the day the test suite is supposed to test if Agents.jl works, not if Schelling's model is a good approximation of society. Having too many tests that do the same thing just makes the test suite less clear.
3. There are no real tests about parallelization nor distributed computing.
4. There are no real tests about reproducibility of the end result, starting all the way from a model and going to the data collection, while setting `Random.seed!()` only once.

This issue is great for newcomers!

**Comment by Datseris** [comment]
Notice that we now have coverall as well, to help identify untested parts: https://codecov.io/gh/JuliaDynamics/Agents.jl

**Comment by Libbum** [comment]
Codecov seems to have died three months ago and not come back. I can't see any integration details with it here anymore, but I may not have access to that part of Settings.

**Comment by Datseris** [comment]
do we have tests for parallel / replicates? that's the only thing missing from this list.

**Comment by Libbum** [comment]
Not currently no, I can take a look at that at least.

**Comment by Libbum** [comment]
Closing since #242 covered most of this. Parallel tests are now tracked in #243.
