### ISSUE TITLE
[docs] Missing heading?

### ISSUE THREAD

**Issue by cormullion** [JuliaDynamics/Agents.jl#1012]
Probably missing a `# #` here to make a heading/:

<img width="231" alt="Screenshot 2024-03-16 at 10 57 23" src="https://github.com/JuliaDynamics/Agents.jl/assets/52289/2f2fc356-cf4c-4e92-a154-ee4cdc6819a5">

https://github.com/JuliaDynamics/Agents.jl/blob/3996aff736a39089908d3ebe823931f48c666fd8/examples/event_rock_paper_scissors.jl#L1

This documentation is very good!

**Comment by Tortar** [comment]
thanks, should be fixed in the PR
