### ISSUE TITLE
Stepping until condition is met

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#102]
In #98 @NV2019 requested the following:

> What if I want the step function to run as long as a certain condition is satisfied? Without mentioning the number of steps beforehand?

which I think is a great and non-breaking addition. The way I propose to implement this is to use Multiple Dispatch. If `n` (the number of steps) is integer, nothing changes. If that argument is a function `f` instead then `step!` runs until `f(model)` gives `true`.

**Comment by kavir1698** [comment]
I was thinking along the same lines. I will do it.

**Comment by NV2019** [comment]
Thank you!
