### ISSUE TITLE
Flocking model video doesn't work after update to Makie 0.21

### ISSUE THREAD

**Issue by Tortar** [JuliaDynamics/Agents.jl#1045]
Look at https://juliadynamics.github.io/Agents.jl/dev/examples/flock/

**Comment by Datseris** [comment]
almost certainly it is because now makie checks for keyword arguments and throws errors for invalid kwargs. I've had similar problems in other packages. So we just have to be careful with the kwargs we give to makie.

**Comment by amynang** [comment]
commenting out the agent_marker argument in abmvideo solves the issue (but agents are now plain circles)

> ERROR: Invalid attributes markersize and marker for plot type Poly.

**Comment by Datseris** [comment]
Thanks @amynang , are you interested to create a PR for this? The issue isn't actually in `ambvideo`, but in `meshscatter` (or similar function) used internally deeper in the code.

**Comment by amynang** [comment]
I'm learning Julia as I'm learning how to use Agents.jl so it might be a while before I can be useful...
