### ISSUE TITLE
`@finalise_patterns` not defined impacting @dispatch use in rabbit-fox-hawk example

### ISSUE THREAD

**Issue by CassieSpeakman** [JuliaDynamics/Agents.jl#1052]
ERROR: LoadError: UndefVarError: `@finalize_patterns` not defined in expression starting at C:\Users\User\.julia\packages\DynamicSumTypes\Yw6vy\src\Pattern.jl:65

This is impacting "@dispatch function animal_step!" in[ rabbit-fox-hawk example](https://juliadynamics.github.io/Agents.jl/stable/examples/rabbit_fox_hawk/) code. 

Agents.jl version 6.0

**Comment by Tortar** [comment]
Thanks for the report, I have fixed it in the dependency package, so if you remove Agents and re-add it more or less 30 minutes from now it should be okay
