### ISSUE TITLE
Error in fastest scheduler

### ISSUE THREAD

**Issue by marcelovmaciel** [JuliaDynamics/Agents.jl#106]
In https://github.com/JuliaDynamics/Agents.jl/blob/3fd7e2d04ef884d4cb95c475f0dadf0d4a3575b8/src/core/model.jl#L105 shouldnt it be  `fastest(model) = keys(model.agents)` ??

**Comment by Datseris** [comment]
How can I be so stupid to not test the default scheduler...?

You are correct @marcelovmaciel , I've fixed it in latest commit/version.
