### ISSUE TITLE
minor: typo in tutorial text

### ISSUE THREAD

**Issue by lbs-vadar** [JuliaDynamics/Agents.jl#1060]
**Describe the bug**
Misspelled word in the tutorials page at:

[Additiohally](https://juliadynamics.github.io/Agents.jl/stable/tutorial/#Tutorial:~:text=properties%2C%20and%20more.-,Additiohally,-AgentBasedModel%20defines%20an)

**Minimal Working Example**
Please provide a piece of code that leads to the bug you encounter.

If the code is **runnable**, it will help us identify the problem faster.

**Agents.jl version**

Please provide the version you use (you can do `Pkg.status("Agents")`.

**Comment by Datseris** [comment]
You can click "edit" in the top right of a doc page to make quick changes!

**Comment by lbs-vadar** [comment]
[PR submitted](https://github.com/JuliaDynamics/Agents.jl/pull/1061)
