### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by DanielVandH** [JuliaDynamics/Agents.jl#1079]
At https://juliadynamics.github.io/Agents.jl/stable/tutorial/#Multiple-agent-types-in-Agents.jl, the link in the sentence "However, we strongly recommend you to read through the [comparison of the two approaches](https://juliadynamics.github.io/Agents.jl/stable/tutorial/@ref%20sum_vs_union)." (to https://juliadynamics.github.io/Agents.jl/stable/tutorial/@ref%20sum_vs_union) does not exist.

**Comment by Tortar** [comment]
yes, it should be instead https://juliadynamics.github.io/Agents.jl/stable/performance_tips/#multi_vs_union
