### ISSUE TITLE
 Support for synchronous update rules

### ISSUE THREAD

**Issue by marcelovmaciel** [JuliaDynamics/Agents.jl#109]
Hi everyone. Is there any support for synchronous update rules (as discussed e.g. here : http://jmckalex.org/compass/syn-and-asynch-expl.html ) From what I understood from the documentation there is no scheduler for synchronous updating. Am I correct? In a model I'm implementing using Agents.jl I solved this with a deepcopy (https://github.com/marcelovmaciel/Pudley/blob/fa92f88d7f00fae8b8af3e644b6128b7e79ad160/Pudley/src/01-basefns.jl#L126) is that the best solution ?

**Comment by Datseris** [comment]
@marcelovmaciel would you be so kind to modify the code snippet you pasted so that it includes `using` statements and also the statements you use to run the code? It help us if we have a piece of code that is _runnable_ immediately.

**Comment by marcelovmaciel** [comment]
@Datseris here it is https://github.com/marcelovmaciel/Pudley/blob/master/Pudley/test/we-scheduler.jl

**Comment by Datseris** [comment]
@marcelovmaciel I have thought about this a bit and I don't think deepcopies are the way to go (they are also very inefficient. Here is what I Thought:

1. The agents have four fields: `oold, sold, o, s`.
2. An agent-step function is defined in which each agent updates their `o, s` fields according to the nearby agent's `oold, sold`.
3. A model-step function then sets `old, sold = o, s` for all agents.

Does this do what you want? It should be massively more efficient than your current code, assuming it actually does what you want.

**Comment by marcelovmaciel** [comment]
@Datseris I think it does. I knew you would come up with a solution. Thank you I'm gonna use this implementation strategy whenever I need synchronous updates from now on.

**Comment by Datseris** [comment]
Thanks for the kind words. I have a suggestion for you @marcelovmaciel : since this seems in general a useful concept, and your system seems to be sufficiently known, would you be willing to contribute a Minimal example of this application to our documentation? This would label you as a "contributor" to Agents.jl, and it would also help users with similar problem/question. 

You could write this example identically with the examples of the `examples` folder, with Julia comments interlaced with code, and I'll take it from there.

**Comment by marcelovmaciel** [comment]
@Datseris yes I can try. Since this model I linked here is a work in progress I'm thinking of implementing a synchronous version of any famous Opinion Dynamics model, such as the deffuant model ( equation 3 of http://jasss.soc.surrey.ac.uk/20/4/2.html) . I'm going to follow the `examples `and talk to you when I'm done (probably not today).

**Comment by Datseris** [comment]
Sure, don't worry. I'd suggest to just open a Pull Request once you feel like you have the baseline of material, as this will be easier for me or @kavir1698 to give you comments directly on the code. Don't worry about "how good it is", we'll guide you.

**Comment by Datseris** [comment]
Closed in #120
