### ISSUE TITLE
Precompile of AgentsGraphVisualizations fails

### ISSUE THREAD

**Issue by finmod** [JuliaDynamics/Agents.jl#1098]
| | |_| | | | (_| |  |  Version 1.11.1 (2024-10-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.11) pkg> up
    Updating registry at `C:\Users\Denis\.julia\registries\General.toml`
  No Changes to `C:\Users\Denis\.julia\environments\v1.11\Project.toml`
  No Changes to `C:\Users\Denis\.julia\environments\v1.11\Manifest.toml`
Precompiling project...
  ✗ Agents → AgentsGraphVisualizations
  0 dependencies successfully precompiled in 59 seconds. 678 already precompiled.
  1 dependency errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`

julia> err
PkgPrecompileError: The following 1 direct dependency failed to precompile:

AgentsGraphVisualizations

Failed to precompile AgentsGraphVisualizations [fc457f6c-ecc5-5e53-a4cf-8c57f0a5571f] to "C:\\Users\\Denis\\.julia\\compiled\\v1.11\\AgentsGraphVisualizations\\jl_B1F8.tmp".
ERROR: LoadError: TypeError: in Type{...} expression, expected UnionAll, got a value of type Nothing
Stacktrace:
 [1] top-level scope
   @ C:\Users\Denis\.julia\packages\Agents\dTr7O\ext\AgentsGraphVisualizations\AgentsGraphVisualizations.jl:6
 [2] include
   @ .\Base.jl:557 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base .\loading.jl:2790
 [4] top-level scope
   @ stdin:5
in expression starting at C:\Users\Denis\.julia\packages\Agents\dTr7O\ext\AgentsGraphVisualizations\AgentsGraphVisualizations.jl:2
in expression starting at stdin:

julia>

**Comment by Datseris** [comment]
which version of Julia and Agents.jl?

**Comment by finmod** [comment]
Julia v1.11.1 latest, Agents.jl v6.1.10

**Comment by Tortar** [comment]
We observe the same in our CI: https://github.com/JuliaDynamics/Agents.jl/actions/runs/11394559895/job/31727914202?pr=1091, seems like a Julia bug

**Comment by rmellema** [comment]
I can confirm that it does still precompile just fine on Julia LTS, but it does mean that the package cannot even be installed on the newest version of Julia at the moment. Has anyone brought this to the attention of the Julia developers yet? If it is a bug on their side they should at least know about it.

**Comment by Datseris** [comment]
I haven't found the root of the problem to report it anywhere yet. We Need to know what is failing to know where to report. It is probaby a problem with GraphMakie, not with Base Julia. Or, it could be our own problem. The error message points here: https://github.com/JuliaDynamics/Agents.jl/blob/1028e735080a63547fedf7f1778dba445a45f28d/ext/AgentsGraphVisualizations/AgentsGraphVisualizations.jl#L6 . Which I find weird... I don't see something wrong there.

I am also confused why this fails the whole Agents compilation in the first place. `AgentsGraphVisualizations ` is hidden behind an extension of `GraphMakie` and this isn't used yet. So this should be compiled only when GraphMakie is used...?

**Comment by rmellema** [comment]
You are right about it failing the whole agents compilation. I just created a clean environment, and only installed Agents.jl and that went fine. Once I added GraphMakie the precompilation failed. So that bit is indeed all set up correctly and it only fails if you have both.

**Comment by Tortar** [comment]
I think the general issue is discussed at https://github.com/JuliaLang/julia/issues/56204, julia 1.11.1 introduced a breaking change which should be addressed from our side, I didn't have much time to understand really well how

**Comment by Datseris** [comment]
It seems that it will be fixed in the next Julia patch release for 1.11.

**Comment by Tortar** [comment]
Tested our main with 1.11.2 and it now works fortunately, see https://github.com/JuliaDynamics/Agents.jl/actions/runs/11889177838/job/33814309543
