### ISSUE TITLE
Zombie open street map simulation does not have a video

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#1108]
From here:

https://juliadynamics.github.io/Agents.jl/dev/examples/zombies/

the video does not exist. Same result for latest stable.

_I'm labeling this as high priority as the OSM simulations are a big selling point of Agents.jl, so there should be some sort of video highlighting it._

**Comment by Tortar** [comment]
Fortunately it works on 1.11.2

**Comment by Tortar** [comment]
the dev version uses that now

**Comment by Tortar** [comment]
but we could probably release a new stable version so that it works also there
