### ISSUE TITLE
EventQueueABM example giving incorrect results

### ISSUE THREAD

**Issue by sdwfrost** [JuliaDynamics/Agents.jl#1110]
**Describe the bug**

I'm trying out the continuous time version of a toy model I use for demonstrating simulation/inference capabilities in Julia. Previously, I have coded up a [`StandardABM`](https://github.com/epirecipes/sir-julia/blob/master/markdown/abm/abm.md), which works fine, and gives results comparable to a [hand-coded exanmple](https://github.com/epirecipes/sir-julia/blob/master/markdown/abm_vector/abm_vector.md). However, although my [EventQueueABM](https://github.com/epirecipes/sir-julia/blob/master/markdown/des_agentsjl/des_agentsjl.md) runs without error, it is not giving the correct dynamics. A version of the same model, but using SimJulia, can be found [here](https://github.com/epirecipes/sir-julia/blob/master/markdown/des/des.md). The peak number of infected individuals in my model comes too late - I've checked with different population sizes/multiple runs, and this is a systematic effect, not a stochastic one. I *think* that I'm implementing the model correctly - do you have any suggestions?

**Minimal Working Example**

Julia script: [https://github.com/epirecipes/sir-julia/blob/master/script/des_agentsjl/des_agentsjl.jl](https://github.com/epirecipes/sir-julia/blob/master/script/des_agentsjl/des_agentsjl.jl)
Julia Markdown: [https://github.com/epirecipes/sir-julia/blob/master/tutorials/des_agentsjl/des_agentsjl.jmd](https://github.com/epirecipes/sir-julia/blob/master/tutorials/des_agentsjl/des_agentsjl.jmd)

**Agents.jl version**

v6.1.12

**Comment by Datseris** [comment]
Hi, what is the thing that you believe is behaving "incorrectly"? Is it the event queing, the propensity timing estimation, or something else? The result of the continuous time implementation is:

![image](https://github.com/user-attachments/assets/3ff3a578-3e2f-4281-bd57-3dd54f151fee)

and the result of the discrete time, scaled to the same time units is:

![image](https://github.com/user-attachments/assets/1f5e8b50-f8a2-4488-9c22-d120764d0555)

The blue and green curves to me seem very similar but for the continuous time case they need to be run for longer time, like tf=50. Is this the problem that you are reporting? I haven't read your source code in deep detail yet.

**Comment by slwu89** [comment]
@sdwfrost see https://github.com/epirecipes/sir-julia/issues/153, I found our issue.

**Comment by Datseris** [comment]
thanks @sdwfrost . Yes, the event queue is always a bit tricky to wrap your head around when moving from the discrete time. One needs to take care of when an event should be scheduled and when not, because for the continuous time scheduled event == triggered event.

I assume this is safe to close now.

**Comment by sdwfrost** [comment]
Thanks @slwu89 and @Datseris - it wasn't apparent to me that one needed to explicitly set propensities to zero.

**Comment by Datseris** [comment]
That's why the two graphs look the same but the continuous time is "slower": even though the infect action function does check whether an agent is infected, it was still scheduled and triggered for non infected agents, essentially "wasting" some of the agents' time, if this makes any sense. As an event for an agent is scheduled always after a previous event has happened, this effectively slowed down the simulation.

Does it make sense now?

**Comment by Tortar** [comment]
By the way I'm pleased by the fact that our des works so much faster than the SimJulia one

**Comment by Datseris** [comment]
What's the numbers? I can't seem to find them at the repo now...

**Comment by Tortar** [comment]
I think they are https://github.com/epirecipes/sir-julia/blob/master/markdown/des/des.md#benchmarking and https://github.com/epirecipes/sir-julia/blob/master/markdown/des_agentsjl/des_agentsjl.md#benchmarking (maybe even slightly better by the latest fix)

**Comment by Datseris** [comment]
Oh yeah, that is almost 10x 🔥
