### ISSUE TITLE
Make library of predefined ABMs

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#113]
DynamicalSystems.jl has a [library of predefined systems](https://juliadynamics.github.io/DynamicalSystems.jl/dev/ds/predefined/). Inspired by #112 , which creates a lot of "defining a system" files, maybe it is worth it for us to consider implementing something similar here.

The question is, what's the API going to be like, i.e. what is the "returned" thing that represents the predefined system?

As a first guess: `agentstep, modelstep, abm` (where the function that returns these 3 takes as keywords the arguments that make the `abm`)

**Comment by kavir1698** [comment]
Yeah, this would help development.

**Comment by Datseris** [comment]
We have the example files anyway. We could define a function `loadexample()` that uses the existing example textfiles and brings their definition into scope. Then, in the example files we could add a source specific delmiter like `"stophere" #src` (so that it doesn't go into Literate, and only read the text file until then. Then, we can "evaluate" this file normally.

I am still thinking how to do the #114 , code snippet for website. In fact #113 was opened just for #114 I think.

**Comment by Libbum** [comment]
Closed via #257. Additional work to populate the library with current examples is tracked in #258, and a wishlist in #125.
