### ISSUE TITLE
Code snippet for website

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#114]
website: https://juliadynamics.github.io/JuliaDynamics/

@kavir1698 can we come up with a code snippet that is sufficiently short (up to 20 loc) but still illustrative of the usage of Agents.jl (and thus not the 3-liner CA2D plot) and results in a nice figure or animation we can show in our website? See the "Code Examples" section.

**Comment by kavir1698** [comment]
The current examples do not satisfy the conditions you want. I will to think about a new example.

**Comment by kavir1698** [comment]
A predefined ABM doesn't count?

**Comment by Datseris** [comment]
It does count but we would have to solve #113 first! :)

**Comment by kavir1698** [comment]
> not the 3-liner CA2D plot

It is a predefined ABM, after all. Why not just using that? and the animation can look cool (we should choose a good initialization for interesting things to happen.)

**Comment by Datseris** [comment]
Hm, I just feel that it doesn't highlight using Agents.jl. There should be at least something defined on the code snippet, something that "shows you a typical usage of Agents.jl". There are hundreds of "game of life simulators" out there, but Agents.jl can do much, much more than that. The main thing to highlight for me would be how darn simple the API is or the data collection.

Maybe if we could define a simple step! function at least?

**Comment by Libbum** [comment]
Closed via JuliaDynamics/JuliaDynamics@a22e6852d740
