### ISSUE TITLE
Schelling Model in docs does not run

### ISSUE THREAD

**Issue by itsdfish** [JuliaDynamics/Agents.jl#115]
Hi-

I want to report that the Schelling model in the docs does not work.  It fails at two points:

1.` partial_activation(:group)` where it expects a number:

```
MethodError: no method matching partial_activation(::Symbol)
Closest candidates are:
  partial_activation(!Matched::Real) at /home/dfish/.julia/packages/Agents/65w58/src/core/model.jl:132
in top-level scope at untitled:17
```

2. `step!(model, agent_step!)   ` where there is a method error: 

```

MethodError: no method matching step!(::AgentBasedModel{SchellingAgent,Agents.GridSpace{LightGraphs.SimpleGraphs.SimpleGraph{Int64},2,Int64},typeof(random_activation),Dict{Symbol,Int64}}, ::typeof(agent_step!))
Closest candidates are:
  step!(::AgentBasedModel, ::F, !Matched::G) where {F<:Function, G<:Function} at /home/dfish/.julia/packages/Agents/65w58/src/simulations/step.jl:61
  step!(::AgentBasedModel, ::F, !Matched::G, !Matched::Int64) where {F<:Function, G<:Function} at /home/dfish/.julia/packages/Agents/65w58/src/simulations/step.jl:61
  step!(::AgentBasedModel, ::F, !Matched::G, !Matched::H) where {F<:Function, G<:Function, H<:Function} at /home/dfish/.julia/packages/Agents/65w58/src/simulations/step.jl:71
  ...
in top-level scope at untitled:66
```

Julia 1.3

```
(v1.3) pkg> st Agents
    Status `~/.julia/environments/v1.3/Project.toml`
  [46ada45e] Agents v2.2.2
  [a93c6f00] DataFrames v0.20.0
  [2913bbd2] StatsBase v0.32.0
```

By the way, thanks for putting this package together. I look forward to exploring it!

**Comment by Datseris** [comment]
Hi @itsdfish , thank you for your kind words! I'll fix this soon, its not hard :)

**Comment by itsdfish** [comment]
Thanks for the quick turnaround. I was able to successfully run the model on master. 

By the way, I was hoping to ask a slightly tangential question. Do you have any plans to provide dynamic 2D visualizations, akin to NetLogo or [Mesa
](https://github.com/projectmesa/mesa/blob/master/docs/images/Mesa_Screenshot.png) ?  I ran into some stumbling blocks while trying to implement a simple visualization in Gtk, probably because I am unfamiliar with that package.

**Comment by Datseris** [comment]
> Do you have any plans to provide dynamic 2D visualizations

This would be great to have, and one candidate to do it would be Makie.jl. We certainly want to do this, but at the moment we lack the manpower, having just 2 regular contributors.

**Comment by Datseris** [comment]
see #118
