### ISSUE TITLE
Is the game of life animation correct?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#117]
@kavir1698 , when I look here: https://juliadynamics.github.io/Agents.jl/dev/examples/game_of_life_2D_CA/

you see that in the animation all pixels "fall down", i.e. move downwards. Even a group of 2 pixels side-by-side move downwards, even though this clearly contradicts the game's of life rules.

**Comment by kavir1698** [comment]
It should be a bug in CA2D.jl, not the animation. I will look into it.
