### ISSUE TITLE
Dynamic ABM plotting

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#118]
It would be great if we could support dynamic plotting where one can interactively see how the model evolves. Mesa, the Python ABM framework has some support for that: https://mesa.readthedocs.io/en/master/tutorials/adv_tutorial.html

A good candidate which has a lot of support for interactive visualizations is Makie.jl, because it hooks up very well with Observables.jl . Other alternatives would probably be packages from [JuliaGizmos](https://github.com/JuliaGizmos) for a web-based application.

Any other suggestions/alternatives on how this could be done are welcome.

*(notice that this functionality will reside in AgentsPlots.jl)*

**Comment by itsdfish** [comment]
@Datseris, I have limited experience with package development and visualization, but I will see if I can create a working prototype with Makie until a more permanent solution can be made.  Would you recommend passing an optional `plot_step!` function to `step! `, which would be called after all agents are updated?

**Comment by Datseris** [comment]
Hm, I think the best option would be to create an independent plotting function whose inputs are `abm, agent_step!, model_step!` as well as all other arguments relevant for plotting. `step!` is already quite heavy in functionality and thus I would try to keep plotting separated from `step!`. Thanks for your interest by the way!

**Comment by Libbum** [comment]
Can we consider JuliaDynamics/InteractiveChaos.jl#7 to have championed this issue and close it?
