### ISSUE TITLE
HK example model_step! allocation

### ISSUE THREAD

**Issue by marcelovmaciel** [JuliaDynamics/Agents.jl#123]
I have discovered, using `@btime`, that this line  https://github.com/JuliaDynamics/Agents.jl/blob/df79b0eb63ca42826d0692bb421b8cc7a1f2117b/examples/HK.jl#L70 makes `model_step!` allocate. If we use a function barrier such as 
```
function updateold(a)
    a.old_opinion = a.new_opinion
    return a
end

function model_step!(model)
    for i in keys(model.agents)
        agent = id2agent(i, model)
        updateold(agent)
    end
end
``` 
it stops allocating.

Should I leave it as it is or open a pull request?

**Comment by Datseris** [comment]
I'd say to open a pull request. This doesn't complicate the code much more but leads to performance gain so its a net win!
