### ISSUE TITLE
Node neighbors in a directed graph

### ISSUE THREAD

**Issue by NV2019** [JuliaDynamics/Agents.jl#124]
Is there a way to distinguish between neighbors with incoming and outgoing edges in a directed graph? Currently, I do not see `node_neighbors(node_number::Integer, model::ABM, radius::Integer)` having a provision like `is_directed=true\false`.

**Comment by Datseris** [comment]
what you ask can certainly be done with the API of LightGraphs.jl. Although probably a good suggestion to have here as well? 

@kavir1698 what do you think

**Comment by kavir1698** [comment]
It is a worthwhile addition, especially that it won't complicate the API. It only needs one more method for `node_neighbors` and changing all `::SimpleGraphs` to `::AbstractSimpleGraph`.
