### ISSUE TITLE
Contribution Ideas & Roadmap

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#141]
I'd like to start contributing a few more things to [Agents.jl](https://github.com/JuliaDynamics/Agents.jl), but wasn't too sure if you had a direction you'd like to head in from here, whether you guys are interested in adding certain features or not *etc*.

Do you have specific plans for the project from this point?

How would you like me to go about adding my thoughts/requests? Should I file issues to discuss things first, or WIP PRs for things I'd like to include?

One quick thing I've noticed for example:
```julia
node_neighbors(agent::AbstractAgent, model::ABM)
node_neighbors(node::Int, model::ABM)
```
but only
```julia
node_neighbors(node_number::Integer, model::ABM, radius::Integer)
```
implementing an `agent` radius method would be a trivial extension to make the API balanced.

For me personally though, I'd be interested in the ability to add model properties as an output from a data collector method. Something I'm currently working on is a coupled AB-dynamical systems model, so my `model_step!` changes values in `model.properties`.

Adding something like
```julia
step!(model, agent_step! [, model_step!], n, properties [, model_properties]; kwargs...)
```
to the API and extending the internal methods to not only cover agent properties but also the model is something I think would add value.

A renaming of 'properties' may also be helpful in general, since the properties we save to the `DataFrame` from the `step!` methods and the properties we give to `AgentBasedModel` are separate entities (this wasn't clear to me when reading the documentation initially). In the test cases you already use the variable name `agent_properties` a lot, perhaps making this more verbose throughout the code and documentation could be a solution?

I've also been working on a Luxor based plotting system for my project, it looks quite nice but would take work to generalise for inclusion to [AgentsPlots](https://github.com/JuliaDynamics/AgentsPlots.jl). Something akin to NetLogo's output, but a little less 1995:
![image](https://user-images.githubusercontent.com/3059508/76955705-f345ff00-6912-11ea-8047-e8b536a8779c.png)

Let me know your thoughts!

**Comment by Datseris** [comment]
Awesome!

For `node_neighbors`: first, it should be renamed to `space_neighbors`: it also works (or it will) for continuous space as well, and the name `space_neighbors` always tells you that you get some neighbors in your spatial strucutre.

THere should be a method `space_neighbors(agent, model, radius) = `space_neighbors(agent.pos, model, radius)` and then all further methods are taken care of and work for both agent as well as position.

**Comment by kavir1698** [comment]
For me, any feature addition can be welcome and discussed. So I suggest filing and issue before creating a PR to prevent redoing things.

> Adding something like
> 
> `step!(model, agent_step! [, model_step!], n, properties [, model_properties]; kwargs...)`
> 
> to the API and extending the internal methods to not only cover agent properties but also the model is something I think would add value.

You can already change model properties. The dictionary key of `properties` should be `:model` and the values are functions that retrieve data from the model.

> I've also been working on a Luxor based plotting system for my project, it looks quite nice but would take work to generalise for inclusion to AgentsPlots.

This would be great. Fast plotting, IMO, is the biggest shortcoming of Agents.jl at this point.

**Comment by Libbum** [comment]
Great! Thanks guys. 

- I'll read up on your continuous space discussions and perhaps look at the `space_neighbours` function after that settles (if it's still listed as a TODO at that point).
- Model properties: yep, aware that I could do that, perhaps I'll write up an issue and workflow that I'm having problems resolving with the current implementation, and we'll see if we can identify a better method.
- Will have a think about how I could make my specific case become a general library & continue the discussion over in AgentsPlots.

**Comment by Datseris** [comment]
@Libbum in your Luxor plot the agents are in `GridSpace`?

**Comment by Libbum** [comment]
Yep, I'm just taking the agent positions essentially and scaling them to the size of the Luxor tile I'm working with. 

With continuous space we should be fine with bounding that on the convex hull of all velocity vectors or something to that effect. It would be 1 and 2D only with Luxor, but I'd be interested in setting up something with [Makie](https://github.com/JuliaPlots/Makie.jl) in the future for 3D.

**Comment by Datseris** [comment]
To make this generic we could have a function `location(agent, model)` that will return you the position of the agent. For continuous space this is always `agent.pos` but for GridSpace there might be need to take the `grid.dims` into consideration (I actually don't remember what `agent.pos` is for grid spaces tuple of integers or tuple of reals...).... :D

**Comment by kavir1698** [comment]
> I actually don't remember what agent.pos is for grid spaces tuple of integers or tuple of reals

Integers

**Comment by Libbum** [comment]
Ints for me at least.
```julia
space = Space((25,25), moore = true)
```
with 100 agents yields something like this:
![image](https://user-images.githubusercontent.com/3059508/76976604-77f54500-6934-11ea-91ee-7f340130859b.png)

`location` would be helpful I think, would be good to have this value consistent against all grid types.

**Comment by Datseris** [comment]
yeah actually `location` can just give `agent.pos` for ContinuousSPace and `vertex2coord(agent.pos)` for anything else. THe latter case covers the situation where the user uses `GridSpace` but keeps (for whatever reason) the agent position as `Int`.

**Comment by Datseris** [comment]
@Libbum , I've just opened #148 , which attempts to simplify code. In addition with the todo:
```
# TODO: `Space` became overly complicated and there is no reason to use the same
# name for all spaces anymore. Instead, we should properly use `GraphSpace`,
# `GridSpace`, `ContinuousSpace`. A depwarning should be added to `Space`.
```
which is above `ContinuousSpace`, these two small projects are excellent so that you get more familiar with the space types. Both `ContinuousSpace` and `GridSpace` could be used intercha-engebly in your plotting framework. 

If you could/would like to hack these two things, it would be a great help plus a good exercise for you as well.

**Comment by Libbum** [comment]
All this is essentially done now, other than some aspects of the plotting.
