### ISSUE TITLE
Tests for continuous space

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#146]
We really need tests for continuous space before continuing to work on it!

The `examples/continuous_space.jl` should be turned into a test file ASAP.

Here is what should be tested:

- [x] Basic model initialization
- [x] `move_agent!` without provided function
- [ ] `move_agent!` with provided `update_vel!` function 
- [x] `add_agent!` with an existing agent
- [x] `add_agent!` with no existing agent (the agent is created)
- [x] internal database is updated correctly at every step after an agent is added or is moved or is removed
- [ ] periodic boundary conditions are enforced
- [x] agents within some range are found correctly
- [ ] `space_neighbors` (once this is implemented)

**Comment by Datseris** [comment]
@kavir1698 you checked that agents within range are found correctly, but how is this "tested" since we don't even have `space_neighbors` yet...? :D

**Comment by kavir1698** [comment]
I have used the database function to find agents in an arbitrary range.
