### ISSUE TITLE
Rethink gridspace: don't expose network to user

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#148]
I think that we unecessarily complicate things by exponsing the underlying network structure of `GridSpace` to user, and exporting functions such as `vertex2coord` and `coord2vertex` or allowing the position to be specified either as a node or a tuple.

Instead, we should simply ensure / assert that for grid spaces the "position" is always of type `NTuple{Int}` and this is the only type used. 

it will also simplify the source code and simplify the entire discussion.

---

while technically a breaking change, it is an extremely mild one, basically removing obsolete functions from the API.

**Comment by Libbum** [comment]
Sure, I can take this on!
