### ISSUE TITLE
Would you like to join JuliaDynamics?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#15]
Hey there,

let me start with an important declaration: **The discussion here will in no way affect my review at [JOSS](https://github.com/openjournals/joss-reviews/issues/1527).**

Agents.jl is a Julia package that revolves around agent-based-modeling and cellular automata. I unfortunately was not aware about this until I was given the opportunity to review it... JuliaDynamics is a GitHub organization about dynamical systems and nonlinear dynamics (and also recently for assisting scientific projects). It contains several packages already, one being the award-winning **DynamicalSystems.jl**. What is notably missing from JuliaDynamics are systems with discrete space and time (i.e. cellular automata).

https://juliadynamics.github.io/JuliaDynamics/

Agents.jl seems to fit in JuliaDynamics from a scientific perspective. In addition, its documentation clearly matches the standards of JuliaDynamics, providing examples, tutorials and scientific motivation on the use of ABM. At JuliaDynamics we try to be a coherent unit ("organization") that can spread word and interest for dynamical systems. It is also very good for users to have packages of similar scientific orientation to organizations. It makes them easier to find and more trustworthy

I would like to invite you to join us at JuliaDynamics. What we will gain is that your excellent work will be part of our collective effort for creating high quality libraries for dynamical systems. What you'll gain by joining:

* A logo for Agents.jl
* Help in maintaining the repo
* Pull Requests review
* Documentation improvements (if necessary)
* Be part of an already recognized (and highly active) GitHub org.
* More exposure: easier to find it if part of JuliaDynamics, and also showcased in our website. I think you could benefit from this.

Let me know what you think! In a similar way that I approached you, I also approached [RecurrenceAnalysis.jl](https://github.com/JuliaDynamics/RecurrenceAnalysis.jl/issues/8).

*please notice that for conflict-of-interest purposes, this can only progress from my side after the review of JOSS is over*

**Comment by Datseris** [comment]
(I forgot to mention the obvious technicality: should you chose to join, the moment you do you will become part of a team that has owner-level access to this repo)

**Comment by kavir1698** [comment]
Hi,
Thank you for the invitation. I am happy to join the JuliaDynamics organization, as it will help introduce, maintain, and develop Agents.jl.

**Comment by def-mycroft** [comment]
I've recently started investing some time into making contributions to Agents.jl. I'm very interested in using ABM techniques in economics research (I'm working on a graduate program in applied math right now in the US and plan to continue studies in economics). The Agents project provides such a useful framework for ABM work. 

I definitely hope to continue making contributions to the project in the future. 

The JuliaDynamics org and Agents.jl looks like a great fit!

**Comment by Datseris** [comment]
Now that the JOSS paper is published, I think we can progress here! Let me summarize how I think a good plan moving forward is:

1. @kavir1698 moves the repo to JuliaDynamics, and I make a team that gives him owner level access.
2. I start working on #20 
3. [Optional] @kavir1698 can attempt to tackle #24 
4. Me and a friend of mine work on a logo for Agents.jl
5. I make an announcement at discourse about the Agents.jl 

What do you think?

**Comment by kavir1698** [comment]
Pretty good. Let's move forward.
