### ISSUE TITLE
minor error in the code for sir.jl

### ISSUE THREAD

**Issue by DOSull** [JuliaDynamics/Agents.jl#157]
Getting this set up in Juno, I copied and pasted code from the sir.jl example, and found that I need to change line 68
    `space = GraphSpace(complete_digraph(C))`
to
    `space = Space(complete_digraph(C))`
to get it to work. I'm still figuring out Julia and Agents so I am no expert, but I guess that's a typo/bug. The code on the documentation page at https://juliadynamics.github.io/Agents.jl/stable/examples/sir/ is correct

**Comment by Datseris** [comment]
Hi, yes you are correct. Thanks for pointing this out. It is an unfortunate consequence of being in the time between going to version 3.0 (where we have support for continuous agents in space).

This is fixed on master (where `Space` is not used anymore and you would indeed use `GraphSpace`), but unfortunately I now can't go back to fix the "stable" version...

**Comment by Datseris** [comment]
Ps.: Be sure that if you copy paste code from the master branch, you also have the master branch installed. this is done by 
```
]add Agents#master
```

**Comment by Datseris** [comment]
Otherwise, you can use the `examples` folder from the stable installation of Agents in your Julia packges folder.
