### ISSUE TITLE
New logo for version 3.0

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#160]
I must admit that for months now I was displeased with the agents logo we came up, because it paid too much attention to cellular automata... which does injustice to Agents.

Now, with the new continuous space, we have an opportunity that I want to take.

@kavir1698 if you can get the social distancing model up to speed with the current state of the repo even without #155 I can take it from here.

The continuous space has stabilized a bit, besides #155 , and we can have this example in the docs already.

**Comment by kavir1698** [comment]
I will create a PR soon. Interactions between agents do not happen as desired, though.

**Comment by Datseris** [comment]
I've replied to some open issues regarding interaction. It is a good time for you to take administrative actions here: Since you are an expert in ABMs and I am not, please feel free to enrich the open Project https://github.com/JuliaDynamics/Agents.jl/projects/2  with things to-do or to-discuss. You are more qualified to guide the project than me!
