### ISSUE TITLE
Incorrect step number after using n::Function in data collection

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#165]
If I use the functionality of specifying `n::Function` for data collection, the resulting data are b roken:
```
julia> data
10×3 DataFrames.DataFrame
│ Row │ id    │ new_opinion │ step  │
│     │ Int64 │ Float64     │ Int64 │
├─────┼───────┼─────────────┼───────┤
│ 1   │ 1     │ 0.18514     │ 0     │
│ 2   │ 2     │ 0.73779     │ 0     │
│ 3   │ 3     │ 0.172216    │ 0     │
│ 4   │ 4     │ 0.506883    │ 0     │
│ 5   │ 5     │ 0.755257    │ 0     │
│ 6   │ 6     │ 0.963889    │ 0     │
│ 7   │ 7     │ 0.315111    │ 0     │
│ 8   │ 8     │ 0.873518    │ 0     │
│ 9   │ 9     │ 0.58046     │ 0     │
│ 10  │ 10    │ 0.646094    │ 0     │
```

they have only 0 as step.

**Comment by Datseris** [comment]
@kavir1698 I don't know where this happens. Can you point it in the source code and I'll fix it? I am updating the HK model to use this functionality, I can do it immediatelly if I found out where this happens.

**Comment by Datseris** [comment]
Or even better, I am sure it will be much simpler for you to fix this. Can you please push the fix to the branch `terminate` ? The HK.jl model is a test of whether this works.

**Comment by kavir1698** [comment]
This is not a bug. You are collecting all agents' opinions. So you have agent ids (first columns) at each time step.

**Comment by kavir1698** [comment]
If you wanted one line per time step, you should have used an aggregate function in `properties`.

**Comment by Datseris** [comment]
wait, let me check again.

**Comment by Datseris** [comment]
Sorrryyyyyyyyyy
