### ISSUE TITLE
Iterator over agent pairs

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#170]
See https://github.com/JuliaDynamics/Agents.jl/pull/169 for motivation.

Often wants to iterate of pair of nearest neighbors of agents, and do some kind of interaction. Almost always, this interaction happens once between `agent1, agent2` and need not be repeated for `agent2, agent1`. I.e. almost all interactions are **commutative**.

We should create a function / iterator that iterates over pairs of nearest neighbors agents (i.e. the iterator returns two agents). This function can be then used in a `model_step!` to make everything massively more performant.

@kavir1698 with the database approach, is there an easy way to find nearest neighbors?

**Comment by kavir1698** [comment]
It would involve calculating the distance of the agent to all other agents and choosing the smallest one.

**Comment by Datseris** [comment]
This is the most inefficient way to do it though.

**Comment by kavir1698** [comment]
But do we really need to find the closest agents globally? The current implementation in #169 is enough, I think.

**Comment by kavir1698** [comment]
If there is no other agent within `r`, we don't want any interaction.

**Comment by Datseris** [comment]
Yes using the `nearest_neighbor` of #169 is a goo start I guess. Definitely not the most efficient one but what can you do...
