### ISSUE TITLE
Manifest & gitignore

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#180]
bc7ae9f2893 dropped `Manifest.toml` from `.gitignore`, but has also put the current master (bc2d8baae19) in the odd state of tracking the `/docs/Manifest.toml` but not the `/Manifest.toml`. It's not pertinent to have the base manifest in the repo, so no qualms there. If it's necessary to now track the docs manifest, it's probably better we alter `.gitignore` to be explicit about the difference.

**Comment by Datseris** [comment]
Don't care about the manifests until 3.0 is released, let me track them. I've spent four hours yesterday (I am not exaggerating), setting the docs to build properly.

If any of your PRs change the Manifests, you can safely add them back to `gitignore` and I'll do anything else necessary.

**Comment by Libbum** [comment]
No worries. Yeah, I had a nightmare of a time with them myself but didn't manage to crack it&mdash;good to see them functioning.
