### ISSUE TITLE
Handling agents killed by other agents

### ISSUE THREAD

**Issue by itsdfish** [JuliaDynamics/Agents.jl#193]
If agent 1 is processed first and kills agent 2,  an error will occur when the step! loop advances to agent 2.  

There are a variety of solutions. One possibility is to use  Base.Iterators.Filter which allows you to iterate over a dynamic set. Another solution is to include a Boolean field (e.g. alive) and to ignore alive=false and to purge those agents in the model_step!. This solution has the downside of increasing bookkeeping on the user end. You guys might have a better solution, or perhaps you already have one and it was broken in some changes. 

Here is a MWE:

```julia
using Agents 

mutable struct Agent <: AbstractAgent
    id::Int
    pos::Tuple{Int,Int}
end

function initialize_model(;n_agents=100, dims=(20,20))
    space = GridSpace(dims)
    model = ABM(Agent, space, scheduler=random_activation)
    for _ in 1:n_agents
        add_agent!(model)
    end
    return model
end

function agent_step!(agent, model)
    dead_agent = model.agents[2]
    kill_agent!(dead_agent, model)
end

model = initialize_model()
step!(model, agent_step!)
```

**Comment by itsdfish** [comment]
I'm not sure if this is relevant for the situation at hand, but it appears that Julia does handle dynamic removal of iterator elements. This was not true in the past and it was necessary to use Base.iterators.Filter. 

However, it does not seem to work in the case of dynamically added elements. I'm not sure how that is typically handled in ABM? If a new agent is added on step i, is it processed on step i or is it processed first on step i + 1?

```
function test1()
    x = Dict(i=>rand() for i in 1:5)
    flag = true
    for (k,v) in x
        println(k)
        if flag
            delete!(x, 2)
            x[20] = 2.
            flag = false
        end
    end
    return x
end
# removes key 2 but does not process key 20
test1()
```

**Comment by kavir1698** [comment]
> Another solution is to include a Boolean field (e.g. alive) and to ignore alive=false and to purge those agents in the model_step!.

This is what I would do in such a situation.

> If a new agent is added on step i, is it processed on step i or is it processed first on step i + 1?

At the start of each step, a list of agent ids is produced from the `scheduler`. Then `agent_step!` is applied to each of them. That is you see this error. The removed agent is not removed from the iterator.

**Comment by Datseris** [comment]
This is trivially fixed by changing this code of `step!`:
```julia
for index in activation_order
      agent_step!(model.agents[index], model)
    end
```
to this:
```julia
for index in activation_order
    haskey(index, model) || continue
      agent_step!(model.agents[index], model)
    end
```
i.e. skips the agent step if the key no longer exists.

**Comment by Datseris** [comment]
>  >    Another solution is to include a Boolean field (e.g. alive) and to ignore alive=false and to purge those agents in the model_step!.

> This is what I would do in such a situation.

!!! what??? no! @kavir1698 how come you didn't think of the code of `step!`?

**Comment by kavir1698** [comment]
> !!! what??? no! @kavir1698 how come you didn't think of the code of step!?

I mentioned the quickest fix, without waiting for the code to change!!

**Comment by Datseris** [comment]
no no no :P We should do the things the "correct" way, not the quick way!!!

**Comment by kavir1698** [comment]
There are two points here. Helping the halted simulation of the OP to move forward for now, and preventing such issues happening in the future.

**Comment by Datseris** [comment]
Or, you could just add a single line of code to the source, fix the issue, and not recommend the user to change their entire data structure, agent step function and model step function.

**Comment by kavir1698** [comment]
Only if the user wants to be on master. Anyway, whenever you notice a mistake or an improvement, you can just mention that. This tone is not useful.

**Comment by itsdfish** [comment]
Thank you guys for your help. I've been working on master in anticipation of changes for v3.0.

Just for my edification, are newly created agents processed on the current step iteration or the subsequent one? I'm guessing it is the later, but I just want to be sure.

**Comment by Datseris** [comment]
> Only if the user wants to be on master. Anyway, whenever you notice a mistake or an improvement, you can just mention that. This tone is not useful.

Yes you are right, I apologize.

Similarly, whenever such an issue opens, please take 10 seconds to think about it. I am sure you can find these trivial solutions just as fast. Regardless if a user wants to be on master or not, they should make this choice _after_ they know the true solution to this puzzle. Presenting an alternative that requires changing quite literally every part of the user code without presenting the actual solution leads to bad decisions and sloppy code. That's why we take steps back when developing this library, so that we can make better decisions. We've seen this a lot in the 3.0 process.

p.s.: The user that reported this is already on master, as is evident by the use of `GridSpace`.

**Comment by Datseris** [comment]
> Just for my edification, are newly created agents processed on the current step iteration or the subsequent one? I'm guessing it is the later, but I just want to be sure.

the later.
