### ISSUE TITLE
Support unions for heterogeneous agents

### ISSUE THREAD

**Issue by itsdfish** [JuliaDynamics/Agents.jl#194]
Currently, Agents.jl does not support Unions of different agents. @Datseris  tried a quick fix on master but that did not work. I think the solution will involve `typeof(A) == Union`. However, the code crashes as a subsequent point with that check. Here is a MWE:

```
using  Agents
mutable struct Sheep <: AbstractAgent
    id::Int
    pos::Tuple{Int,Int}
    energy::Float64
    max_energy::Int
    reproduction_prob::Float64
    Δenergy::Float64
end
mutable struct Wolf <: AbstractAgent
    id::Int
    pos::Tuple{Int,Int}
    energy::Float64
    max_energy::Int
    reproduction_prob::Float64
    Δenergy::Float64
end
mutable struct Grass <: AbstractAgent
    id::Int
    pos::Tuple{Int,Int}
    fully_grown::Bool
    regrowth_time::Int
    countdown::Int
end
space = GridSpace((20,20))
model = ABM(Union{Sheep,Wolf,Grass}, space, scheduler=random_activation)
```

**Comment by Datseris** [comment]
I had to use `isconcretetype` instead of Union. Thankfully it was an easy fix :) Please reopen this issue if somewhere along you found a bug on this again.
