### ISSUE TITLE
Problems with the `sample!` function 

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#196]
The sample function does not do what it claims.

1. `sample!` with `replace` is not tested.
2. `sample!` with `replace` does not work because:
```julia
    for (index, id) in enumerate(newids) # add new agents while adjusting id
        model.agents[index] = deepcopy(model[id])
        model.agents[index].id = index
    end
```
thus an agent that has been selected twice is only added once in the model.

3. The design of the `sample!` function has bad performance. It removes and re-adds everything from scratch, but I don't understand why. Why not just kill the agents that were not selected, and add any additional extra ones (e.g. add the extra duplicates if `resample` , or just add the extra created agents if `n > nagents(model)` ?

**Comment by kavir1698** [comment]
> thus an agent that has been selected twice is only added once in the model.

Reading the code you pasted, I don't see why you say it is added only once. If an id appears twice in `newids`, then two identical agents with different ids are added to the model.

**Comment by kavir1698** [comment]
I'll test the function further for bugs.

> The design of the sample! function has bad performance. It removes and re-adds everything from scratch, but I don't understand why. Why not just kill the agents that were not selected, and add any additional extra ones (e.g. add the extra duplicates if resample , or just add the extra created agents if n > nagents(model) ?

With the current code, if an agent should be added multiple times, the first time it's added is redundant. The following can be a fix: an if statement that checks whether a `newid` is being added for the first time, and if so, doesn't do the deepcopy, and only updates the original id to the `newid`.

**Comment by Datseris** [comment]
> and only updates the original id to the `newid`.

I still don't understand this statement, or maybe I don't understand `StatsBase.sample`. This function will give you a vector of IDs, randomly sampled. All of these IDs **already exist in the model**, because this is where you sample from:
```julia
julia> sample(1:100, 10)
10-element Array{Int64,1}:
 66
 82
 17
 44
 61
 54
 82
 21
 84
 18
```
thus, the output of this function can only give you IDs that already exist in the model. Our `sample!` only has to do two things:

1. Kill agents whose ID is NOT in this sampled list
2. For all duplicate IDs in the sampled list, add new agents for them.

**Comment by Datseris** [comment]
Just saw the first message.  @kavir1698 you are right, I swapped the `index` and `id` around in my brain. While the first case is indeed not "incorrect" in the sense, the second case will probably still be much more performant.
