### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by IgorDouven** [JuliaDynamics/Agents.jl#203]
I'm impressed by this package&mdash;even more so after the recent extensions. Thanks for the hard work!

Maybe the following is a feature request, but maybe it's already possible and I just fail to see how to do it. In that case, it might be good to add something about it to the documentation.

What I'm trying to do concerns a later version of the HK model than the one you use in your example. In that later version, agents update their opinions both on the basis of the opinions of agents within their bounded confidence interval (the ones filtered by what you call `boundfilter`) and on the basis of evidence they directly get about the 'truth' (some value &tau;). Their updates are a mixture of these two, which is regulated by a parameter &alpha;.

In some of their later publications, Rainer Hegselmann and Ulrich Krause consider models in which each agent has its own &epsilon; and &alpha;. I'm running simulations in which I'm trying to determine the impact agents' &epsilon; and &alpha; values have on the their accuracy (the sum of squared errors).

Your package makes it very easy to run these simulations, and I have had no difficulty defining my own data gathering loop, which I can run in parallel, so it's all really fast. But just out of curiosity, I wanted to see whether I could the same without writing a loop and instead using your `replicates` and `parallel` functionality. The problem is that in each simulation, &tau; should be chosen randomly anew. Unfortunately, when I use `replicates`, then even if I put `tau = rand()` in the model definition, all the replications use the same value of &tau;. Is it possible to somehow let `replicate` initialize the model anew for each replication?

Minor additional question: I think I saw in the discussion on github in the past two weeks or so that there was an idea to specify something like `nmax` for the `terminate` function (so, run till convergence, but with a maximum number of iterations specified). That would be very useful, but I can't find anything about it in the documentation. Am I overlooking something?

**Comment by Datseris** [comment]
Quick answer on last part:

> Minor additional question: I think I saw in the discussion on github in the past two weeks or so that there was an idea to specify something like nmax for the terminate function (so, run till convergence, but with a maximum number of iterations specified). That would be very useful, but I can't find anything about it in the documentation. Am I overlooking something?

That is no longer necessary because the current step is given as an argument to the "terminating function". So you can implement an arbitrary `Nmax` in your terminating function like  `s > Nmax && return true`.

**Comment by IgorDouven** [comment]
Thanks, that's great!

One additional remark on the main issue: I saw that the replications also all use the same &epsilon; and &alpha; values. I'd also like them to be chosen anew for each replication. (As said, this can easily be done via a loop&mdash;it would just be really nice if this could be done even more easily via `replicates`.)

**Comment by kavir1698** [comment]
You can explore parameter value combinations using [the `paramscan` function](https://juliadynamics.github.io/Agents.jl/stable/api/#Agents.paramscan). [Here](https://juliadynamics.github.io/Agents.jl/stable/examples/schelling/#Scanning-parameter-ranges-1) is an example of this function in use.

**Comment by IgorDouven** [comment]
Thanks, I had seen that function. It's not clear to me how I could use it
for my purposes. I have two agent properties (values for alpha and epsilon)
that I want to be chosen randomly for each agent at the beginning of each
replication, and I have a model property (value for tau) that I also want
to be chosen randomly at the beginning of each replication. I suppose I
could first generate vectors of random numbers and then feed them into the
`paramscan` function, but then I think I prefer my current approach. (As I
said, I was just curious whether this could be done more easily via
`replicates`.)

Op do 9 apr. 2020 om 12:54 schreef Ali R. Vahdati <notifications@github.com

**Comment by Datseris** [comment]
I think a solution would be allowing when `replicates > 0 ` to provide an `initialize` function, so that instead of us doing `deepcopy(model)` for each replicate, we do an initialize. In fact, it is probably possible to make the `model` argument (the first argument) to be a function, and via multiple dispatch do:

1. `allmodels = [deepcopy(model) for i in 1:replicates]` for input ABM
2. `allmodels = [model(i) for i in 1:replicates]` for input function. So each function gets the replicate number and initializes a model.

What do you think?

**Comment by kavir1698** [comment]
>  I suppose I could first generate vectors of random numbers and then feed them into the
`paramscan` function

Yes, that is what I was thinking.

> I think a solution would be allowing when replicates > 0 to provide an initialize function, so that instead of us doing deepcopy(model) for each replicate, we do an initialize.

I am not sure if that is necessary. Specifically, I don't see why using `paramscan` is not good enough.

**Comment by Datseris** [comment]
> I am not sure if that is necessary. Specifically, I don't see why using `paramscan` is not good enough.

So, how would you do it with `paramscan`?
