### ISSUE TITLE
Type instability in space_neighbors

### ISSUE THREAD

**Issue by itsdfish** [JuliaDynamics/Agents.jl#208]
space_neighbors returns a `Vector{Union{Missing, Int}}` instead of `Vector{Int}`. Here is a MWE

```
using Agents, Random

mutable struct Agent <: AbstractAgent
    id::Int
    pos::NTuple{2,Float64}
end

function initialize_model(;n_agents=100)
    space2d = ContinuousSpace(2; periodic=true, extend=(1, 1))
    model = ABM(Agent, space2d, scheduler=random_activation)
    for _ in 1:n_agents
        add_agent!(model)
    end
    index!(model)
    return model
end

Random.seed!(0358)

model = initialize_model()

agent = random_agent(model)

ids = space_neighbors(agent, model, .1)
```

On a somewhat related note, I was wondering whether it would be useful to return agents instead of agent ids with `space_neighbors`? I find that I usually iterate over agents rather than their ids.

**Comment by Libbum** [comment]
Confirmed here, albeit only for `ContinuousSpace`, I'll fix that now.

As for returning agents vs ids, we'll open that for discussion. If this was implemented, we should do the same with `node_neighbors` to keep things consistent.

**Comment by Datseris** [comment]
The reason to return IDs is simple: it allocates less. Making a vector of integers is much less costly than making a vector of complicated structs.
