### ISSUE TITLE
GridSpace not defined on Schelling model

### ISSUE THREAD

**Issue by sbacelar** [JuliaDynamics/Agents.jl#215]
On Schelling model (but not on documentation):
```
space = GridSpace((10, 10), moore = true)
```
gives the error `UndefVarError: GridSpace not defined`.
Should it be `Space` instead of `GridSpace`?

**Comment by Libbum** [comment]
If you're looking at the master branch you should also be looking at the [development documentation](https://juliadynamics.github.io/Agents.jl/dev/examples/schelling/).
