### ISSUE TITLE
terminate and when

### ISSUE THREAD

**Issue by IgorDouven** [JuliaDynamics/Agents.jl#217]
Suppose I run a model until convergence -- using the new `terminate` function -- and suppose I only need to collect the results from the last step. How would I do that? Something like `when = end` would make sense. Maybe there is something about this in the documentation, but I can't find it.

**Comment by Datseris** [comment]
I am not sure what the difficulty is here: from the documentation of `step!` and `run!` I can see that both can be functions that take as an input `(model, s)`. So, just make both of them have the same condition?

**Comment by Datseris** [comment]
Please let us know whether this works (or why it doesn't work).

**Comment by IgorDouven** [comment]
Sorry, but I can't get this to work. I now collect data with `data, _ =
run!(model, agent_step!, model_step!, terminate, agent_properties)`. Given
that I don't know in advance how many steps it will take till convergence,
the only thing I can think of is adding something like `when = terminate`
to `run!(...)` -- but that gives an empty data frame.

Op ma 13 apr. 2020 om 01:29 schreef George Datseris <
notifications@github.com>:

**Comment by Datseris** [comment]
`when = terminate` that is incorrect. You need to modify `when` to be the same function as `terminate` but counting one step previously. Since data collection is done at the end of the stepping process, while `terminate` is checked at the start of the process, you need to do the modification I said.

**Comment by IgorDouven** [comment]
Thanks, yes, I thought about that. But I'm using the `terminate` function you sent me to run updating in the HK model till convergence. This is the function:
```{julia}
function terminate(model, s)
    if any(!isapprox(a.previous_opinion, a.new_opinion; atol=1e-5) for a in allagents(model))
        return false
    else
        return true
    end
end
```
The problem is that, in the HK model, it is not obvious which step is the one just before the agents' opinions converge.

**Comment by Datseris** [comment]
I understand your question and problem.

This is the data collection loop:
```julia
df_agent = init_agent_dataframe(model, adata)
df_model = init_model_dataframe(model, mdata)

s = 0
while until(s, n, model)
  if should_we_collect(s, model, when)
      collect_agent_data!(df_agent, model, adata, s)
  end
  if should_we_collect(s, model, when_model)
      collect_model_data!(df_model, model, mdata, s)
  end
  step!(model, agent_step!, model_step!, 1)
  s += 1
end
return df_agent, df_model
```

I think we (the developers) made a mistake here. There is no data collection done one the final step even if the user wants to. We should modify the above loop to call `collect_data!` once after the `while` loop is done. Maybe you can open a PR?

**Comment by Libbum** [comment]
This has come about with the removal of `step0` effectively. We can certainly change the order of operations here.

**Comment by Datseris** [comment]
Yeah, that's the reason. we must add one copy of 
```
  if should_we_collect(s, model, when)
      collect_agent_data!(df_agent, model, adata, s)
  end
  if should_we_collect(s, model, when_model)
      collect_model_data!(df_model, model, mdata, s)
  end
```
after the while loop. (or re-introduce the `step0`, but I like the solution withl les keywords better)

**Comment by IgorDouven** [comment]
Thanks for all your help. This is a bit beyond me, but wouldn't it suffice
to have `while until(s, n + 1, model)` instead of `while until(s, n,
model)` (perhaps the same then in the `step!` function)?

Op ma 13 apr. 2020 om 12:17 schreef George Datseris <
notifications@github.com>:

**Comment by Datseris** [comment]
This won't work in your scenario where `when` doesn't care about the step size `n`. The fix is very easy and I've posted it in my above comment.

**Comment by IgorDouven** [comment]
Great, thanks, I'll wait for the change then.

Op ma 13 apr. 2020 om 13:02 schreef George Datseris <
notifications@github.com>:

**Comment by Datseris** [comment]
On current master I've even updated the HK model to do exactly what discussed here: pass `terminate` to `when`, and it works just fine.

**Comment by IgorDouven** [comment]
I just saw it, updated the package, and tried it: works great indeed! Many
thanks!

Op ma 13 apr. 2020 om 20:51 schreef George Datseris <
notifications@github.com>:
