### ISSUE TITLE
different types of agents

### ISSUE THREAD

**Issue by IgorDouven** [JuliaDynamics/Agents.jl#218]
I'd like to populate a model with different types of agents. I found that this can done using `Union`. Is there a way in which I can store the type information about the agents when I collect data. So, e.g., could one have a column in the `DataFrame` with agent data indicating the type of the agent whose data are stored in the given row?

**Comment by Datseris** [comment]
Many possibilities:

* `typeof`
* `Symbol(typeof)`
* `string(typeof)`
* `nameof`

Just make the data collection entry to be one of these functions.
