### ISSUE TITLE
Reducing over an empty collection is not allowed

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#221]
We've got a problem in the data collector when we try to save data from a set of 0 agents.

Suppose we have

```julia
julia> model.agents
Dict{Int64,Agent} with 5 entries
...
```
and `run!` with an agent aggregation function, say `(:weight, sum)`.

If `agent_step!` ends up using `kill_agent!()` or `genocide!()` such that
```julia
julia> model.agents
Dict{Int64,Agent} with 0 entries
```
at some point, we'll hit the `[1] _empty_reduce_error() at ./reduce.jl:295`.

**Comment by Datseris** [comment]
But is this really a bug...? How do you make sense of "aggregating" when there are no agents? 

We could add the value `missing` if `length(model.agents) == 0`.

**Comment by Libbum** [comment]
True. The error is *by design* in Julia core. It puts the burden on the user to check this, so perhaps at least some documentation around the issue.

From Daisyworld where I hit this:
```julia
black(agent) = agent.breed == :black
```
to
```julia
black(agent) = isnothing(agent) ? false : agent.breed == :black
```
works just fine.

**Comment by Datseris** [comment]
Default value seems very sensible to me, and also the way to go! We could default to `missing`, if possible given our setup.

**Comment by Libbum** [comment]
Exactly. I don't think we want to add `missings` if we can help it.

Solution in the Daisyworld case is:

```julia
total(v) = length(v) == 0 ? 0 : sum(v)
```

I'll add an extra discussion in `run!` about this in conjunction with Daisyworld (should be in the next hour or so).

**Comment by Datseris** [comment]
use `0.0` instead of `0`. This is not that much different from using `missing`, since `0` is not FLoat64 ;)

**Comment by Libbum** [comment]
Sure. Will do.

**Comment by Libbum** [comment]
**With `missing`**
```
julia> model
AgentBasedModel with 774 agents of type Daisy
julia> @btime collect_agent_data!(agent_df, model, adata, 1)
  10.271 μs (4 allocations: 64 bytes)
  
julia> model
AgentBasedModel with 0 agents of type Daisy
julia> @btime collect_agent_data!(agent_df, model, adata, 2)
  1.695 μs (26 allocations: 1.00 KiB)
```
Implementation:
```diff
   isconcretetype(current_type) || warn("Type is not concrete when using function $(agg) "*
        "on key $(k). Consider using type annotation, e.g. $(agg)(a)::Float64 = ...")
-      types[i+1] = current_type[]
+      types[i+1] = Union{Missing, current_type}[]
    end

    function collect_agent_data!(df, model, properties::Vector{<:Tuple}, step::Int=0)
    alla = allagents(model)
-   push!(df[!, 1], step)
-   for (i, (k, agg)) in enumerate(properties)
-       _add_col_data!(df[!, i+1], agg, k, alla)
+   if length(alla) > 0
+       push!(df[!, 1], step)
+       for (i, (k, agg)) in enumerate(properties)
+           _add_col_data!(df[!, i+1], agg, k, alla)
+       end
+   else
+       push!(df, vcat(step, repeat([missing]; outer=length(properties))))
    end
    return df
end
```


**With 0.0 default**
```
julia> model
AgentBasedModel with 774 agents of type Daisy
julia> @btime collect_agent_data!(agent_df, model, adata, 1)
  9.226 μs (4 allocations: 64 bytes)

julia> model
AgentBasedModel with 0 agents of type Daisy
julia> @btime collect_agent_data!(agent_df, model, adata, 2)
  901.273 ns (3 allocations: 48 bytes)
```

Default is the clean winner. Adding `missing` requires us to *always* initialise an agent aggregate dataframe with all columns other than `step` with `Union{Missing, X}`, since we never know before time if `length(alla) == 0` at any stage throughout the run.

To me, this means making sure users understand this by adding documentation, not by implementing guards. I'll add the docs and push up Daisyworld.

**Comment by Datseris** [comment]
Alright, I agree. Let's simply document this and not do anything. Will also get 3.0 out faster. I always perceived this as not a bug and the users responsibility as well to be honest.
