### ISSUE TITLE
possible test failure in upcoming Julia version 1.5 

### ISSUE THREAD

**Issue by rfourquet** [JuliaDynamics/Agents.jl#247]
A PkgEval run for a Julia [pull request](https://github.com/JuliaLang/julia/pull/29240) which changes the generated numbers for `rand(a:b)` indicates that the tests of this package might fail in Julia 1.5 (and on Julia current master branch).

Also, you might be interested in using the new [StableRNGs.jl](https://github.com/rfourquet/StableRNGs.jl) registered package, which provides guaranteed stable streams of random numbers across Julia releases.

Apologies if this is a false positive. Cf. https://github.com/JuliaCI/NanosoldierReports/blob/ab6676206b210325500b4f4619fa711f2d7429d2/pkgeval/by_hash/52c2272_vs_47c55db/logs/Agents/1.5.0-DEV-87d2a04de3.log

**Comment by Libbum** [comment]
Thanks for bringing this to our attention! I'll have a closer look.

**Comment by Libbum** [comment]
OK, so the TLDR for this is that `Random.seed!(N)` in julia 1.5 may yield a different output, thus our tests will break when using it.

The underlying algorithm changes.  

We can keep an eye on this once we start testing against 1.5.

**Comment by Libbum** [comment]
Travis only swapped to 1.5 today, so this hasn't been a problem up until now. 

I suggest we add `1.4.2` to our travis, and allow `1` to fail for the time being until we sort this out.

**Comment by Libbum** [comment]
Closed in #270.
