### ISSUE TITLE
move_agent! based on new position or an arbitrary velocity for ContinuousSpace models

### ISSUE THREAD

**Issue by balenamiaa** [JuliaDynamics/Agents.jl#248]
Looking through the source code I see that there's no move_agent that uses some position or an arbitrary velocity for ContinuousSpace models. It is pretty trivial to, for example, add a move_agent! method with the signature:
```
move_agent!(agent::A, model::ABM{A,S,F,P}, vel::NTuple{D, N}, dt = 1.0) where {A <: AbstractAgent, S <: ContinuousSpace, F, P, D, N <: AbstractFloat}
```
If I understand correctly the reason is that there's simply no incentive and users are recommended to create a custom move_agent!. But doesn't this pattern repeat enough times so as to warrant being implemented in Agents.jl?

**Comment by Datseris** [comment]
But if an agent is moving with a given velocity, I don't immediately see a reason why this shouldn't be the velocity of the agent...?

**Comment by Libbum** [comment]
This seems like an anti-pattern we'd want to avoid actually. Could you provide us a use case for this kind of method?

It's completely fine for agents to interact with each other, or via some external force (calculated in the model for example) with the current implementation. [`elastic_collision!`](https://github.com/JuliaDynamics/Agents.jl/blob/7bfe524786e8771b5050081e433c97a49ff4a672/src/core/continuous_space.jl#L298) for example provides an agent-agent velocity update.

One could see agents advecting through some turbulent flow for example, but again this can be done via calculating the new agent velocity vector against some turbulent field within the model, then calling `move_agent!(agent, model)` to update its position. It's not exactly the same, but [daisyworld has a temperature field](https://github.com/JuliaDynamics/Agents.jl/blob/7bfe524786e8771b5050081e433c97a49ff4a672/examples/daisyworld.jl#L128) which permeates the space and affects an agents survivability. Something similar to that for external forcing is my current thought process.

**Comment by Datseris** [comment]
> One could see agents advecting through some turbulent flow for example, but again this can be done via calculating the new agent velocity vector against some turbulent field within the model, then calling move_agent!(agent, model) to update its position. 

In this scenario one can provide a function `update_vel!` in `ContinuousSpace`, which will be automatically taken care of when calling `move_agent!`.

**Comment by balenamiaa** [comment]
Sorry for the delayed response. I thought this might come off as an anti-pattern. A use case for example would if you wanted some agents in a continuous space to be attracted to a specific agent temporarily. One way to do it would be to store their old velocities then set the new velocities and when it's over, set the old velocities back. Another way would be to call a move_agent! method that doesn't rely on the agents intrinsic velocity.

**Comment by Datseris** [comment]
Seems reasonable for me, and seems simple enough to code as well! Feel free to put a PR that does it!
