### ISSUE TITLE
FR: function that puts one agent in every grid point

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#260]
Would be nice to create and expose a function to the user that creates and adds a specific agent to every grid point. For example the function could take a pre-initialized agent, and then make copies and put them into the grid.

**Comment by fbanning** [comment]
Wouldn't that just be equivalent to a for-loop over [add_agent_single!](https://juliadynamics.github.io/Agents.jl/stable/api/#Agents.add_agent_single!) until there's no more free space to add agents?

**Comment by Libbum** [comment]
This is more of an indexing & performance requirement under the hood. `add_agent_single!` chooses random positions and checks nodes are empty.

The function we're looking to add here is moreso for mixed agent methods which need a correctly indexed agent across the entire space. Take a look at how Daisyworld is [currently implemented](https://github.com/JuliaDynamics/Agents.jl/blob/0f68e2e66f9c90757833db1d43d4e7d57a785518/examples/daisyworld.j) vs this [daisystruct](https://github.com/JuliaDynamics/Agents.jl/tree/daisystruct) branch.

**Comment by fbanning** [comment]
I might get this wrong but it seems to me that this issue #260 was already solved by adding the `fill_space!` function [here](https://github.com/JuliaDynamics/Agents.jl/blob/daisystruct/src/core/agent_space_interaction.jl). Is that correct?

**Comment by Libbum** [comment]
You're right! @Datseris has just merged something and must have forgot to reference this issue.

**Comment by Datseris** [comment]
Its getting there guys! I just want to resolve a problem with the interactive application!
