### ISSUE TITLE
Conditional agent data aggregation?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#275]
Let's say I have some agents on a `GridSpace` and I have a fairly complicated model where my agents have a lot of properties.

Let's also say there is a property `a` that I realy care about and I want to data collect and aggregate, but I want to do it *conditionally*. Specifically, I want to know the average value of `a` for all agents whose x position is greater than 5. How do we do this with the current interface?

One way is to *not* aggregate agent data, and instead collect all agent positions and `a`. Then, do a DataFrames-based operation to collapse property `a` to its mean but only when some other column `pos` satisfies some other property.

**Comment by Datseris** [comment]
Here is an idea of how to go about it: In the "aggregating" version of data collection, where the user gives a 2-tuple, allow a 3-tuple version:
```
(property, f, b)
```
where `b` is a function that takes as input an agent and returns `true` if its `property` should be data collected and *then* aggragated with `f`.

Will this be performant? Does it play well with our current status of the source code? Haven't checked yet, just thinking out loud.

**Comment by Libbum** [comment]
Not tested, but wouldn't this get you what you need?
```julia
important_a(agent) = agent.pos[1] > 5 ? agent.a : missing #perhaps 0 rather than missing could also work
adata = [(important_a, mean)]
```

**Comment by Datseris** [comment]
Hm, seems like it, but with a bit of a twist:
```julia
julia> mean([1, missing, 2])
missing

julia> mymean(x) = mean(skipmissing(x))
mymean (generic function with 1 method)

julia> mymean([1, missing, 2])
1.5
```
However this does introduce the extra collection of the missings and then the extra skipping them.

**Comment by Libbum** [comment]
This is a general issue we hit when redesigning the collect interface in the first place.

It would be possible to ignore properties thar didn't meet a criteria with something like your `(property, f, b)` suggestion, but then as soon as a user needed `[(property, f, b), (property2, g, c)]`, we have the situation that must provide `missing`s. This caused a performance hit and additional complexity of the collection interface. 

So, unless we can identify a way around this, the case you're interested in here is a job for the low level API.

**Comment by Datseris** [comment]
> [(property, f, b), (property2, g, c)], we have the situation that must provide missings.

Why is this the case? Each run of the elements of `adata` produces and reduces its own vector.

**Comment by Libbum** [comment]
Let me know if my interpretation of this idea is correct or not:
For some set of agents, we want the mean of property a if the x position at a particular step is above 5.
`(a->a.id[1] > 5, mean, a->a.a)`
would produce a dataframe similar to this:

|  step | mean_a_select | 
|-------|----------|
|     0 |        0 |
|     6 |      219.5 | 
|    15 |      278.8 |
|    16 |      299.0 |
|    22 |      312.8 | 
|    50 |      313.1 |

And a second property, maybe `(a->a.id[2] < 5, mean, a->a.b)`

|  step | mean_b_select | 
|-------|----------|
|     0 |        0 |
|     18 |      19.1 | 
|    20 |      28.6 |
|    22 |      31.7 | 
|    50 |      13.5 |

These results would merge to
|  step | mean_a_select | mean_a_select |
|-------|----------|-----------|
|     0 |        0 |       0 |
|     6 |      219.5  |        missing |
|     15 |      278.8 |        missing |
|     16 |      299.0 |       missing |
|     18 |     missing |        19.1 |
|     20 |      missing |        28.6 |
|     22 |      312.8 |        31.7 |
|     50 |      313.1 |        13.5 |

How would the current proposal manage this situation?

**Comment by Datseris** [comment]
Why would the two dataframes have different step...? The step that the data collection occurs in is an idependent variable from what data are collected.

**Comment by Libbum** [comment]
> but I want to do it *conditionally*.

How else would you satisfy this?

**Comment by Datseris** [comment]
I aggregate conditionally over some agents, not conditionally at some timesteps. I get the mean `w` of all agents whose `pos[1] > 5`. I do this at any step regardless.

**Comment by Libbum** [comment]
Ooooh, right. So you're just after a condition of whether or not to include a particular agent within the normal aggregate.

Sure. 
Current implementation:
```julia
function collect_agent_data!(df, model, properties::Vector{<:Tuple}, step::Int=0)
    alla = allagents(model)
    push!(df[!, 1], step)
    for (i, (k, agg)) in enumerate(properties)
        _add_col_data!(df[!, i+1], agg, k, alla)
    end
    return df
end
# Function barrier
function _add_col_data!(col::AbstractVector{T}, agg, k, alla) where {T}
    res::T = agg(get_data(a, k) for a in alla)
    push!(col, res)
end
```

for which we can extend the properties vector (or multiple dispatch a new `collect_agent_data`), then just add a filter:

```julia
condition(agent) = agent.pos[1] > 5
...
res::T = agg(get_data(a, k) for a in Iterators.filter(condition, alla))
```

Performance wise: no change, we modify the iterator before collecting. Would be trivial to do this I think.
