### ISSUE TITLE
Distributed run!

### ISSUE THREAD

**Issue by Jagirhussan** [JuliaDynamics/Agents.jl#279]
I have a fairly large model of 10^7 agents. While I am able to run this model on a large machine, it would be great to simulate such models on a cluster. Could you comment on how I solve models in a distributed manner?

**Comment by Libbum** [comment]
We used to have a distributed example, although our focus has been on other aspects of the framework recently. @kavir1698 has had success with large models before, so hopefully he can give you some pointers.

We track this issue in #243 and perhaps you can find some details in #96. From what I understand, this is possible at the moment, just not documented.

**Comment by Libbum** [comment]
Would be great if you could give us a MWE test case to work on if that's possible too!

**Comment by kavir1698** [comment]
We currently implement pleasingly parallel computation, meaning that several simulations are run in parallel. But we do not have an API to run a single simulation on multiple cores. That would be problem specific, I guess. I have run simulations with about 6 million agents, but they were also on single machines.

**Comment by Datseris** [comment]
I'm closing this as this seems to be outside Agents.jl. A user can do anything distributed they want inside `model_step!`, it is system specific.
