### ISSUE TITLE
Gridspace UndefVarError

### ISSUE THREAD

**Issue by MFaisalZaki** [JuliaDynamics/Agents.jl#292]
GridSpace from some reason is not exported properly to be used later, I'm attaching a screenshot.
Can you help me with this issue?
![Screen Shot 2020-09-12 at 9 59 59 PM](https://user-images.githubusercontent.com/9129265/93004103-3ab8eb00-f544-11ea-8ed2-568bd2e33ccf.png)

**Comment by Datseris** [comment]
I can't reproduce this issue. Besides, our documentation examples are run on Travis. As you can see here: https://juliadynamics.github.io/Agents.jl/stable/examples/forest_fire/ Travis has no problem to find `GridSpace`. Something is wrong with your installation I'd guess?

**Comment by Libbum** [comment]
> I can't reproduce this issue. 
Neither can I.

@MFaisalZaki: what Julia version are you using?

**Comment by MFaisalZaki** [comment]
I have removed uninstalled Julia with its packages then installed only Agents and now it works, for now things are working I'll reinstall my other packages and I'll reopen the issue in case it occurred again.

Thanks
