### ISSUE TITLE
Integrate PkgBenchmark

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#297]

**Comment by Datseris** [comment]
Here is how I did it for billiards:

https://github.com/JuliaCI/PkgBenchmark.jl

https://github.com/JuliaDynamics/DynamicalBilliards.jl/blob/master/benchmark/benchmarks.jl

**Comment by Datseris** [comment]
We should benchmark fundamentally basic functions: `move_agent!`, `add_agent!`, `find_neighbors`, etc, in all types of space. We could also benchmark the low-level data collection API.
