### ISSUE TITLE
Documentation trackbacks to examples in function docstrings

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#305]
In our example files, we use `[link](@ref)` to refer to the API. 

Something that would be helpful to the documentation (and great for a fist issue to a new contributor!), would be links that track back from the API documentation to specific places in the examples where that function is used.

As an example, the current docstring for `kill_agent!`:
```julia
"""
      kill_agent!(agent::AbstractAgent, model::ABM)
Remove an agent from model, and from the space if the model has a space.
"""
```

may read:
```julia
"""
      kill_agent!(agent::AbstractAgent, model::ABM)
Remove an agent from model, and from the space if the model has a space.

Example usage in:
- [Bacteria Growth](@ref): [model_step!](@id bg_kill_agent)
"""
```

**Comment by Datseris** [comment]
PRetty good idea!
