### ISSUE TITLE
How to get current step during model run

### ISSUE THREAD

**Issue by fbanning** [JuliaDynamics/Agents.jl#308]
I'd like to use the current step during a model run (in my case to use it in a stepping function). What's the best way to do this?

**Comment by Datseris** [comment]
Make a `step` parameter and increment it by 1 in `model_step!`.

**Comment by fbanning** [comment]
Yes, that's what I thought but wanted to make sure I didn't miss any integrated feature.

Would it make sense to have a step parameter integrated in the framework?

**Comment by Datseris** [comment]
We have considered this before. The only sensible way to do it would be to have the function `model_step` always accept two arguments, the second being the current step. I don't think this mandatory increase of complexity is worth it, given how trivial it is to do it with the method proposed here.

**Comment by Libbum** [comment]
[Daisyworld](https://juliadynamics.github.io/Agents.jl/stable/examples/daisyworld/) uses `tick` for example. 

I'm torn about this one myself. It was the first 'issue' I came across when using Agents. 

It's really only needed for a subset of models, so I agree with @Datseris concerning leaving it out of the standard mechanics, but at the same time, perhaps we need to add a sentence in the tutorial page (something new users see initially) about this quirk we have.

**Comment by Datseris** [comment]
> there it was very easy to use the current tick/step of the simulation in every situation.

I believe that it is very easy here as well, but you should correct me if you think the proposed solution here is not easy.

Could you also suggest where is the most fitting place in the docs to add this?

**Comment by fbanning** [comment]
It is easy to do in Agents.jl as well, I agree. What I meant with that is that in NetLogo there's the [ticks](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#ticks) keyword built-in and ready to use (i.e. no intermediary step needed).

**Comment by Datseris** [comment]
> add a sentence in the tutorial page (something new users see initially) about this quirk we have.

Yeah that's a good place
