### ISSUE TITLE
Relating ABM with statistics

### ISSUE THREAD

**Issue by sbacelar** [JuliaDynamics/Agents.jl#31]
This is just a suggestion to write some examples relating to ABM and statistical analysis. I have been working with `R-Extensions` for `NetLogo` and I think that within Julia it should be easy to incorporate ABM and statistical analysis without recurring to two languages.

**Comment by kavir1698** [comment]
Do you have a specific analysis in mind? There are several established statistical package for Julia. And it should be straight forward to analyze the outputs of Agents.jl, which is in DataFrame format, with those packages.

**Comment by sbacelar** [comment]
I have no specific analysis in mind. Any simple example would do, like those examples found in [R-Extension](https://github.com/NetLogo/R-Extension). This is a very simple example (`example1.nlogo`) from `R-Extension`. But, probably you could use one of the classical examples you published in `Agents.jl`to illustrate that.
```
extensions [r]
to test
  clear-all
  ;; get a value from r
  print "r:eval..."
  print "rnorm(10):"
  print r:get "rnorm(10)"
  print " "
  ;; create a list in r from agentset
  crt 10
  [
    set xcor random-xcor
    set ycor random-ycor
  ]
  (r:putagent "agentlist" turtles "who" "xcor" "ycor")
  print "r-class of agentlist: "
  print r:get "class(agentlist)"
  print " "
  print "variable names of agentlist:"
  print r:get "names(agentlist)"
  print " "
  print "agentlist$xcor: "
  print r:get "agentlist$xcor"
  print " "
  print "agentlist$ycor: "
  print r:get "agentlist$ycor"
  print " "
  print "correlation coefficient between xcor and ycor: "
  print r:get "cor(agentlist$xcor, agentlist$ycor, method='spearman')"
end
```

**Comment by Datseris** [comment]
I think we should close this issue. First of all, the documentation of Agents.jl is now much, much stronger than before. Secondly, what is asked here is not related with the offered functionality of Agents.jl and thus should not be our duty to illustrate how to use the DataFrame once you get it.

**Comment by kavir1698** [comment]
>  what is asked here is not related with the offered functionality of Agents.jl and thus should not be our duty to illustrate how to use the DataFrame once you get it.

I also don't see a good reason to demonstrate statistical analysis with Julia in Agents.jl's documentation.
