### ISSUE TITLE
New continuous space specification: CompartmentSpace

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#313]
PR https://github.com/JuliaDynamics/Agents.jl/pull/311 altered the underlying GridSpace fundamentally, and now enables us to move forwards with a new version of Continuous Space which I believe will have large performance benefits over the existing one. This is to be proven of course, but given that just `move_agent!` [takes micro seconds instead of nanoseconds in continuous space](https://github.com/JuliaDynamics/Agents.jl/pull/299#issuecomment-694779393), it is pretty clear that we will get at least a full order of magnitude speedup. 

The new space will be called CompartmentSpace until we its PR is fully operation. If it indeed has better performance in every aspect, it will replace the current continuous space entirely.

# Core idea
The agent and position types in CompartmentSpace are as were before. The new space now has as part of its field a `GridSpace` instance. A number `x::Float64` defines the grid spacing with respect to real space. e.g. if the user creates a CompartmentSpace with real dimensions (10.0, 20.0) and the grid spacing is 0.1, the the underlying GridSpace will have size (100, 200). Internal test ensures `x` is such that `10.0 / x == Integer`.

All agents in the CompartementSpace are being kept track of in the underlying GridSpace as well. This means that our `add_agent` and `move_agent` functions take care to first update the agents floating type position, but then also update its position in the underlying grid space if e.g. the `move` made the agent move enough to change grid cell.

`move_agent` obtains two versions: `move_agent(agent, model, dt::Real)` and `move_agent(agent, pos, model)`. The first one simple calculates what is the next position of the agent and calls the later version. The later version checks if the agent changes grid cell or not.

**Our new space specification protocol in the file `src/core/space_interaction_API.jl` makes it clear on how to implement a new space**.

# Finding neighbors
Now, main part we care about is `space_neighbors(position, model, r)` (soon to be renamed to `nearby_agents`). Here is the gist of it.

1. `space_neighbors` has a keyword argument `exact = false`. Just like how the space_neighbors of GraphSpace also has a keyword argument.
1. If `exact=false` we do as follows (please see image below)
    1. First we calculate the displacement of the given position from the center of the grid cell, `δ`, given by blue color below
    1. Calculate  `r' = ceil((r+δ)/x)`, which covers the maximum possible further cell the search radius cloud reach.
    2. Using the underlying grid space, find all cells that are within `r'`.
    3. Return all agents within those cells, exactly like it is done in GridSpace (see its implementation of `space_neighbors(pos, model)`
1. If `exact = true`, then 
    1. We have to split the collection of grid cell locations into two steps: in the first step we collect all grid cells that are **absolutely guaranteed** to be entirely contained within the search radius. These are with green color below and are easy to find analytically. All agent ids in those cells are part of the output
    2. We separately collect the cells that are in purple color, which also can be found analytically where they should be. 
    3. For all agents in the purple cells, we iterate using a formal call to `filter!`, according the distance of the agents' position and the given position in `space_agents`.

![image](https://user-images.githubusercontent.com/19669089/93688683-ce9c3100-fac7-11ea-8dfa-62366ae3778b.png)

The image is for euclidean distance, same can be done for Chebyshev distance. Although, to be frank, continuous space and Chebyshev metric don't make much sense to me and perhaps we should drop Chebyshev support.

(I only added colors to the upper half of the image, too lazy to put everywhere!)

What do you think? Don't forget that our new GridSpace is **very fast**.

**Comment by Libbum** [comment]
Completely understandable now. Sounds great!

Yeah, in continuous space Chebyshev may not be necessary, but I don't know. Since its on the hypercube, exact=false and exact=true will be the same, so that's nice at least.

**Comment by Datseris** [comment]
> Since its on the hypercube, exact=false and exact=true will be the same, so that's nice at least. 

Not quite. The outer-most shell of the hypercube is ambiguous and needs to be checked agent-by-agent depending on the exact value of `r` (because `r` is real for continuous space and the actual grid could be sliced at arbitrary point even in chebyshev space).

I vote to drop chebyshev in the new continuous space :D

**Comment by kavir1698** [comment]
I'll start working on it.
I suppose this is a similar to how NetLogo implements continuous space. If we use only this implementation, will we be able to say that we have continuous space? Right now, in the paper, we say Mesa has it but NetLogo doesn't

**Comment by Datseris** [comment]
I don't know what NetLogo does to be honest, but for me it is clear that what I describe above is in every sense continuous space. The agents positions are Float64, so are their velocities. The neighbors can be found in a true Float64 and the result of teh true Euclidean norm is returned. Why would it not be continuous space? More specifically, why is the current version with the database more "continuous" than this proposal?

If NetLogo also satisfies these requirements, and can return *exactly* true neighbors based on a real-valued euclidean distance, then it also has continuous space (provided that agent positions can be floats and agents can move in any direction, not only the ones predefined by the grid).

@Libbum in MASON, can agent positions be floats? Because I think MASON has our implementation here but they don't have the `exact = true` version, right?

**Comment by kavir1698** [comment]
It is an approximation of continuous space, isn't it? The higher the resolution of the grid, the closer will be the behavior of the model to a continuous space. For example:

> First we calculate the displacement of the given position from the center of the grid cell, δ, given by blue color below

`r` or `r'` is not centered on the exact position, but from the center of a cell.

**Comment by Datseris** [comment]
Not it is not an approximation, have a look at my specification for the `exact = true` version: If the user wants performance, they can get the approximate version, but the exact version is exactly as it is in real space.

**Comment by Datseris** [comment]
the filtering in `exact` is done based on the given position, not on the centered one.

**Comment by kavir1698** [comment]
I see. Great then!

**Comment by Libbum** [comment]
I need to dig more in light of these changes. At the moment, my understanding is that 

- Netlogo has no Continuous space as we call it.
- Mesa has Continuous space as we currently implement it
- MASON has a Continuous space which is more specifically a Compartment space as we define it here.

This implementation of the Compartment portion of the space is solely for neighbor lookup etc., and therefore in my view (and the view we should take) it is a 'true' Continuous space, not an approximation, but has an underlying lookup table to make things more efficient.

MASON: Internally, Continuous2D and Continuous3D do not actually store Objects at their Double2D or Double3Dlocations. Instead, they define a virtual grid of Int2D or Int3D locations and store Objects in this grid. The Objects still are related with their Double2D and Double3D locations, so it’s more or less transparent

They cannot do 3D, but do have `exact=true` for point objects on non-periodic 2D spaces.

**Comment by Libbum** [comment]
I've been doing some more digging, and I *think* I might have uncovered a few details about NetLogo and MASON implementations.

Whilst we thought NetLogo didn't contain a continuous space implementation (like Mesa's and our present version), it *does* contain something like what MASON does.

So what happens, in our language, is that they keep their GridSpace implementation, but allow agents to have a `Tuple{Float64, Float64}` position. Specifically, they separate agent types. A **Patch** is an agent that sits in a discrete position. A patch cannot move, but works like an agent (similar to `Land` in daisyworld for us). **Turtles** are an agent type that can reside anywhere within a 2D plane 'a turtle can be positioned at any point within its patch; it doesn’t have to be in the center of the patch'. 

The ContinuousSpace implementation therefore is an extension of the GridSpace methods for this Turtle agent type.
- They don't have a velocity, but have a 'forward direction'. You move them manually `fd 1` moves you to the next patch (`fd 0.2` is possible though)
- `distance agent` gets you a Patch&ndash;Patch measurement (grid distance). Also possible to use a Turtle&ndash;Patch here, but you will get the Patch&ndash;Patch distance.
- `distance x y` where `x` and `y` are floats. If this is Turtle&ndash;Turtle, you get the euclidean distance, otherwise its effectively the same as `distance agent`
Everything else is built on top of this essentially.

So what this means for us is that CompartmentSpace will end up aligning to NetLogo and MASON's ContinuousSpace implementation, and move us away from Mesa's version.

**Comment by kavir1698** [comment]
>     1. We have to split the collection of grid cell locations into two steps: in the first step we collect all grid cells that are **absolutely guaranteed** to be entirely contained within the search radius.

For that, I think `r` should be centered on the given position, rather than cell center, no?

**Comment by Datseris** [comment]
Yes, that is correct
