### ISSUE TITLE
Allow search radius in GridSpace to be a Tuple (different value for each dimension)

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#314]
It is quite straightforward(*) to change the neighbor finding code in grid space to allow for `r` to be a tuple as well, so that across each dimension a different radius is used. This will make the higher dimensionality of the space truly useful. Imagine you had some 3D problem, and you want the 4th dimension to actually mean a property of whatever: color, class, wealth, I don't know. Then you can find agents not only by proximity in real space, but also in the 4th dimension, that property.

(*) this is trivial for chebyshev norm by simply broadcasting the code. For euclidean space it is not possible.

**Comment by Libbum** [comment]
Sounds good! We'll need to come up with a decent example to showcase this.

**Comment by Libbum** [comment]
Maybe we could do another daisyworld where temperature is on the gridspace?

**Comment by Datseris** [comment]
Hm, this format is not suitable for real values though, and due to the diffusion, you don't really want to discretize the temperature...

**Comment by Libbum** [comment]
Perhaps not with this particular extension&mdash;fair point.

Although, with ND gridspace, rather than discretize temperature in a model in the array, or in an Agent (like we have currently), I wonder what gains (if any) there are with temperature on the grid?

**Comment by Datseris** [comment]
I think I confused you. The point here is that a specific property of an agent can correspond instead to its `n`-th spatial dimension. Imagine age for example, or some other property that can be discretized into the integers and has a finite span.

The first two dimensions of the space could be actual physical spatial dimensions while the third dimension could be age. Then when you search agents, you find agents not only nearby in real space, but also nearby in "agent space".

The case of temperature is different. Temperature itself is a spatial field and thus has a specific value at each point in space.

> I wonder what gains (if any) there are with temperature on the grid?

You're talking about a grid that specificallly has a temperature value? That is I think the same thing as having an array as temperature in the model properties (same as original version of Daisyworld). Is there any difference?

**Comment by Libbum** [comment]
I follow that point, was just considering if we have any existing models with properties we could extend into this dimension and not have to come up with a completely new example.

> You're talking about a grid that specificallly has a temperature value? ... Is there any difference?

Perhaps not. Just throwing around ideas.

**Comment by Libbum** [comment]
Playing around with this one, looks like the lowest primitive we need to extend is `initialize_neighborhood!`. 
Here's a start:
```julia
function initialize_neighborhood!(space::GridSpace{D}, r::NTuple{D,Real}) where {D}
    @assert space.metric == :chebyshev "Cannot use tuple based neighbor search with the Euclidean metric."
    d = size(space.s)
    r0 = (floor(Int, i) for i in r)
    βs = vec([CartesianIndex(a) for a in Iterators.product([(-r_0):r_0 for r_0 in r0]...)])
    whole = Region(map(one, d), d)
    hood = Hood{D}(whole, βs)
    space.hoods[float(r)] = hood # This doesn't fit.
    return hood
end
```

Since `space.hoods` is a `Dict{Float64,Hood{D}}`, the `float(r)` isn't going to allow us to store the generated hood easily. Any suggestion on how we should handle these complex parameters? The dirtiest way would be something like `float(prod(r))`, and hope that users don't need search radii that large. A second option may be to change to a `Dict{NTuple{D,Float64},Hood{D}}` and store the single value as `Tuple(fill(float(r),D))`.

**Comment by Datseris** [comment]
Thankfully this is not breaking as these internals are not part of the API. So we can think how to go about it after 4.0

**Comment by Datseris** [comment]
The simplest way is to make `space.hoods` a `Dict{T, Hood{D}}` and parameterize on `T` wich can be float or tuple

**Comment by Datseris** [comment]
no wait I have already tought about this... the solution is just one more field `hoods_tuple` which would be a `Dict{Tuple, Hood{D}}`.
