### ISSUE TITLE
Make an explicit `rng` field part of `ABM`?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#321]
The `rng` field will contain some random number generator like a `MersenneTwister`. This will be used in functions like `random_position` I guess. Should we do it? Is there any actual benefit? because Calling `Random.seed!` at the start of your script should in principle lead to same results...?

**Comment by Libbum** [comment]
This could also allow one to use a Poisson or Normal distribution of numbers for example, but I'm not sure how useful that is under the hood. In fact, I may even suggest not allowing this to be anything other than a `MersenneTwister`. Many of our functions should only use a uniform distribution. 

What it does do is allow us to do this "checkpointing" that MASON does. I took a little dive into trying to get the GLOBAL_RNG value at any given time a while back, but was unsuccessful there.

**Comment by Datseris** [comment]
The problem however is that if any user defined step function uses random nunbers, they should use `model.rng`. But I tried to dissallow accessing fields of the model because I want to keep the internals detached from the API...

**Comment by Libbum** [comment]
Yeah, in addition, what if I want numbers from Uniform, Normal and Poisson in the same model? I can't use `model.rng` there, nor can I save state via a checkpoint...

**Comment by Datseris** [comment]
For me it is difficult to imagine what it means to use a Poisson distribution to get a random position. Positions are discretized, so how does this work...?

**Comment by Libbum** [comment]
That's kind of my point, I don't think we should allow this.

Say a user needs a random number from a Poisson distribution (like in [SIR](https://github.com/JuliaDynamics/Agents.jl/blob/3f77991239def65175338d01cbf6ea32aa756ea4/examples/sir.jl#L236-L237)), so they set `model.rng` to come from Poisson. That means they'd be incorrectly sampling across the rest of the model. Poisson is discrete too, it would mean sampling particular areas of space more frequently than others. We need to remove this as a possibility I think.

**Comment by Datseris** [comment]
having a seed inside the model is just as much of an issue, because a user that selects a random agent (random neighbor) will not be using this seed but the global one, as they will be doing this selection in `agent_step!`.

**Comment by Datseris** [comment]
Seems to me all problems are resolved by adding `Random.seed!(whatever)` at the start of the script and this is a good point to not look at how other software do it.

**Comment by Libbum** [comment]
100% agreed.
