### ISSUE TITLE
Collecting data in mixed-ABMs is mostly unhandled

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#335]
I think there's something here we haven't taken into account.

Suppose I have a mixed model of `Union{Wolf, Sheep}` and I want to get a property from `Wolf` that doesn't exist in `Sheep`. I'm not interested in aggregate data at present, but we may need to cover that example too.

Say `wolf.range`. Perhaps I could provide a helper
```julia
w_range(a) = hasfield(typeof(a), :range) ? a.range : missing
```
So my expected collection here would output a range value for each wolf and a missing value for each sheep. The problem is that if the *first* agent in the schedule is a `Sheep`, the dataframe will be constructed with a `Missing` type, not a `Union{Missing,Float64}`. Then, an error at runtime
```julia
┌ Error: Error adding value to column :w_range.
└ @ DataFrames ~/.julia/packages/DataFrames/cdZCk/src/dataframe/dataframe.jl:1301
ERROR: MethodError: convert(::Type{Union{}}, ::Float64) is ambiguous. Candidates:
  convert(::Type{Union{}}, x) in Base at essentials.jl:169
  convert(::Type{T}, x::Number) where T<:Number in Base at number.jl:7
  convert(::Type{T}, arg) where T<:VecElement in Base at baseext.jl:8
  convert(::Type{T}, x::Number) where T<:AbstractChar in Base at char.jl:179
  convert(::Type{T}, obj) where T<:FunctionWrappers.FunctionWrapper in FunctionWrappers at /home/tim/.julia/packages/FunctionWrappers/OAZAk/src/FunctionWrappers.jl:85
Possible fix, define
  convert(::Type{Union{}}, ::Number)
```

The reason why this is dependent on the first value is that we assume the result type of the collection of one agent is the same for all agents. That's true in the single agent case, but should somehow be handled differently in the mixed case.

I don't want to have to change schedulers on the model here; what if I also have a `Sheep` property that isn't in `Wolf`? The same problem would occur.

How should/can we best filter agent properties in this scenario?

**Comment by Datseris** [comment]
Why not use the filtering-based data collection that you contributed? the 3-tuple syntax?

**Comment by Datseris** [comment]
By the way, my personal take on this is "use low level API and write your own data collection instead". I wouldn't try too hard to take care of it in the software and keep the API clean.

**Comment by Libbum** [comment]
> Why not use the filtering-based data collection that you contributed? the 3-tuple syntax?

Since that's only for aggregate data

> use low level API and write your own data collection instead

Can certainly implement something with that. Just wondering if there's a simple API we can design to allow collection through `run!` in this case or not.
Will post a solution from the low level later and see what we see.
