### ISSUE TITLE
TravisCI

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#340]
We need to take a look at Travis again. [Things are moving beneath our feet](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works).

- Testing on macos may cost us money [details](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)
- travis.org will be read only by the end of the year [details](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions)

**Comment by Datseris** [comment]
god fucking damn it.

**Comment by Datseris** [comment]
So what is the status quo? We have to change testing service? To what? I thought GitHub actions were used to trigger bots and existing things, how can they test your code...?

**Comment by Datseris** [comment]
https://discourse.julialang.org/t/travis-ci-changes-pricing-plans/49528

**Comment by Datseris** [comment]
https://github.com/invenia/PkgTemplates.jl/blob/master/test/fixtures/AllPlugins/.github/workflows/ci.yml

**Comment by Datseris** [comment]
Another contributor of JuliaDynamics found out how to do this and has described it in detail here: https://github.com/JuliaDynamics/Entropies.jl/issues/42#issuecomment-733694502
