### ISSUE TITLE
Confusion about current (released) version

### ISSUE THREAD

**Issue by BenediktAllendorf** [JuliaDynamics/Agents.jl#344]
The changelog suggests, that v4.0 is already finished/released, but that's not the case, is it? Maybe add an "unreleased" to the latest version in the changelog to make that clear - because I got excited about the new version and it didn't update. ;)

Still v7.3.1 here :https://github.com/JuliaRegistries/General/tree/master/A/Agents

**Comment by Datseris** [comment]
I'll add the "unreleased" tag. As far as the docs as concerned, you can see the version here:

![versions](https://user-images.githubusercontent.com/19669089/99531832-a172de80-29a3-11eb-83de-fa6de0704161.PNG)
