### ISSUE TITLE
Challenging the design and complexity of `walk!`

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#352]
I've been thinking about the new `walk!` function, and I don't think its design is good. It suffers from the (somewhat arbitrary) complexity of introducing 8 new types and 1 new abstract type, while making selecting a random direction difficult, since Julia is a compiled language. Choosing a type North, East etc. at random doesn't play well with type deductions.

I propose to completely remove all this North, East stuff and instead allow `walk` to take a 2-tuple as second argument:

```
walk!(agent, direction::Tuple{Int, Int}, model)
```
this has the benefit that we can define easily the dispatch method
```
walk!(agent, ::typeof(rand), model) = walk!(agent, (rand(-1:1), rand(-1:1)), model
```

**Comment by Datseris** [comment]
@mbruna we can add a clause `ifempty::Bool = false` where if `true` would only move the agent if the position doesn't have any more empty agents. That is simple to do.

**Comment by Libbum** [comment]
This could ultimately expand to `NTuple{D, Int}` for `GridSpace{D}` really. So ND random walks would also be possible. Good plan.
