### ISSUE TITLE
Use `Dims{N}` rather than `NTuple{N,Int}` in gridspace agent structs.

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#361]
I'm wondering if it may feel more 'simple' if we were to change out examples to use [Base.Dims](https://docs.julialang.org/en/v1/base/arrays/#Base.Dims) `pos::Dims{2}` or whatever, rather than having users write out the tuple explicitly.

```julia
mutable struct Agent <: AbstractAgent
	id::Int
	pos::Tuple{Int, Int, Int}
	flag::Bool
end
```

vs

```julia
mutable struct Agent <: AbstractAgent
	id::Int
	pos::Dims{3}
	flag::Bool
end
```

**Comment by Datseris** [comment]
I didn't even know this existed. Hell yeah!!! I will immediately use it in my work now that I know it exists, it makes much more sense.

**Comment by Libbum** [comment]
I essentially just came across it too. 
Sweet, I'll write up a PR.
