### ISSUE TITLE
Change Type parameterization order for ::ABM, make `Space` first

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#364]
It is almost exclusively the case that we dispatch on the _second_ type parameter of `ABM`, the space type. Perhaps it makes sense to make this type first in the type paraterization, so we no longer have to write `::ABM{A, GridSpace} where {A<:AbstractAgent}`, but simply `::ABM{GridSpace}` ?

Besides the fact that we have to do this change throughout the source, is there any downside? The simplification upside is huge I believe.

**Comment by Libbum** [comment]
There's no downside I can think of right now.

I think it makes sense to keep function order the same and just change internals here. But good suggestion!
