### ISSUE TITLE
[FR] Inheritance from pre-defined agent types

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#365]
c.f discussion here: https://discourse.julialang.org/t/composition-and-inheritance-the-julian-way/11231/4

I've been thinking this for a long time now, because we kind of force the user to make a type with given fields at given order, we could simplify with making a 
```julia
mutable type ContinuousAgent{D}
id::Int
pos::NTuple{D, Float64}
end
```
and the user could do
```julia
@inherit Agent ContinuousAgent{2}
w::Float64
end
```

and the new open street map space made me rethink about it. The post above provides a simple macro to do this, all in all I think it is not a bad idea? I definitely think this is more reasonable than enforcing extension of a `pos` function the standard Julian way.

**Comment by Libbum** [comment]
Would take some design consideration, but in general this would indeed be nicer. I've used something like this before in [DICE.jl](https://github.com/Libbum/DICE.jl/blob/master/src/Abstractions.jl), which was quite helpful.

**Comment by Libbum** [comment]
The good thing about this is that each space will have an agent type, so we may not even need to worry about #366, since we can dispatch on `GridAgent` when needed, and `GridSpace` otherwise.

**Comment by Datseris** [comment]
I still think the dispatch should happen on the space nevertheless, because the suggestion here is that using this subtyping system is _optional_ (because it reduces code clarity after all).

I'll put together a draft once I'm doing reviewing the rest of the PRs.

**Comment by Libbum** [comment]
Oh, but I've just done it.
