### ISSUE TITLE
[DOCS] examples of non-grid spaces 

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#37]
I think it would be great, and useful, if examples of scientific research using non-grid (i.e. arbitrary graphs) as spaces for agent based modelling are presented/cited in the documentation.

After I am done with #24 #36 we could also consider implementing one of these examples in this library.

**Comment by yuxiliu1995** [comment]
Some ideas:

Examples from Complexity Explorables: https://www.complexity-explorables.org/topics/agent-based-models/

* Ising model
* Herd immunity model
* Opinion in a network https://www.complexity-explorables.org/explorables/echo-chambers/
* [Epidemic Dynamics on an Adaptive Network](https://core.ac.uk/download/pdf/44186473.pdf)
* Economics and finance. See [To bail-out or to bail-in? Answers from an agent-based model](https://core.ac.uk/download/pdf/33971665.pdf), [Bubbles, crashes and intermittency in agent based market models](http://finance.martinsewell.com/stylized-facts/scaling/GiardinaBouchaud2003.pdf)

**Comment by Datseris** [comment]
Oh wow, besides the Ising model (which is traditionally associated with spatial structure), these examples are awesome!

**Comment by kavir1698** [comment]
We have now examples of graph spaces (SIR model) and continuous spaces (Boid flocking). Can this issue be closed?
