### ISSUE TITLE
Bug in ContinuousSpace constructor

### ISSUE THREAD

**Issue by AayushSabharwal** [JuliaDynamics/Agents.jl#379]
**Describe the bug**
If the `spacing` parameter of continuousSpace isn't assigned explicitly, it evaluates to the default value of `min(extent)/10.0`. However, this raises an error that `min` isn't defined for a `Tuple`. Shouldn't this be `min(extent...)/10.0`?

**Minimal Working Example**
`space = ContinuousSpace((10., 10.))`

**Agents.jl version**
dev (`] add Agents#master`)

**Comment by Libbum** [comment]
Great catch! That should be picked up in tests. I'll fix it right away.
