### ISSUE TITLE
running example in the document, but given error " UndefVarError: abm_plot! not defined"

### ISSUE THREAD

**Issue by danielchen26** [JuliaDynamics/Agents.jl#387]
**Describe the bug**
Running the following example.
https://juliadynamics.github.io/Agents.jl/stable/examples/schelling/

**Minimal Working Example**
In this example, at the bottom of the example page
```
scene, adf, modeldf =
abm_data_exploration(model, agent_step!, dummystep, parange;
                ac = groupcolor, am = groupmarker, as = 1,
                adata = adata, alabels = labels)
```
gives me error : `UndefVarError: abm_plot! not defined`

**Agents.jl v4.0.1**

**Comment by AayushSabharwal** [comment]
Which version of `InteractiveChaos` (now `InteractiveDynamics`) are you using?

**Comment by danielchen26** [comment]
julia> Pkg.status("InteractiveChaos")
Status `~/.julia/environments/v1.5/Project.toml`
  [81850811] InteractiveChaos v0.12.3

**Comment by AayushSabharwal** [comment]
Does calling `abm_plot` work?

**Comment by danielchen26** [comment]
julia> abm_plot
abm_plot (generic function with 1 method)

Yes!

**Comment by AayushSabharwal** [comment]
The function exists, but can you call it? Does it produce an output plot?

**Comment by danielchen26** [comment]
Should I call it like this?  abm_plot(SchellingAgent)
where SchellingAgent is the model

**Comment by danielchen26** [comment]
julia> abm_plot(schelling2)
(Scene (600px, 600px):
  14 Plots:
    ├ Combined{AbstractPlotting.poly,Tuple{Array{Array{Point{2,Float32},1},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.annotations,Tuple{Array{Tuple{String,Point{2,Float32}},1}}}
    ├ Combined{AbstractPlotting.text,Tuple{String}}
    ├ Combined{AbstractPlotting.lines,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.linesegments,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.annotations,Tuple{Array{Tuple{String,Point{2,Float32}},1}}}
    ├ Combined{AbstractPlotting.text,Tuple{String}}
    ├ Combined{AbstractPlotting.lines,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.lines,Tuple{Array{Point{2,Float32},1}}}
    ├ Combined{AbstractPlotting.lines,Tuple{Array{Point{2,Float32},1}}}
    └ Combined{AbstractPlotting.text,Tuple{String}}
  1 Child Scene:
    └ Scene (484px, 484px), Helper structure for stepping and updating the plot of an agent based model. It is outputted by `abm_plot` and can be used in `Agents.step!`.
)

**Comment by AayushSabharwal** [comment]
Hmmm. I just checked out the InteractiveDynamics page, it appears as though this is a tracked bug https://github.com/JuliaDynamics/InteractiveDynamics.jl/issues/34.

I would recommend using `InteractiveChaos#0.11.1` instead, the new Makie.jl based backend is still a work in progress.

**Comment by danielchen26** [comment]
It does not seems that I can revert it back?

(@v1.5) pkg> add InteractiveChaos#0.11.1
    Cloning git-repo `https://github.com/JuliaDynamics/InteractiveChaos.jl.git`
   Updating git-repo `https://github.com/JuliaDynamics/InteractiveChaos.jl.git`
ERROR: Did not find rev 0.11.1 in repository

**Comment by AayushSabharwal** [comment]
You probably have to do `rm InteractiveChaos` then `add InteractiveDynamics#0.11.1`

**Comment by danielchen26** [comment]
(@v1.5) pkg> rm InteractiveChaos
Updating `~/.julia/environments/v1.5/Project.toml`
  [81850811] - InteractiveChaos v0.12.3
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [81850811] - InteractiveChaos v0.12.3

(@v1.5) pkg> add InteractiveDynamics#0.11.1
ERROR: The following package names could not be resolved:
 * InteractiveDynamics (not found in project, manifest or registry)

(@v1.5) pkg> add InteractiveDynamics#0.11.1
ERROR: The following package names could not be resolved:
 * InteractiveDynamics (not found in project, manifest or registry)

(@v1.5) pkg> add InteractiveChaos#0.11.1
   Updating git-repo `https://github.com/JuliaDynamics/InteractiveChaos.jl.git`
ERROR: Did not find rev 0.11.1 in repository

**Comment by AayushSabharwal** [comment]
Try running `registry update` before adding the package. I'm not entirely sure how this works out after the rename

**Comment by danielchen26** [comment]
Ok, Thanks. I will try it.

**Comment by Libbum** [comment]
Hi all,
Yes, sorry - there's a lot of churn in the interactive portion of the plot system. We are waiting for the name change to go through to InteractiveDynamics, then we can solve this issue. May be another day until its done.

**Comment by Datseris** [comment]
Fixed in InteractiveDynamics.jl version 0.13.1

Really sorry about this, I have simply forgotten to push the updated code for the interactive application.

**Comment by Libbum** [comment]
@danielchen26, I just tagged v4.0.3 which adjusts the documentation to reflect the name changes etc. (may take 30 mins or so to update). If you now add the latest `InteractiveDynamics`, things should work as the documentation will reflect.

**Comment by danielchen26** [comment]
Thanks, it works now. The Makie interactive plot is sometimes rendered slow on my machine. I am also trying it on mac M1. But it seems that GLMakie does not compile correctly. It gives me this error `┌Warning:GLFW.GLFWError(GLFW.PLATFORM_ERROR, "Cocoa: Failed to find service port for display")`. Do you know what this issue is? or is it Makie not ready for M1 yet?

**Comment by Libbum** [comment]
Hmm. Quite far out of my line of expertise I'm afraid. Best to post an [issue on GLMakie](https://github.com/JuliaPlots/GLMakie.jl/issues) or ask about the problem on `#makie` in the [Julia slack](https://julialang.org/slack/).

**Comment by danielchen26** [comment]
ok, thanks!

[Tianchi Chen - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=vov4x)	[vov4x]

On January 29, 2021 at 18:15 GMT, Tim DuBois <notifications@github.com> wrote:

Hmm. Quite far out of my line of expertise I'm afraid. Best to post an [issue on GLMakie](https://github.com/JuliaPlots/GLMakie.jl/issues) or ask about the problem on #makie in the [Julia slack](https://julialang.org/slack/).
