### ISSUE TITLE
doubled information: agent.pos and space.agent_positions

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#40]
Seems to me that for any agent, the information contained in `agent.pos` and `space.agent_positions` is fully equivalent and convertible from one form to another.

Is this true? If it is true, then **why** should both informations exist? 

Can't one get away by completely removing the `pos` field of the agent struct?

**Comment by Datseris** [comment]
I think I understand why: it would be terribly inneficient to do such conversion every time you search for a specific position.

**Comment by kavir1698** [comment]
Yes. But here is actually something I have been thinking about a lot. Now that you mention it, it maybe a good time to discuss it.

I am looking for a more efficient way of storing agent positions in the `space.agent_positions` vector. Right now, agent IDs are saved in the `space.agent_positions` vector. The problem is that whenever one wants to retrieve all the agents in a node, we have to find agents that correspond to the IDs saved in a node. The `id_to_agent` function does that with the following implementation:

```jl
function id_to_agent(id::Integer, model::AbstractModel)
  agent_index = findfirst(a-> a.id==id, model.agents)
  agent = model.agents[agent_index]
  return agent
end
```

The first line of this function is a major bottleneck. I once tried to save `Ref`s to the agents instead of their IDs in the `space.agent_positions` vector. But it turned out to be even slower. Do you have any suggestion for this situation?

The "forest fire" example is a good model to test the performance of different the performance of our ideas regarding this issue.

**Comment by Datseris** [comment]
I think a smart way to resolve this is to **not allow users to provide the Agent ID**. Each agent gets an id when added to a model, and the agent's id is just the number it was added at, starting from 1 and incremeting by 1 for each agent.

Then the agent's ID is the same as the agent's index in the `model.agent` vector.

I don't see a reason why the user would have to specify the agent ID. Once again this seems to me a 100% internal information the user should never have to care about, similarly with making the `agent_positions` when initializing a space. If there is any model-related information about the ID, the user should just create a new field for their agent type.

---

**Importantly** such a change would eliminate the ID as a field of the Agent type. Since the agent's id is identical with its index in `model.agents`, there is no reason to doubly store the information.

**Comment by kavir1698** [comment]
A problem with such approach arises when some agents die during a model.
Then the agent ID will be different from it's index.

**Comment by Datseris** [comment]
Hm, good point that I have not though.

But seems to me that creating a custom Index type would probably solve our problems. I'll contemplate on it and let you know.

**Comment by Datseris** [comment]
Here is my solution: the agents are contained in a vector of: `Vector{AgentType, Missing}` (or `Vector{AgentType, Nothing}`. Recent Julia optimizations made it possible to combine types with singleton types like `Missing` or `Nothing`.

What I described above will still hold perfectly: each agent's ID is identical to its index in the `agents` vector. But when an Agent is "killed", first its "id" is removed from space, and then this id is replaced by `nothing / missing` in the agents vector.

Seems elegant, but we should test for performance regressions as well though. @kavir1698  Thoughts?

**Comment by Datseris** [comment]
An extra field `alive` , which only holds the alive indices would be a convenient tool for functions such as `random_activation`. (so that one doesn't have to skip missings all the time)

**Comment by Datseris** [comment]
@kavir1698 I have thought about this more, and I must say this is super-duper promising because:
```
struct AgentBasedModel{A<:AbstractAgent, S<:AbstractSpace, F, P}
    agents::Vector{Union{A, Missing}}
    space::S
    scheduler::F
    properties::P
end
const ABM = AgentBasedModel

function AgentBasedModel(
        agent::A, space::S,
        scheduler::F = as_added, properties::P = nothing
        ) where {A<:AbstractAgent, S<:AbstractSpace, F, P}
    agents = Union{A, Missing}[agent]
    return ABM{A, S, F, P}(agents, space, scheduler, properties)
end
```

As you can see, now the users do NOT create a model STRUCT. Instead, they initialize one struct, which, if they want it to have unique properties they can change, they do so by providing a dictionary as properties.

**Comment by kavir1698** [comment]
Thanks for thinking about this. I see one possible problem, though.
In long simulations, where the actual number of agents are not too huge, but there are many births and deaths, the `agents` vector could eventually become too large. Consequently, depending on the number of living agents, the framework may become unusable for simulations that take longer than `n` steps.

Or do you think that the `nothing`s/`missing`s do not take much memory?

**Comment by kavir1698** [comment]
> As you can see, now the users do NOT create a model STRUCT. Instead, they initialize one struct, which, if they want it to have unique properties they can change, they do so by providing a dictionary as properties.

But this is really nice, if the dictionary does not slow things down.

**Comment by Datseris** [comment]
> Or do you think that the nothings/missings do not take much memory?

Although I do believe that `missing` takes as much memory as a boolean (and thus the smallest possible), this is a valid concern that I am also trying to cope with.

A reasonable approach is the following: define a "renormalization function", which is called every time a model is stepped once. This function first checks the length of `agents`, and if it is "large" (some arbitrary number we define), then the function renormalizes: it first removes all `missing` entries from `agents` and then it re-scales (via appropriate subtraction) all entries in `space`.

> But this is really nice, if the dictionary does not slow things down.

No this is not a concern at all, plus these are the model-level parameters (which are supposed to be updated at most once per `step!`). For the agent at the moment I am keeping it as a struct.

**Comment by kavir1698** [comment]
> A reasonable approach is the following: define a "renormalization function", which is called every time a model is stepped once. This function first checks the length of agents, and if it is "large" (some arbitrary number we define), then the function renormalizes: it first removes all missing entries from agents and then it re-scales (via appropriate subtraction) all entries in space.

I like this solution. It seems to be practical.

> For the agent at the moment I am keeping it as a struct.

Ok, this should be good then.

**Comment by Datseris** [comment]
(while working on this I also did a minor tweak to scheduling, that is not only a bit more efficient, but also makes more sense programmatically in my eyes: the scheduler functions return an iterator that iterates over agents, instead of creating vectors)

**Comment by Datseris** [comment]
See `agents` branch

**Comment by kavir1698** [comment]
Perfect!

**Comment by kavir1698** [comment]
How about saving agents in a dictionary `id=> agent` instead of an array? Like that, we will not have to clean the array from dead agents and it will be fast.

**Comment by Datseris** [comment]
What happens when you kill an agent in this implementation?

**Comment by kavir1698** [comment]
`delete!(model.agents, id)` and the id is removed from from space as before.

**Comment by Datseris** [comment]
Seems like a reasonable plan. But we have to test and benchmark. Tell you what, after I do #53 the next steps should be to (1) update tests and (2) create basic benchmark files. 

it is important to not invest more development effort before being sure that our steps are actually beneficial.
