### ISSUE TITLE
Read data from file directly into agents/model

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#403]
We have decent data collecting utilities, but it'd be good to extend capacity to allow users to read in data from files to populate agents.

Unsure if this needs to be new methods or just an Ecosystem Integration example with CSV.jl and / or DataFrames.jl

**Comment by Datseris** [comment]
Seems like a straightforward ecosystem integration with CSV.jl to me. Get some list of some workers with age / sex / whatever property  and make them into Agents?

**Comment by Libbum** [comment]
I think that's all we'd need, yeah.

**Comment by AayushSabharwal** [comment]
What if this were made both ways? It could be useful to be able to save the state of a model (and its agents), and be able to load that in to simulate possibly branching scenarios. For example, in an epidemic simulation it could be useful to simulate the disease spread for a certain duration, then save the model state. After that, from the same point, the effects of different phenomena such as different vaccination rates, increased social distancing, simulating the use of masks be reducing the distance that the infection can spread over etc.

There could be several formats of storing this data

- Model properties are stored in a json file, and each agent type in its own csv
- All data in a json file, each agent type has its own key. The data within each agent type is best explained by the following example (each field is an array of values of the same length, the same index into each field gives the values for a given agent)
```json
... some model data
"Agent1": {
    "id": [1, 2, 3],
    "pos": [[1,2],[3,4],[5,6],[7,8]],
    .
    .
    .
}
```
- I'm not particularly familiar with it, but YAML might be a candidate here too

**Comment by Datseris** [comment]
how do you save the scheduler and the stepping functions?

**Comment by Datseris** [comment]
and what if a model-property is a function?

**Comment by AayushSabharwal** [comment]
> how do you save the scheduler and the stepping functions?

I'm not trying to save the entire model, and its functions. Just the data that specifies the state a simulation is in. The save won't allow passing a file around to be able to rerun the model, but rather load the state of a model at any given point. Additionally, in such a case couldn't the code just be passed around along with the saved data?

> and what if a model-property is a function?

I didn't think of this case, but we could just as easily specify that only JSON/CSV/something-serializable properties will be saved. I'm not sure why a model property would be a function anyway? How frequent would such situations be?

**Comment by Datseris** [comment]
> I'm not trying to save the entire model, and its functions. Just the data that specifies the state a simulation is in. 

Yeah, that's what I'm trying to point out. How would you "load" this "state"? And where would this loading be put into? Because, no matter how I try to look at it, the "scheduler" is part of the state of the model. Can you outline, in specificity, how the loading would be used?

**Comment by AayushSabharwal** [comment]
Suppose I `run!` the model for 300 steps. I have some 50 agents, and a few properties of the model. I call some `save_state` function, which writes the (serializable) model properties and the agent data to some file(s). 

Later, in another REPL session (or maybe multiple times in the same one) I can use `include` the `.jl` file with my `_step!` and other relevant functions. Then, I call some `load_state` function that acts like a replacement for an `initialize_model` function, which recreates all those 50 agents and the (serialized) model properties. The `load_state` function also takes in the scheduler, and creates the model using that. 

I think it could be thought of as another constructor for `ABM`, which also creates agents and loads properties from some file(s).

**Comment by Datseris** [comment]
Okay, this sounds like a good idea. However I see no reason to use JSON or other text-based formats, instead of using JLD2.jl and saving data directly to binary. It takes much less space and is much faster to read in as well.

**Comment by AayushSabharwal** [comment]
I'll look into JLD2.jl, never having used it before. Maybe there should be an option to save it text based, for human readability? With multiple files, it could be easier to differentiate them if they're human readable?

I agree though, that JLD2 is better for performance and space, and text-based should probably be implemented after.

**Comment by scepeda78** [comment]
What would be the potential variables to store in a file?, in my case the initialization of the model took near 2 hours, in a OSM space. I was able to see that model.space.s stores some info about the agents, but what would be other variables importants to review and store?

**Comment by Libbum** [comment]
If you're making a big map, I suspect that this slow load comes from OpenStreetMapX and how it parses the map data. In this scenario, everything in the model would be saved. `model.space.*`, `model.agents`, everything. In that sense you could have a 'pre-loaded' map agent that should significantly lower your initialization times by storing a model with no agents, but with the map you're interested in.

**Comment by scepeda78** [comment]
Yes indeed, the map is a whole country, and I need to add 4 millions agents on it. I have a cached version of the osm file, and it took 25 secs to load it, so loading the map is not the main issue. Is there a way to preload the agents on the osm file as a layer (crazy ideas to speed up the load), and then tell the software where to find the agents?. I didnt get well the idea of the preload map, since what it takes more time is to put the agents in the roads/intersections...

**Comment by Datseris** [comment]
> Yes indeed, the map is a whole country, and I need to add 4 millions agents on it.

??? This takes 2 hours? That is hard for me to believe I admit. Can you please provide us a benchmark of how much time it takes to add a single agent to the model? Or some kind of MWE example? It does not sound reasonable that this should take `0.0018` seconds, which is the estimate of 2hours/4million agents.

**Comment by Datseris** [comment]
https://github.com/JuliaDynamics/Agents.jl/blob/master/src/spaces/openstreetmap.jl#L317-L323 this is literally a push! operation. Perhaps in this time you also include _the time to plan a route for the agents_, which then of course i can understand it should take a massive amount of time if you are planning routes throughout an entire country ;)

**Comment by Libbum** [comment]
Would be nice in general to get a sense of the scale you're working with here @scepeda78, since I'm not aware of anyone using OSMSpace like you yet. So perhaps open another issue with some code and we can see if there's a better way to get you running faster.

**Comment by scepeda78** [comment]
By the way, my simulation has to do with PV generation, and I'm interested in knowing the neighbours within a radius.

`using Distributed
using Agents  
using DataFrames
using Parquet
using ExcelFiles
mapa=OpenStreetMapSpace("chile-latest.osm",use_cache=true) (this takes 18.1 sec to load with cache, first time is like 5 min, 437618 roadways, 721204 intersections)

mutable struct generador <: AbstractAgent
    id::Int
    pos::Tuple{Int,Int,Float64}
end
model = ABM(generador, mapa)

pos=osm_intersection((-33.433619,-70.664926),model)
human = generador(1,pos)
add_agent_pos!(human, model) (0.7 secs )

pos=osm_road((-33.433619,-70.664926),model) (0.9 secs)
human = generador(2,pos)
add_agent_pos!(human, model)

# this was my attemp to make it distribuited
#Cargar terrenos
archivo="terrenos_sin_BBCC_filtrado.parquet"
terrenos=DataFrame(read_parquet(archivo))
first(terrenos,5)
terrenos_seleccionados=terrenos[terrenos.region_ISO .== "AP",:]
#Crear agentes primer intento
using ProgressMeter
N = size(terrenos_seleccionados,1)
p = Progress(N);
update!(p,0)
jj = Threads.Atomic{Int}(0)
l = Threads.SpinLock()

Threads.@threads for id in 1:size(terrenos_seleccionados,1)
    pos=osm_random_road_position(model)
    human = generador(id,pos)
    add_agent_pos!(human, model)
    Threads.atomic_add!(jj, 1)
    Threads.lock(l)
    update!(p, jj[])
    Threads.unlock(l) 
end

(here the ETA time was 2 hours for 4 million households)



`

**Comment by Libbum** [comment]
If I had to guess, my money is on `osm_random_road_position`. I'd bet that `random_position` in it's place would not take anywhere near as long.

These methods have not been optimised yet unfortunately. The space is still pretty new. OpenStreetMapX stores only *intersection* data, so we've had to hack together solutions to get continuous values along roads.

**Comment by Datseris** [comment]
This has gotten a lot out of topic, @scepeda78 please continue this in a new issue.
