### ISSUE TITLE
@agent macro doesn't work with StaticArrays properties

### ISSUE THREAD

**Issue by flipgthb** [JuliaDynamics/Agents.jl#406]
Hi, 
I just updated Agents.jl to version 4.0.3 and tried to adapt my code for the new API, and just to try the new `@agent` macro I rewrote my agent struct using it, but for some reason it does not recognize the imported StaticArrays.jl package inside the begin block and does not define the struct.  The usual syntax for defining the agent works fine.

Here is a minimal working example:
```julia
using Agents, StaticArrays

try
    @agent TestAgent{N} GraphAgent begin
        v::MVector{N}
    end
catch e
    println("Got error: $e")
    mutable struct TestAgent{N}<:AbstractAgent
        id::Int
        pos::Int
        v::MVector{N}
    end
end

a = TestAgent(1,1,@MVector(ones(3)))
println("Hi from agent $(a.id) at $(a.pos) with vector $(a.v)")
```
which prints:
```
Got error: UndefVarError(:MVector)
Hi from agent 1 at 1 with vector [1.0, 1.0, 1.0]
```
Running  `Pkg.status(["Agents","StaticArrays"])` prints
```
[46ada45e] Agents v4.0.3
[90137ffa] StaticArrays v0.12.5
```
and I'm running Julia v1.5.3

**Comment by Libbum** [comment]
That's something we didn't test for, but should definitely be supported. Will take a look at it as soon as I can.

**Comment by Libbum** [comment]
```julia
julia> @macroexpand @agent TestAgent{N} GraphAgent begin
               v::MVector{N}
           end
:(mutable struct TestAgent{var"#11#N"} <: Agents.AbstractAgent
      #= /Agents.jl/src/core/agents.jl:64 =#
      id::Int64
      pos::Int64
      #= REPL[28]:2 =#
      v::Agents.MVector{var"#11#N"}
  end)
```
The macro is assuming `MVector` is a type in `Agents` rather than just in scope. Using `StaticArrays.MVector` isn't helpful:
```julia
    ...
    v::(Agents.StaticArrays).MVector{var"#12#N"}
  end)
```

Will need to dig into the macro docs a little more..

**Comment by Libbum** [comment]
I've started the process to tag #407 as v4.0.4, so you should be able to `] up` in an hour or so and have this working.

**Comment by flipgthb** [comment]
Nice! thanks for the great work with Agents.jl :)
