### ISSUE TITLE
JuliaCon 2021: Agents.jl Birds of Feather

### ISSUE THREAD

**Issue by fbanning** [JuliaDynamics/Agents.jl#411]
https://pretalx.com/juliacon2021/cfp

I think it would be nice to hold a "Birds of Feather" meetup of Agents.jl users or writing ABMs with Julia in general. What do you think about this? Worth a shot to get a better picture of the userbase?

> Birds of feather sessions are breakout sessions for organized discussions around specific topics. For example, package maintainers can use these times to organize a meeting with and recruit contributors, or community members can organize discussion groups for Julia teaching materials or diversity recruitment. These sessions will be allocated a one hour timeslot, and will not be recorded.

**Comment by Libbum** [comment]
Certainly something to consider. @Datseris, do you think we should coordinate a dyamics BoF like last year, or is there enough momentum in each of the domains JuliaDynamics covers to warrant more than one session?

**Comment by Datseris** [comment]
Yes guys, we will host a dynamics BoF like last year. To me it doesn't make sense to make something JuliaDynamics exclusive. @Libbum , will you submit a talk for Agents.jl this JuliaCon? You should!

**Comment by Libbum** [comment]
Yeah, I'm certainly considering it. May be changing jobs in the near future, so I need to make sure schedules align. If it's possible for me to attend it'll definitely happen.

**Comment by Datseris** [comment]
It will be online, probably with pre-recorded talks like last time.
