### ISSUE TITLE
Examples not running correctly

### ISSUE THREAD

**Issue by scottturner21** [JuliaDynamics/Agents.jl#413]
**Describe the bug**
Note I am very new to Julia so am likely doing something stupid (so apologies!!). When I try to run the examples given in the documentation, I have come across issues with functions or macros not actually being imported.

**Minimal Working Example**
```
using Agents
ids_in_position
```
UndefVarError: ids_in_position not defined

```
using Agents
@agent
```
LoadError: UndefVarError: @agent not defined

I also got an issue with the keywords in the wealth example. When reaching the line `data, _ = run!(model, agent_step!, N; adata)` I get the error: LoadError: syntax: invalid keyword argument syntax "adata"

This seems to be fixed by explicitly naming the keyword: `data, _ = run!(model, agent_step!, N; adata=adata)` in the last line.

**Agents.jl version**
Agents v3.1.0

**Comment by Libbum** [comment]
Hi! Looks like you're using an older version of Agents, but reading the current documentation. 
In your REPL, try `] up` to update to the latest Agents (4.0.4), and give it another shot. 

Let me know if you have more issues.

**Comment by Libbum** [comment]
`data, _ = run!(model, agent_step!, N; adata)`

What version of Julia are you using? I think you need at least v1.5 to use that syntax. If you're on something older, you can use
`data, _ = run!(model, agent_step!, N; adata=adata)`

**Comment by scottturner21** [comment]
Thank you, that was the issue. I had an old version of Julia which installed an older version of Agents because of compatibility requirements.
