### ISSUE TITLE
Seed consideration in parallel_replicates

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#415]
At the moment, `parallel_replicates` uses a [deepcopy of the model](https://github.com/JuliaDynamics/Agents.jl/blob/0c660872f983b5a981671bc8f1b5c901c8799a93/src/simulations/collect.jl#L454). If users are depending on seeds inside their model to produce replicable random results, they will want replicates to modify such a seed. 

We need to allow users to provide a function which appropriately modifies each replicate to achieve this.

**Comment by Datseris** [comment]
True, but the seeding is a bigger problem, because functions that choose e.g. random positions are not seeded properly by the model. Therefore, I think the issue of using a global RNG from the ABM _everywhere_ precedes solving the current issue.

**Comment by Libbum** [comment]
Ah, yes. That may be more important. I'll think on that.

**Comment by Datseris** [comment]
We could define `get_rng(model::ABM) = get(model.properties, :rng, Random.GLOBAL_RNG)` and use the output of `get_rng` in every `random` call. What I'm a bit uncertain is whether this is type stable.

**Comment by Libbum** [comment]
I've been thinking about Bogumił's [blog about seeds](https://bkamins.github.io/julialang/2020/11/20/rand.html) too, I think something like what you've suggested above is a good place to start.

Snowed under at the moment with other projects, but it'll be good to chat about this in a few weeks.

**Comment by Datseris** [comment]
Very interesting. I knew almost nothing the post said. It only makes it clear that the seed business is more important than we thought.

**Comment by Datseris** [comment]
I think we should simply allow an extra keyword `seeds = [rand(Int) for i in 1:replicates]` by default, which is used to seed each replicate. That seems to be the simplest scenario. Not really sure what to do with the `RandomDevice()` version though.

**Comment by Libbum** [comment]
Something like that would be a solution, yeah.

Concerning `RandomDevice()`: I've got a hardware entropy RNG thingy plugged into this machine. No point not using it!

**Comment by Datseris** [comment]
Have you checked that `deepcopy`-ing a model with `RandomDevice()` instance produces same numbers, even if run at different points in time?

**Comment by Libbum** [comment]
At least with a modified parallel replicates implementation its true. Hence #436 

https://github.com/Libbum/LimnoSES.jl/blob/656a5c13d274a23ab6e59773e25f091d5173346b/src/replicates.jl#L5

This is with pseudo-random now, but it should work if we were able to re-initialise the RandomDevice. However, I get the same 10 runs.
