### ISSUE TITLE
Document `nearby_ids` for OpenStreetMapSpace

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#424]
@Libbum what precisely does `nearby_ids` do for open street map space? There are several possibilities:

1. Finds nearby agents based on intersections, identically to GraphSpace.
2. Finds nearby agents/positions based on the distance in meters of road need to be travelled to meet the point
3. Finds nearby agents based on the euclidean distance in real space

By looking at the source I think it is (2), but we should add docs for it.

**Comment by Datseris** [comment]
Same for `nearby_positions`

**Comment by Libbum** [comment]
Yeah. These totally slipped through the cracks. 

You're right: `nearby_positions` is the same as graphspace, so its essentially `nearby_intersections`.
`nearby_ids` is (2).

**Comment by Datseris** [comment]
@Libbum does `nearby_positions` takes the argument `r` in meters, or in neighborhing graph nodes like `GraphSpace`?

**Comment by Datseris** [comment]
@Libbum I see that `nearby_positions` for OSM does not allow for an `r` argument:
```julia

function nearby_positions(
    position::Int,
    model::ABM{<:OpenStreetMapSpace};
    neighbor_type::Symbol = :default,
)
    @assert neighbor_type ∈ (:default, :all, :in, :out)
    neighborfn = if neighbor_type == :default
        LightGraphs.neighbors
    elseif neighbor_type == :in
        LightGraphs.inneighbors
    elseif neighbor_type == :out
        LightGraphs.outneighbors
    else
        LightGraphs.all_neighbors
    end
    neighborfn(model.space.m.g, position)
end
```

**Comment by Datseris** [comment]
(that is okay, but should be documented)

**Comment by Libbum** [comment]
Sorry, yes - these changes look correct.
