### ISSUE TITLE
Moving OSM Agents by time, rather than by distance

### ISSUE THREAD

**Issue by SteffenMuehle** [JuliaDynamics/Agents.jl#426]
## Feature request:
I would like to move agents on an OSM map by *time* rather than by *distance*, taking into account local road speeds.
For intuition, I've attached a .gif I've made where it's clear that agents have different speeds on different roads.
![bus_time_test](https://user-images.githubusercontent.com/28302575/108683656-2fee8300-74f2-11eb-8967-b6dcd6485d82.gif)

## Solution wanted
The solution (=function) I'd like would look like
> time=5.0
> move_agents_by_time(model,time)

or as a kwarg
> move_agents(model;time=5.0)

This function should take into account the local road's (=graph edge) speed limit.
This is already given in the model's map:
> model.space.m.class
with speed limits in km/h
> OpenStreetMapX.SPEED_ROADS_URBAN

## My custom solution
I've written two functions, which together solve this issue. Both are attached. Two further little helper functions are also attached:
[get_travel_times.txt](https://github.com/JuliaDynamics/Agents.jl/files/6020559/get_travel_times.txt)
[move_agent_by_time!.txt](https://github.com/JuliaDynamics/Agents.jl/files/6020560/move_agent_by_time.txt)
[two_little_helper_functions.txt](https://github.com/JuliaDynamics/Agents.jl/files/6020561/two_little_helper_functions.txt)

#### Explanation
1) "get_travel_times": Obtains the map's edge's weights as travel times.
This function is exactly taken from the OpenStreetMapX.jl package (see here https://github.com/pszufe/OpenStreetMapX.jl/blob/b74a8d432efd61683a9eaea3282381feceaa8b44/src/routing.jl#L63), but I've altered it such that the output is a sparse matrix in the same form as the map's original weights (travel distances) that are given in model.space.m.w.

2) "move_agents_by_time"
- Converts agent's position' third element (=distance between two nodes in meters) into a time (in seconds)
- exchanges model's graph weights with travel times rather than distances
- performs "time step" by using given Agents.jl functions for distance-steps.
- turns agent.pos[3] into distance again
- retrieves distance-weights

#### Suggestion
My solution works but needs to pass the travel_times as an explicit argument. It would be more convenient if this sparse matrix would just be a field of the model's map model.space.m. This map is a struct of data type "MapData" as given by the OpenStreetMapX.jl package. So far, it has a single weight matrix model.space.m.w for distances between nodes.

## Minimal example
Given an OSM-model called "model", run the functions I attached, then
> time=3.14159
> sparse_times=get_travel_times(model.space.m);
> move_agent_by_time!(model,time,sparse_times)

P.S.: This is my first issue opened on GitHub, let me know if I need to provide something else or so. I hope attaching the files worked properly :)

**Comment by Libbum** [comment]
Good idea Steffen, and thanks for all the work on this already!

Are you interested in writing a PR for this? We can help you with the process, but ultimately it will show that you're the one that did the work. 

If not, I think it's a decent method to include so I can do so in the future. Will be a few weeks before I can look at this properly though.

**Comment by SteffenMuehle** [comment]
Hi Tim,
Sure, I can do that, but I'd need some assistance concerning how exactly to do it though.
Cheers!

**Comment by Libbum** [comment]
Certainly.

First you want to fork this repository (top right of this page). It'll create your own version of it.  Clone that copy to your local machine.
Make a new branch, something like `git checkout -b move_by_time`, and add your changes in there. Push those changes to github. Once you've done that, a banner will appear either on the Agents.jl page or your personal copy to make a Pull Request. Click that, write some comments and that will open the PR.

Don't worry if it doesn't work or you still have open questions. We can discuss them in the PR where we can change code and discuss the best implementation together.

**Comment by SteffenMuehle** [comment]
Right, thanks! I've done so, for both issues.

**Comment by Datseris** [comment]
Closed on `master` via the usage of the new space LightOSM.jl
