### ISSUE TITLE
OSM move_agents not working properly for long distances

### ISSUE THREAD

**Issue by SteffenMuehle** [JuliaDynamics/Agents.jl#427]
# Bug
Given an OSM agent "a" with some position a.pos, destination a.destination and route a.route can be moved with
> move_agent!(a, model, distance)

I believe this function (and in particular subfunction "travel!") silently assume that the distance steps "distance" are small compared to the OSM map's typical edge lengths:
A sequence of consecutive steps leads the agent to its destination.
**One very long distance step does not lead the agent to its destination**.
Instead, the agent seems to rest at its route's last node instead.

# Reproduce bug:
Take the Zombie outbreak example, then do
> model = initialise()

check agent's position, destination and route
> model[1]

perform large number of small steps (**good**)
> for _ in 1:10^4
move_agents!(model[1],model,10)
end

and compare the outcome with that of one large step (**bad**)
> move_agent(model[1],model,10^5)

In the latter case, you should see that the agents position and destination do not coincide as they should.

# Proposed solution
I believe the function "travel!" ([line 446](https://github.com/JuliaDynamics/Agents.jl/blob/8e51d6926b65eb31d5fb49ce8cd6cdc0cfc09652/src/spaces/openstreetmap.jl#L446)) does not behave correctly in the case of a huge step length. Line 446 should instead have the same logic as the function "park!" ([line 453](https://github.com/JuliaDynamics/Agents.jl/blob/8e51d6926b65eb31d5fb49ce8cd6cdc0cfc09652/src/spaces/openstreetmap.jl#L453)), but with the *virtual agent* (inside the travel! function) having already moved so to say.
I've fixed this and it now seems to work properly for me:
[my_travel.txt](https://github.com/JuliaDynamics/Agents.jl/files/6021316/my_travel.txt)

I've commented the respective code section I've changed in the attached file.

### Explanation
I think the logical error the function "travel!" makes is that it did not expect the agent's route to become empty while running with plenty of distance left to travel. Fortunately, this special case is handled in the function "park!" which I've inserted manually.

# Version
Status `~/.julia/environments/v1.5/Project.toml`
  [46ada45e] Agents v4.0.1

**Comment by Libbum** [comment]
Yep, good catch. Same deal on this one&mdash;feel free to open a PR with your solution in it.
