### ISSUE TITLE
grid definition isn't working

### ISSUE THREAD

**Issue by sanalphatau** [JuliaDynamics/Agents.jl#43]
Hello I'm trying to ruhn the schelling model example from the docs. 

I keep running into the error "function Grid does not accept keyword arguments"

this seems to be caused by the line:
`mygrid = MyGrid(griddims, grid(griddims, false, true), agent_positions)`
space.jl seems to be miscalling grid().

Attached the file all the code is copied from the docs. [test.txt](https://github.com/JuliaDynamics/Agents.jl/files/3784860/test.txt)

**Comment by kavir1698** [comment]
Same as #28. Just use the latest update from master `]add Agents#master`.

**Comment by sanalphatau** [comment]
yes that works, thanks! Is there a reason master isn't the one that is installed by default

**Comment by kavir1698** [comment]
A new version with major changes will be released soon.
