### ISSUE TITLE
Citation Link Not Visible In Dark Mode

### ISSUE THREAD

**Issue by rmcsqrd** [JuliaDynamics/Agents.jl#432]
**Describe the bug**
In the [documentation landing page citation section](https://juliadynamics.github.io/Agents.jl/stable/#Citation) the citation is not readable in dark mode (it is white text with a white background, see image). Filing this as an FYI - I have not used Documenter.jl before so I am unclear on how to fix this. 

<img width="753" alt="Screen Shot 2021-02-22 at 11 48 24 AM" src="https://user-images.githubusercontent.com/48159564/108755159-2241f900-7504-11eb-82d7-646fb5683308.png">

**Minimal Working Example**
N/A

**Agents.jl version**
v4.04

**Comment by Datseris** [comment]
Fixed in #425 , thank you very much!
