### ISSUE TITLE
seed! is ineffective for RandomDevice

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#436]
I *thought* seed! was working with the current implementation, but upon further testing, it's not. Reading into the docs further: *Two such objects will always generate different streams of random numbers.*

So to truly `seed!` a random device, we need to pass a new instance to `model.rng`. We'll need to go back to the Ref implementation I think.

**Comment by Datseris** [comment]
What is the purpose of "seeding" something without providing an actual reproducible seed?

**Comment by Datseris** [comment]
> Two such objects will always generate different streams of random numbers

Okay, so what? It's like shuffling a well-shuffled deck.

**Comment by Libbum** [comment]
Well, I'm happy to not call it `seed!` in this instance, but providing an ability to have random replicates (#415) is what I'm talking about here.

**Comment by Datseris** [comment]
I see. I am personally not happy with putting Ref everywhere. It seems hacky and fishy. If this was a "good way to go", then mutable types wouldn't exist. Julia would tell you "just make everything have Ref fields, its better this way, and you only need to type an extra `[]`".

But I guess here a `Ref` is the only way to go forwards, or simply benchmarking whether making `ABM` mutable has any impact.

**Comment by Libbum** [comment]
Yep. Will do some mutability checks I think.

Out of time on this problem now anyway. I'm going to switch back to MersenneTwister for the moment.

**Comment by Datseris** [comment]
Just to be clear, at the moment parallel replicates do not work right? as they deep copy the model, and `rng` is part of the model...?
