### ISSUE TITLE
Creating a Makie-based version of open street map plotting

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#437]
This issue is probably better to open in OpenStreetMapXPlot.jl, but we care about it as well.

In Agents.jl we are currently moving largely towards plotting only with Makie.jl. It is too powerful to not do it!

The problem with the current open street map space is that it is extremely slow to plot. If we manage the Makie port, we will have huge benefits regarding plotting time.

Porting open street map to Makie is doable when we find some spare time. From here https://github.com/pszufe/OpenStreetMapXPlot.jl/blob/master/src/plot.jl  it looks daunting and large, but I think it is because of design. Much code can be made simpler by removing repetition of functions and propagating arguments. We could have a Makie version in 200 lines or even less. In principle we only plot `lines!` and `poly!`. For example, our Zombie outbreak example only plots `lines!` with different color. 

The core plotting is this loop:
```julia
# Draw all buildings
    if !isa(buildings,Nothing)
        OpenStreetMapXPlot.draw_buildings!(p,nodes, buildings, buildingStyle, km)
    end
    # Draw all roadways
    if !isa(roadways,Nothing)
        OpenStreetMapXPlot.draw_roadways!(p,nodes, roadways, roadwayStyle, km)
    end
    # Draw all walkways
    if !isa(walkways,Nothing)
        OpenStreetMapXPlot.draw_walkways!(p,nodes, walkways, walkwayStyle, km)
    end
    # Draw all cycleways
    if !isa(cycleways,Nothing)
        OpenStreetMapXPlot.draw_cycleways!(p,nodes, cycleways, cyclewayStyle, km)
    end
    #Draw all features
    if !isa(features,Nothing)
        OpenStreetMapXPlot.draw_features!(p,nodes, features, featureStyle, km)
    end
```
and for example all functions that plot roads should be a single function but with different style: color, width, and transparency. This will make the source code simpler.

@pszufe I am tagging you as well here, you would benefit greatly from having faster plotting of maps.

**Comment by pszufe** [comment]
Yes - this would be quite easy to program.

Actually it is worth knowing that `gr()` is very fast once you correctly set the environment variable:
```
ENV["GKSwstype"]="nul"
```
But most people never set it and than observe poor performance.

For discussion see:
https://stackoverflow.com/questions/64371677/plot-window-showing-up-when-run-from-terminal-in-plots-jl

**Comment by Datseris** [comment]
It is extremely weird for me that such a massively important option, supposedly leading to 150x performance gain, should be set explicitly from the user every time instead of being always on by default. As far as I can tell, it is an indication of bad design decisions and yet another reason to turn away from Plots.jl and into Makie.jl.

**Comment by Datseris** [comment]
@AayushSabharwal can you please share with me the scripts you've used to plot the new OSM space with @fbanning 's code with Makie.jl plotting? I'd like to resolve this before the 5.0 release.

**Comment by AayushSabharwal** [comment]
```julia
using OSMMakie
using CairoMakie
ac(agent) = agent.infected ? :green : :black
as(agent) = agent.infected ? 6 : 5

model = initialise()

fig, ax, plot = osmplot(model.space.map)
ids = model.scheduler(model)
colors = Node([ac(model[i]) for i in ids])
sizes = Node([as(model[i]) for i in ids])
marker = :circle
pos = Node(Point2f[OSM.latlon(model[i].pos, model) for i in ids])
scatter!(pos; color = colors, size = sizes, marker)

record(fig, "outbreak.mp4", 1:200; framerate = 15) do i
    Agents.step!(model, agent_step!, 1)
    ids = model.scheduler(model)
    colors[] = [ac(model[i]) for i in ids]
    sizes[] = [as(model[i]) for i in ids]
    pos[] = Point2f[OSM.latlon(model[i].pos, model) for i in ids]
end
```

This should work (for the zombies example)

**Comment by Datseris** [comment]
@fbanning or @AayushSabharwal how can I use the OSMMakie package to plot _in-place_ in an axis? I cannot afford to iitialize a new axis with `fig, ax, plot = osmplot(...)` because then I simply can't integrate this into InteractiveDynamics.jl.

**Comment by fbanning** [comment]
> @fbanning or @AayushSabharwal how can I use the OSMMakie package to plot _in-place_ in an axis? I cannot afford to iitialize a new axis with `fig, ax, plot = osmplot(...)` because then I simply can't integrate this into InteractiveDynamics.jl.

Wouldn't it work to just use `osmplot!`?

**Comment by Datseris** [comment]
I'm proud to say that we now have native support for OSM spaces in all the InteractiveDynamics.jl+Agents.jl applications. Thanks to @fbanning for the amazing work on the plotting backend. Result:

![zombies](https://user-images.githubusercontent.com/19669089/149425946-273fdf23-0d63-4bc6-885f-f06c77d45c4e.gif)

@fbanning you need to register this package for this to go in any tagged version.

**Comment by Datseris** [comment]
(Oh yeah, also this is wicked fast. IF I put the sleep slider to 0 this goes from full black to full green instantly)
