### ISSUE TITLE
Remove PyPlot as a dependency in documentation

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#439]
Builds fail if it's not there, but we don't use it and it takes quite some time to build. Track down why it's needed in the dependency tree and remove it if possible.

**Comment by Datseris** [comment]
If the open street map plot requires necessarily the `pyplot()` backend, then it is necessary to build PyPlot.jl.

**Comment by Libbum** [comment]
But we don't have OpenStreetMapXPlot.jl in the dependencies, so its not that.

**Comment by Datseris** [comment]
Then how do we make the Zombie animation...?

**Comment by Libbum** [comment]
https://github.com/JuliaDynamics/JuliaDynamics/blob/master/videos/agents/zombies.mp4

**Comment by Datseris** [comment]
loooooooooooooooooooooooooool
