### ISSUE TITLE
How to obtain meters travelled until destination?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#449]
I'm looking at the Zombie example, and I've noticed that some agents (those that reach their destination while on current step) travel two times. What if I want to set up a simulation where all agents travel exactly 25 meters even if a new route has to be planned? 

Can we modify `move_agent!` so that its return value is the meters travelled? So `move_agent!(a, model, 25)` will always return `25` if the agent hasn't reached the destination, but otherwise will return the amount travelled to reach the destination.

is this costly to do, or already available information?

**Comment by Libbum** [comment]
> travel two times

Not sure what you mean by that?

> Can we modify `move_agent!` ...

Yeah, that should be trivial. We need to track that to move the agent anyhow.

**Comment by Datseris** [comment]
```julia
## Each agent will progress 25 meters along their route
    move_agent!(agent, model, 25)

    if osm_is_stationary(agent) && rand(model.rng) < 0.1
        ## When stationary, give the agent a 10% chance of going somewhere else
        osm_random_route!(agent, model)
        ## Start on new route
        move_agent!(agent, model, 25)
    end
```
will move more than 25 meters if reached destination during this step

**Comment by Libbum** [comment]
Oh, sure. So you want the possibility of doing something like

```julia
    total_moved = move_agent!(agent, model, 25)

    if osm_is_stationary(agent) && rand(model.rng) < 0.1
        ## When stationary, give the agent a 10% chance of going somewhere else
        osm_random_route!(agent, model)
        ## Start on new route
        move_agent!(agent, model, 25-total_moved)
    end
```
such that agents only ever move 25 meters per step. Sure.

**Comment by Datseris** [comment]
Exactly.

**Comment by Libbum** [comment]
We will need to fold this requirement into #459

**Comment by AayushSabharwal** [comment]
This should be fairly easy to add to `move_along_route!`.
