### ISSUE TITLE
Failing to assign value to field of properties struct via `model.key`

### ISSUE THREAD

**Issue by fbanning** [JuliaDynamics/Agents.jl#455]
In #453 @Libbum wrote:

> If you can find that edge case that failed with model.key, that's something separate to investigate—open a new issue for that if it crops up.

I've found it (a lot faster than expected) although it was not about accessing struct fields via `model.key` but instead about assigning new values to the field.
The issue can be reproduced with the same MWE that I provided in the earlier issue:

```julia
using Agents
mutable struct MyAgent <: AbstractAgent
    id::Int
end
mutable struct Properties
    par1::Int
    par2::Float64
    par3::String
end
properties = Properties(1,1.0,"Test")
model = ABM(MyAgent; properties = properties)
```

```julia
julia> model.par1
1

julia> model.par1 = 2
ERROR: MethodError: no method matching haskey(::Properties, ::Symbol)
Closest candidates are:
  haskey(::REPL.Terminals.TTYTerminal, ::Any) at C:\buildbot\worker\package_win64\build\usr\share\juli
a\stdlib\v1.5\REPL\src\Terminals.jl:159
  haskey(::DataFrames.Index, ::Symbol) at C:\Users\Frederik Banning\.julia\packages\DataFrames\oQ5c7\s
rc\other\index.jl:111
  haskey(::LibGit2.CachedCredentials, ::Any) at C:\buildbot\worker\package_win64\build\usr\share\julia
\stdlib\v1.5\LibGit2\src\types.jl:1277
  ...
Stacktrace:
 [1] setproperty!(::AgentBasedModel{Nothing,MyAgent,typeof(fastest),Properties,Random.MersenneTwister}
, ::Symbol, ::Int64) at C:\Users\Frederik Banning\.julia\packages\Agents\pILxZ\src\core\model.jl:164
 [2] top-level scope at REPL[7]:1

julia> model.properties.par1 = 2
2

julia> model.par1
2
```

As you can see accessing a field via `model.par1` works and the value can be used in calculations everywhere.
But assigning a value to `model.par1` does not work although using `model.properties.par1` does.

**Comment by Datseris** [comment]
super easy fix by extending https://github.com/JuliaDynamics/Agents.jl/blob/master/src/core/model.jl#L162-L169 to also work with structs. now it assumes dictionary
