### ISSUE TITLE
Iterating over new agents in agent_step! and model_step!

### ISSUE THREAD

**Issue by drbergman** [JuliaDynamics/Agents.jl#457]
**Describe the bug**
My agents are tumor cells. The main thing they do is proliferate and create new tumor cells. I want to do this in `agent_step!`, but it sometimes iterates over new cells created in these functions during one update step. If I do cell updates in `model_step!` using for `for a in allagents(model)`, the same thing happens. How can I insist on the iterator only iterating over agents present at the start of the step?

**Minimal Working Example**
```
using Agents
mutable struct TumorCell <: AbstractAgent
    id::Int
    pos::NTuple{1,Int}
end

function agent_step!(a,model)
    add_agent!(a.pos,model) % create new cell from every existing cell; should double cell number
end

function model_step!(model)
     for a in allagents(model)
          add_agent!(a.pos,model) % create new cell from every existing cell; should double cell number
     end
end

space = GridSpace((1,))
model1 = AgentBasedModel(TumorCell,space) % to test agent_step!
model2 = AgentBasedModel(TumorCell,space) % to test model_step!

add_agent!((1,),model1)
add_agent!((1,),model2)

step!(model1,agent_step!,dummystep,2) 
step!(model2,dummystep,model_step!,2)
% each step should have each cell create a new cell, doubling the size; 2 steps would mean 2 cells at the end; however, 5 cells are created at the end
```
**Agents.jl version**

Agents v4.1.5

**Comment by Datseris** [comment]
Hi,

This is described in a note on iteration: https://juliadynamics.github.io/Agents.jl/stable/api/#A-note-on-iteration  

Iteration in Agents.jl is dynamic for performance reasons. You have to choices:
1. If you don't go to the `model_step!` pass as scheduler `scheduler = model -> collect(allagents(model))`.
2. If you do use `model_step!` use directly `collect(allagents(model))` in your loop instead of `allagents(model)`.

**Comment by Datseris** [comment]
p.s.: @drbergman your model sounds interesting and quite far away from what we have in the examples library. would you be interested to contribute an example to the documentation?

**Comment by drbergman** [comment]
Thank you so much! I'll have a look at your link. I had figured there was a way to do this and I'm just too new to Julia to find it.

I'm currently just dabbling in Julia (it seems like a possible direction ABMs in cancer might want to head). If I end up with something more complete, I'll let you know!

**Comment by Datseris** [comment]
Also, you can use `nothing` instead of `GridSpace((1,))` for "no space", and then the field `pos` is not necessary.

**Comment by drbergman** [comment]
Interesting! That could be useful.
