### ISSUE TITLE
Move along path for OSMSpace

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#459]
Path-finding #447 introduces `move_along_path!`, we should make this explicit in `OSMSpace` too.

**Comment by Datseris** [comment]
As a note: this will _replace_ the functionality of the existing `move_agent!` function. A deprecation will be thrown inside the current `move_agent!`.

**Comment by Datseris** [comment]
We will do this change in https://github.com/JuliaDynamics/Agents.jl/pull/429

**Comment by AayushSabharwal** [comment]
Can we close this now that `move_along_route!` is the standard API?
