### ISSUE TITLE
map_agent_groups documentation is unclear

### ISSUE THREAD

**Issue by sents** [JuliaDynamics/Agents.jl#462]
The documentation for `map_agent_groups` states: "Applies function `f` to all grouped agents of an [`iter_agent_groups`](@ref) iterator."

However `map_agent_groups` returns a generator object that still has to be consumed (e.g. by collect) to initiate the application of `f` to the agent groups. It would be helpful if the documentation would state that extra steps are needed to actually execute the function. 

**Agents.jl version**
4.1.5

**Comment by Datseris** [comment]
The result of `map_agent_groups` can still be iterated over normally, no reason to collect it. See https://juliadynamics.github.io/Agents.jl/stable/api/#A-note-on-iteration
