### ISSUE TITLE
Swap CI

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#468]
1.6 should now be the main testbed. Don't think we need to be looking at 1.7 just yet. Since we still support 1.5, we should probably run tests there still however.

**Comment by Datseris** [comment]
At the moment we test twice on 1.6: https://github.com/JuliaDynamics/Agents.jl/blob/master/.github/workflows/ci.yml#L17-L19

I don't think continuing to test on 1.5 is necessary, nor is necessary to "actively support 1.5" since 1.6 is LTS.
