### ISSUE TITLE
Parallel computing

### ISSUE THREAD

**Issue by kavir1698** [JuliaDynamics/Agents.jl#47]
For parallel simulations to work, we need to modify the code so that one can define the number of workers. We also have to make sure `Agents` is defined on all the workers.

**Comment by Datseris** [comment]
Just as a heads up: in Julia 1.3 (soon to be out) there are a big number of updates and improvements regarding parallel computing.

**Comment by kavir1698** [comment]
Is it a good idea to make the package work only with Julia version >= 1.3?

**Comment by Datseris** [comment]
Oh yes, absolutely. I mean, 1.3 is a non-breaking upgrade from 1.0. It is "strictly superior" in a sense, so I cannot find arguments of why we shouldn't be able to do this.

**Comment by kavir1698** [comment]
>  we need to modify the code so that one can define the number of workers. We also have to make sure Agents is defined on all the workers.

I am thinking maybe we shouldn't do this, and leave it to the user. So, to run simulations in parallel, they would have to start julia with `-p n` and import `Agents.jl` with `@everywhere using Agents`.

If we put the `@everywhere` tag in the package, it slows down load times.

**Comment by Datseris** [comment]
Yes this is much more healthy.

**Comment by kavir1698** [comment]
I have updated the tutorial to reflect this idea.
