### ISSUE TITLE
Citation cleanup

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#477]
We have Citation.bib and the /paper/ directory. I'm wondering if we should update / clear this stuff for the release of our new paper.

@kavir1698, I guess you'd be the one to make the decision on what to do with that, since it's your v1.0 single author paper we're referring to.

**Comment by Datseris** [comment]
> I'm wondering if we should update / clear this stuff for the release of our new paper.

My vote is no clearing, because version 1.0 is properly archived both here and in Zenodo (because this is mandatory from the JOSS journal). They currently will not be useful and might even misslead newcomer contributors or people checking out the repo without reading the docs.

**Comment by kavir1698** [comment]
The paper is accessible in JOSS' website anyway. I do not mind clearing it.
