### ISSUE TITLE
ERROR: LoadError: UndefVarError: OSM not defined

### ISSUE THREAD

**Issue by scepeda78** [JuliaDynamics/Agents.jl#487]
**Describe the bug**
ERROR: LoadError: UndefVarError: OSM not defined

**Minimal Working Example**
Zombie example is not workink

If the code is **runnable**, it will help us identify the problem faster.

**Agents.jl version**

Please provide the version you use (you can do `Pkg.status("Agents")`.
4.1.5

**Comment by Libbum** [comment]
OSM and other submodules were released in v4.2 yesterday. You can either use the example in the documentation of 4.1 https://juliadynamics.github.io/Agents.jl/v4.1/examples/zombies/ or `] up` to get the latest version of agents.
