### ISSUE TITLE
`init_model_dataframe` errors when using a properties struct

### ISSUE THREAD

**Issue by fbanning** [JuliaDynamics/Agents.jl#494]
When creating an ABM with a properties struct, we are currently facing a problem during the calll to [`init_model_dataframe`](https://github.com/JuliaDynamics/Agents.jl/blob/c9a7fa13493c0ba24aacd0a6a6de4ba19394d181/src/simulations/collect.jl#L397). We want to collect some model data (through the regular `mdata = [:fieldname]` approach) and get the following error (which I've generalised a bit to make it more easily understandable):

```julia
julia> model.properties[:scenario]
ERROR: MethodError: no method matching getindex(::ModelProperties, ::Symbol)
Stacktrace:
 [1] top-level scope
   @ REPL[7]:1
```

I'm relatively sure that [this line](https://github.com/JuliaDynamics/Agents.jl/blob/c9a7fa13493c0ba24aacd0a6a6de4ba19394d181/src/simulations/collect.jl#L407) is what causes the problem because we can't access a struct's fields like this (i.e. via the fieldnames as symbols). This approach only works for Dicts and Tuples.

Is my assumption correct that this is what is causing the problem?  
If so, maybe it's already enough to add a quick check for the type of `model.properties` and adapt accordingly.

**Comment by Libbum** [comment]
Without looking too deeply, I'd say your assumption is correct. We wrote that method on the assumption that we're using a dict and haven't done thorough testing with the recent improvements when using structs. 

Yep, a type check would be best!
