### ISSUE TITLE
Update benchmarks for 2.0

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#50]
A lot of changes happened to the source code on the way to 2.0. This could have impact on performance, possibly even regressions. By re-doing the benchmarks we will be able to identify such regressions.

**Comment by kavir1698** [comment]
I have created benchmarks of critical operations.

**Comment by Datseris** [comment]
Where are they? 

(also, why didn't you close this?)

**Comment by kavir1698** [comment]
In `test/benchmark`.
They should be updated after changing the agent storage to a dictionary. So I didn't close it.

**Comment by Datseris** [comment]
Maybe we should record in a plan text file the result of doing the benchmarks before changing anything?
