### ISSUE TITLE
Same seed, different result (with different way to collect data)

### ISSUE THREAD

**Issue by ndgnuh** [JuliaDynamics/Agents.jl#500]
**Describe the bug**
The model result is deterministic, but in two different way. Different types of `adata` causes the results to be different.

**Minimal Working Example**
(This is a pluto notebook file, sorry for the extension, Github doesn't allow drag dropping `.jl` file). This is the example predator-prey model, I modified it so it uses seed and scheduler.

[agentsjl-collect-bug.txt](https://github.com/JuliaDynamics/Agents.jl/files/6560465/agentsjl-collect-bug.txt)

**Agents.jl version**
```julia
pkg> st Agents
     Project .........
      Status ............
  [46ada45e] Agents v4.2.4
```
**Additional infomation**

I ***think*** this happened because `init_agent_dataframe` uses two other functions, one of which uses `random_agent`, which uses `shuffle!(model.rng)` while the other doesn't. 

https://github.com/JuliaDynamics/Agents.jl/blob/c377d812146de06e30a13471b4b04f9076b8988e/src/simulations/collect.jl#L201-L206

https://github.com/JuliaDynamics/Agents.jl/blob/c377d812146de06e30a13471b4b04f9076b8988e/src/simulations/collect.jl#L211-L213

https://github.com/JuliaDynamics/Agents.jl/blob/c377d812146de06e30a13471b4b04f9076b8988e/src/core/model.jl#L190-L212

**Comment by Datseris** [comment]
> The model result is deterministic, but in two different way. Different types of adata causes the results to be different.

I don't understand the problem, can you please elaborate in more detail? Linking a 200-loc text file is not as transparent as you'd might think :D

**Comment by Datseris** [comment]
> one of which uses random_agent, which uses shuffle!(model.rng)

That's another thing I don't understand... `random_agent` does not do `shuffle!(model.rng)`...?

**Comment by ndgnuh** [comment]
Sorry for not being a mess :P Basically, I have two function which runs the exact same model, with the exact same seed, with different `adata`

```julia
function collect_agg(sched)
	wolf(a) = a.type == :wolf
	sheep(a) = a.type == :sheep
	df = runsim([(wolf, count), (sheep, count)]; scheduler=sched)
	rename(df, [:step, :nwolf, :nsheep])
end

function collect_normal(sched)
	df = runsim([:type]; scheduler=sched)
	df = combine(
		groupby(df, :step),
		:type => (x -> count(x .== :wolf)) => :nwolf,
		:type => (x -> count(x .== :sheep)) => :nsheep,
	)
end
```

Here's a quick comparison to see what I mean

![image](https://user-images.githubusercontent.com/33273948/119977833-14a87d80-bfe3-11eb-8265-a193acc84bbb.png)
```julia
let f = Figure()
	adf1 = collect_agg(Schedulers.by_id)
	adf2 = collect_normal(Schedulers.by_id)
	a = Axis(f[1,1])
	b = Axis(f[1,2])
	lines!(a, adf1.step, adf1.nwolf)
	lines!(a, adf2.step, adf2.nwolf)
	lines!(b, adf1.step, adf1.nsheep)
	lines!(b, adf2.step, adf2.nsheep)
	f
end
```

> That's another thing I don't understand... random_agent does not do shuffle!(model.rng)...?

This I might be wrong, but according to the code it does trigger the rng some where.

**Comment by Datseris** [comment]
I edited my comments, you got the problem nailed down.

**Comment by Datseris** [comment]
I'll let Tim handle this one, because he was much more involved in the RNG enhancements, he should have the best course of action.

**Comment by Libbum** [comment]
Interesting bug! I'm pretty sure you're right about your suggested fix: `a = .. # maybe pick the first agent?`.

Using a random_agent here is definitely not a requirement and the first solution (adding a random_agent to `multi_agent_types!`) may get unstuck in the future if we need to extend the data collection system. 

I'll play around a bit to make sure that's the best way to go to be certain.

**Comment by ndgnuh** [comment]
## More on the video situation

I have only reproduced the mismatch on `randomly` scheduler (I re-run the code and re-rendered the video twice...). I have not yet figured out what's the problem here though.

These is video and the plot from `by_id` scheduler. (notice the population matches with the imagery from step ~1800 to end in the videos.

![image](https://user-images.githubusercontent.com/33273948/119987443-3c9dde00-bfef-11eb-96ad-cc3e67436191.png)


https://user-images.githubusercontent.com/33273948/119987954-c9489c00-bfef-11eb-9ce7-858436ec22ed.mp4


https://user-images.githubusercontent.com/33273948/119987985-cf3e7d00-bfef-11eb-9c37-969779f1aa51.mp4
