### ISSUE TITLE
Problem with our go-to doc example (Schelling): it has no model logic or model step function

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#517]
Our schelling example is very good, and written clearly. It shows pretty much everything you need to know to get started.

Well, no, not everything. I realize now that the Schelling model can be missleading. It might make users make model-level logic as new agents instead. Perhaps it would be worth it to incorporate some really basic model-level logic to Schelling, just to show that the `model_step!` is useful as well, and avoid putting all ABM logic into the agent stepping?

**Comment by Libbum** [comment]
As a section that extends the base model in the example - yes that sounds good. It should not be reflected in Models.schelling though.

**Comment by fbanning** [comment]
Nice idea. It's good to extend on the basics in the same environment that's already known to new users.

We could for example introduce a new model property `diversity` as a simple extension that's conceptionally not too far from the basic segregation model. A new `diversity` variable is added to each agent which we then can use in `model_step!` to calculate a mean `diversity` value on the aggregate level for the whole population. This can then be stored in the `model.properties` as `diversity` and could demonstrate how to compute aggregates over agent properties.

**Comment by Datseris** [comment]
But if it is only used in data aggregation, a model stepping function is still not necessary. One can aggregated the `diversity` just with agent step and the `run!` function.

**Comment by Datseris** [comment]
Okay I have found a solution to this and will do it before 5.0, because an example with model-stepping action is necessary. One idea is to establish an aggregated spatial property. A grid point whose neighbors are all the same counts as "aggregated". Agents in aggregated grtid locations are not stepped at all. This makes for a custom scheduler that is dynamic, i.e., aware of model nature.
