### ISSUE TITLE
GraphSpace visualizations based on GraphMakie.jl

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#521]
https://discourse.julialang.org/t/ann-graphmakie-jl-plotting-graphs-with-makie/63734 

We can now finally bring back graph plotting. The idea would be the same as our old graphplot function, where each node represents a _vector_ of agents, and the color/size/marker of the node is a function of that vector of agents.

**Comment by Datseris** [comment]
@fbanning maybe wait a moment for me to finish the PR with the OSMPlotting backend at InteractiveDynamics. I'm doing some really useful code refactoring for a space-agnostic codebase. It will make your own development easier I'd recon.

**Comment by fbanning** [comment]
Curious how you approach it. Already have a branch or fork I could have a look at?

**Comment by Datseris** [comment]
https://github.com/JuliaDynamics/InteractiveDynamics.jl/pull/86
