### ISSUE TITLE
Interactive part of the Daisy World example not working properly

### ISSUE THREAD

**Issue by dunefox** [JuliaDynamics/Agents.jl#523]
I'm trying to run the Daisy World example (in JupyterLab) to build on it but the [interactive simulation](https://juliadynamics.github.io/Agents.jl/stable/examples/daisyworld/#Interactive-scientific-research) only produces an image. The code is ran exactly as is.  [CairoMakie](https://github.com/JuliaPlots/CairoMakie.jl) has been deprecated and integrated into [Makie](https://github.com/JuliaPlots/Makie.jl) which might be the problem. Does this occur for anyone else?

Julia 1.6 in Ubuntu 20.04

**Comment by Datseris** [comment]
Hi, 

You need GLMakie to use the interactive applications. CairoMakie does not have any interactivity.

**Comment by dunefox** [comment]
I have imported and built GLMakie and I still get this message when trying to run the last part:

> No backend available (GLMakie, CairoMakie, WGLMakie)!
Maybe you imported GLMakie but it didn't build correctly.
In that case, try `]build GLMakie` and watch out for any warnings.
If that's not the case, make sure to explicitely import any of the mentioned backends.

Imports:

> using Agents
using Statistics: mean
using InteractiveDynamics
using GLMakie
using Random
import StatsBase
import DrWatson: @dict

Essentially, the only was I get any kind of visual output is by using CairoMakie, otherwise I get "Figure()" for images and the above error for the interactive part and videos.

**Comment by Datseris** [comment]
I can run everything fine, just run the Daisyworld example again on my computer. Are you sure you have correct package versions? What's the versions you have?

**Comment by Datseris** [comment]
> I can run the examples from InteractiveDynamics (albeit quite slow)

Are you referring to the _compilation_ time, or the animation time? The animations and interactive applications are ridiculously fast. If you find them slow after you have compiled, then there is definitely something wrong on your end. E.g. do you have a GPU, as GLMakie works on the GPU?

**Comment by dunefox** [comment]
> I can run everything fine, just run the Daisyworld example again on my computer. Are you sure you have correct package versions? What's the versions you have?

>   [46ada45e] Agents v4.4.1
  [634d3b9d] DrWatson v2.0.5
  [e9467ef8] GLMakie v0.2.7
  [7073ff75] IJulia v1.23.2
  [c601a237] Interact v0.10.3
  [ec714cd0] InteractiveDynamics v0.15.3
  [ee78f7c6] Makie v0.13.14
  [2913bbd2] StatsBase v0.33.8

> Are you referring to the _compilation_ time, or the animation time? The animations and interactive applications are ridiculously fast. If you find them slow after you have compiled, then there is definitely something wrong on your end. 

Both, the compilation takes quite some time, and occasionally the visualisation takes time to react and is a bit laggy.

> E.g. do you have a GPU, as GLMakie works on the GPU?

Yes, an AMD RX 480.

**Comment by Datseris** [comment]
> [e9467ef8] GLMakie v0.2.7

GLMakie's approrpiate version is 0.4 while Makie's is 0.14.

**Comment by Datseris** [comment]
stable versions can be found: http://makie.juliaplots.org/stable/

**Comment by dunefox** [comment]
>  [c601a237] Interact v0.10.3

For some reason, I installed Interact which apparently downgrades Makie and GLMakie. After removing and updating I get:

>   [46ada45e] Agents v4.4.1
  [634d3b9d] DrWatson v2.0.5
  [e9467ef8] GLMakie v0.4.2
  [7073ff75] IJulia v1.23.2
  [ec714cd0] InteractiveDynamics v0.15.3
  [ee78f7c6] Makie v0.14.2
  [2913bbd2] StatsBase v0.33.8

Now, with the latest versions it works as intended. Thanks for your help.

**Comment by Datseris** [comment]
Interact.jl hasn't been updated in 2 years: https://github.com/JuliaGizmos/Interact.jl

**Comment by Libbum** [comment]
Here's the issue: The version dependencies are messed up due to the AbstractPlotting -> Makie change. There's no real way around it other than:
- Remove Makie, GLMakie, CairoMakie, AbstractPlotting.
- Add GLMakie
