### ISSUE TITLE
Fractal Growth Example not working (KeyError: key :rng not found)

### ISSUE THREAD

**Issue by MateoPeri** [JuliaDynamics/Agents.jl#525]
**Describe the bug**
Running [the fractal growth example](/JuliaDynamics/Agents.jl/blob/master/examples/fractal_growth.jl) as provided on the docs/github returns the following error:
```
KeyError: key :rng not found


Stacktrace:

 [1] getindex

   @ ./dict.jl:482 [inlined]

 [2] getproperty(m::AgentBasedModel{ContinuousSpace{2, true, Float64, typeof(Agents.defvel)}, Particle, typeof(fastest), Dict{Symbol, Real}}, s::Symbol)

   @ Agents ~/.julia/packages/Agents/YADxD/src/core/model.jl:142

 [3] initialize_model(; initial_particles::Int64, space_extents::Tuple{Float64, Float64}, speed::Float64, vibration::Float64, attraction::Float64, spin::Float64, clockwise_fraction::Float64, min_radius::Float64, max_radius::Float64)

   @ Main ./In[8]:29

 [4] initialize_model()

   @ Main ./In[8]:14

 [5] top-level scope

   @ In[12]:2

 [6] eval

   @ ./boot.jl:360 [inlined]

 [7] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)

   @ Base ./loading.jl:1094
```

**Minimal Working Example**
> Please provide a piece of code that leads to the bug you encounter.
Run the example (either copy from the docs or from github).

> If the code is **runnable**, it will help us identify the problem faster.
It is not runnable, that is the issue.

**Agents.jl version**
`[46ada45e] Agents v4.0.1`

I have tried on my local machine (macOS, latest Julia 1.6.1) and on Google Colab. Both report the same error. I just started learning Julia today, but from what I can tell the program fails at `model.rng`. Models are supposed to have a `rng`component, right? Did I miss an install step or something? The rest of the program works fine.

TIA

**Comment by Datseris** [comment]
update Agents, as the `rng` keys was introduced in v4.1. Current version btw is much later than v4.1. It is a good idea to cross check the version you see in the docs (bottom left corner), with what you have installed before running the examples.

**Comment by MateoPeri** [comment]
Is there a way to force-update? As I said, I just installed `Agents.jl` today using the docs' code.
```jl
julia> using Pkg; Pkg.add("Agents")
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.6/Project.toml`
  No Changes to `~/.julia/environments/v1.6/Manifest.toml`

julia> Pkg.status("Agents")
      Status `~/.julia/environments/v1.6/Project.toml`
  [46ada45e] Agents v4.0.1
```
