### ISSUE TITLE
OSM alternative: LightOSM.jl

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#533]
We wanted a new OSM pipeline, perhaps we should consider this one: https://deloittedigitalapac.github.io/LightOSM.jl/docs/ 

Apparently it has already written `nearby_positions` for us!

But they don't display any performance improvements w.r.t. OSMX.jl. I'll ask for some.

**Comment by Libbum** [comment]
This looks really good.

- KDtree for neighbors
- Routing and other functions are there already
- Represented on a graph, but still contains all the underlying features which we can then incorporate.
- Nice to see my home city as an example :)

In general I think this is well worth considering.

**Comment by fbanning** [comment]
Very promising, thanks for bringing this up.

> But they don't display any performance improvements w.r.t. OSMX.jl. I'll ask for some.

These shortest path benchmarks seem pretty good to me: https://deloittedigitalapac.github.io/LightOSM.jl/notebooks/benchmarks/  
Or were you thinking about other performance measurements=

**Comment by Datseris** [comment]
I was thinking about loading and creating the graph times, but these are also important!

Also, cc @captchanjack

**Comment by Datseris** [comment]
@fbanning or @Libbum the creator has a poster in today's juliacon poster session, might be worth dropping by and saying hello.

**Comment by Libbum** [comment]
Awesome. Will try and get there.

**Comment by AayushSabharwal** [comment]
This looks really cool. I'll take a look at their A* implementation later and see if we can use it in pathfinding

**Comment by captchanjack** [comment]
Hey all!

Thanks for showing interest in LightOSM! Unfortunately I won't be able to host the poster session as I've been quite busy with work, nevertheless happy to answer any of your questions here.

Regarding the benchmarks, I haven't been as active but I'll try to find some time to measure the graph creation time + nearest node calcs! Also any suggestions for improvements are more than welcome :)!

**Comment by jgamper** [comment]
Hey all! It seems that LightOSM pr transitioning from LightGraphs to Graphs https://github.com/DeloitteDigitalAPAC/LightOSM.jl/pull/53 has been merged recently (relating to a discussion here https://github.com/JuliaDynamics/Agents.jl/pull/564) - what needs to be done to transition to LightOSM from OpenStreetMapX? 

I suppose a complete replacement for https://github.com/JuliaDynamics/Agents.jl/blob/master/src/spaces/openstreetmap.jl needs to be written?

**Comment by Datseris** [comment]
Yeah, and we would appreciate someone doing that _extremely much_ I have to admit. To be fair, a full re-write of this source file is not necessary. Nearest neighbor searching is in fact implemented already in LightOSM.jl, so you can save some lines of code there :) 

But yeah, you just need to replace this file and be sure that all tests pass etc. :)

**Comment by AayushSabharwal** [comment]
Yeah! If you would like to work on the migration, please feel free to open a PR.

I'd also like to add that we would also need to make sure the zombies example still runs after this, since the video is pre-rendered and wouldn't be changed even if it breaks.

**Comment by Datseris** [comment]
Well the video case is problematic. The video was made using the OSMX_plotting package, which I guess also has to go if we are moving to LightOSM.jl. But in any case, we have agreed long time ago with @Libbum that plotting that doesn't use Makie.jl is too slow to be useful for Agents.jl at any scale greater than 10 city blocks.

**Comment by AayushSabharwal** [comment]
I took a quick stab at this a while ago, it's not a small task. I'm not entirely sure how some of the functions (like `road`) work, so translating them is a little difficult.

**Comment by Datseris** [comment]
:( Unfortunate. Has The OSMX.jl package transitioned to Graphs.jl already in the meantime? But to be honest I think it really is important to move to the cleaner and faster LightOSM.jl...

**Comment by Datseris** [comment]
@AayushSabharwal keep in mind, no matter what, this will be a breaking release. You can break things for better/simpler/easier design.
