### ISSUE TITLE
Speed up pathfinding

### ISSUE THREAD

**Issue by AayushSabharwal** [JuliaDynamics/Agents.jl#537]
Pathfinding in its current state works, but there is definitely scope for performance improvement, specifically around how much the algorithm allocates:

GridSpace
```
100x100, 0 Admissibility
  10.913 s (51446799 allocations: 10.66 GiB)
100x100, 0.3 Admissibility
  2.033 s (10551657 allocations: 2.45 GiB)
```

ContinuousSpace
```
100x100, 0 Admissibility
  18.884 s (87439621 allocations: 17.39 GiB)
100x100, 0.3 Admissibility
  15.266 s (69817111 allocations: 13.68 GiB)
```

We could probably save on a lot of this by preallocating some of the data structures we use, but that increases demand on memory. This can just be assumed to be acceptable, since in the worst case (when a path doesn't exist) the user would pay somewhere close to that cost anyway.

It would probably be better to explore other pathfinding algorithms for larger maps that A* wouldn't be able to handle.

I think there might also be a way to avoid double-allocating paths for continuous space as it happens now, since coordinate spaces need to be converted. This would also help a lot.

**Comment by Datseris** [comment]
The way the benchmarks are presented is not really useful for optimization purposes; we don't know where a performance hit may be coming from, if any, and these numbers seem to include the "size" of the system / amount of agents, which we don't really care about. The important point is to benchmark atomic functions:

- How much time does it take to initialize an Astar
- Given a single starting position and target position, `@btime` the set_route function
- `@btime` the `move_along_route!` function
- How do these times scale versus the grid length?
- etc....

**Comment by AayushSabharwal** [comment]
I'm working on a jupyter notebook to display the results of various benchmarks, and it's partially complete:

https://gist.github.com/AayushSabharwal/34bf67f99174144e104753623c3667bb

`find_path` (and by extension `find_continuous_path` and `set_target!`) appear to be the bottlenecks. Using `ProfileView` (which renders in a GTK window that I can't include in a notebook) I also noticed the call to `delta_cost` is dynamic, and accounts for a decent chunk of performance. I'll profile that too, as I expand on this file.

**Comment by Datseris** [comment]
everything dynamic needs to be eliminated!

**Comment by AayushSabharwal** [comment]
I've finished the benchmarks for both grid and continuous space. They give a good idea of the current botteneck, and I will add additional benchmarks as and when they seem necessary. The gist doesn't want to render the notebook, so it needs to be viewed on nbviewer:
https://nbviewer.jupyter.org/gist/AayushSabharwal/34bf67f99174144e104753623c3667bb
