### ISSUE TITLE
Agent inspection on mouse hover

### ISSUE THREAD

**Issue by fbanning** [JuliaDynamics/Agents.jl#538]
I'd like to add a simple way to inspect single agents on mouse hover. I'd just like to see a simple tooltip with the agent variables and their current values.  
What do you think about this? Have there already been some plans to implement such a thing?

Makie already provides [`DataInspector`](http://makie.juliaplots.org/stable/interaction/inspector.html) and the ability to customise the shown tooltip. From what I've just tested, the basics of this seem easy enough to add but the customised tooltip may need a bit more time to understand how it should be done.

**Comment by Datseris** [comment]
(I transferred this to Agents.jl, because it will be more visible to the Agents.jl users here)

**Comment by fbanning** [comment]
Quick update, I'm currently working on this and got the basics down:

![grafik](https://user-images.githubusercontent.com/65158285/128723158-b39cfb52-8717-447b-b421-ed848eae2b51.png)

I think this is very much doable in the foreseeable future, although I'm still a bit confused about a few things. Need some more time to wrap my head around those. I will create a PR at InteractiveDynamics.jl at some point and we can look at any persisting problems together then. :)

**Comment by fbanning** [comment]
Here's something I'm currently thinking about and would like your feedback on:

If we have one agent at a position it currently looks like this
![grafik](https://user-images.githubusercontent.com/65158285/128880402-5ced6dc9-b0b1-4d49-b8f0-da36e696cf52.png)

Having multiple agents will just list them below each other
![grafik](https://user-images.githubusercontent.com/65158285/128880559-d9bf82ec-e4e2-483e-81e6-6562fbbbb42d.png)

But having a lot of agents might break the formatting and make parts of the tooltip useless
![grafik](https://user-images.githubusercontent.com/65158285/128880767-98a1d924-211f-4921-a85d-8421f8ea0928.png)

This problem of course get worse when agents have a lot of variables to display.

I can think of two ways to go about this:
1. Leave it as it is. This is pretty flexible, although it has its natural limits as can be seen above.
2. Format the tooltip as a table with one row per agent variable and one column per agent. This might look pretty nice but we will need to account for displaying tooltips for models with multiple agent types. Definitely doable but would require a bit more work.

I would favour the second option which is more work but should hopefully look better in the end. What are your thoughts on this? Maybe you've got some more ideas how to display the agent data?

**Comment by Datseris** [comment]
How would the version 2 make this problem dissapear? Instead of being too large in the vertical direction the tooltip would be come too large in the horizontal... I think it isn't really worth the dev effort right now and would go with 1. One thing worth changing is to display only the final type instead of `Agents.Models.Sche....`. How do you obtain the type name? I think you have to use the `nameof` function.

**Comment by fbanning** [comment]
Modern displays normally have more horizontal than vertical space which is why a table (option 2) instead of a list (option 1) might make use of that as well as saving a bit of space for listing the agent type for each agent.

But I think you're right and we can just stick to the list view for now. Maybe at a later time I'll revise this if I find the time.

> One thing worth changing is to display only the final type instead of `Agents.Models.Sche....`. How do you obtain the type name? I think you have to use the `nameof` function.

Done, thanks. :)

**Comment by Datseris** [comment]
(perhaps it's time for a PR on this, so I can give more feedback on code? It looks pretty close to finished already)

**Comment by Datseris** [comment]
None whatsoever, and I'm not even sure how stable and complete the interface is :(

**Comment by fbanning** [comment]
OK, that's no problem. I'm currently chipping away at it and am making progress, albeit a bit slower than I'd like to. Will keep you updated about this. Once I got a basic recipe working with a custom plot type for simple 2D non-poly models, I will create a PR for you to look at. :)
