### ISSUE TITLE
update plot for agent.jl main API

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#54]

**Comment by kavir1698** [comment]
Please check the new diagrams.

**Comment by Datseris** [comment]
It is difficult for me to go through Git history at the moment, can you upload it here?

**Comment by kavir1698** [comment]
Figure 1:
![overviewModel](https://user-images.githubusercontent.com/3798865/69368160-dfa6c680-0c99-11ea-8175-6c77d59fd4d6.png)

Figure 2
![overviewModelObject](https://user-images.githubusercontent.com/3798865/69368161-dfa6c680-0c99-11ea-9fe8-c9331caa5387.png)

**Comment by Datseris** [comment]
Hm, first of all, this is a very nice font! Which one is it?
In general the figure looks good. But I have some comments:

For Figure 1: 

* What does the box "Model Object" achieve? Because the model object is infact ABM, nothing more. I feel it is confusing, and should be removed.
* I would prefer if `ABM` was expanded to `AgentBasedModel`

For Figure 2:
I don't think it should exist. The standard user does not need to know everything about the fields of `ABM`, besides `properties`. The other fields are never accessed directly, maybe in some cases only `agents`. but the others definitely are only taken care of via the provided API. And given #64 accessing directly the fields of ABM will be even less necessary.

**Comment by kavir1698** [comment]
The font is "Comfortaa".

I agree with your suggestions for Fig. 1. But I think Fig. 2 helps the user to understand how everything is organized. Of course, they do not have to access these fields is most cases, but still knowing the organization can help. I imagine there are actions for which we do not have any function yet.

**Comment by Datseris** [comment]
Okay, I see. 

> I imagine there are actions for which we do not have any function yet.

This is a convincing argument, so I accept.
