### ISSUE TITLE
Progress meter

### ISSUE THREAD

**Issue by kavir1698** [JuliaDynamics/Agents.jl#542]
I vaguely remember there used to be an option to print the progress of a simulation in the `run!` function. Am I correct? Any reason it has been taken out? This is an important feature for heavy simulations.

**Comment by Libbum** [comment]
It's used in [paramscan](https://github.com/JuliaDynamics/Agents.jl/blob/c9a7fa13493c0ba24aacd0a6a6de4ba19394d181/src/simulations/paramscan.jl#L71) at the moment, unsure if it was in run previously and was omitted in some refactor or it was never there. 

Certainly see no reason it cant be a keyword flag.

**Comment by fbanning** [comment]
Can't remember the progress meter being displayed when using `run!`. Anyways, I think it would be a good thing to have and I definitely agree that it will help with longer simulations.

**Comment by Datseris** [comment]
How do you track progress when run is used with a termination function? For `n::Int`, this is super easy to do, low hanging fruit.

**Comment by kavir1698** [comment]
When the end is not known, one can only show the number of iterations passed.
