### ISSUE TITLE
Adding plots to abm_data_exploration

### ISSUE THREAD

**Issue by marcelovmaciel** [JuliaDynamics/Agents.jl#551]
As advised by @Datseris I am opening an issue for that. Basically, what should I do to, analogously to what is done in the [sugarscape example]((https://juliadynamics.github.io/Agents.jl/stable/examples/sugarscape/ ), add a plot to abm_data_exploration? I've only managed to add the plot to the fig the procedure returns, but not update it.  I suppose I'll have to fiddle with Observables and so on, but the best route to do so is not clear from what I could understand reading the docs and source code.

**Comment by Datseris** [comment]
did you use the `abmstepper` like it is advised in the sugarscape example?

**Comment by marcelovmaciel** [comment]
The function does not return a stepper does it? From the docs: "Calling `abm_data_exploration` returns: `figure, agent_df, model_df`." I think its line https://github.com/JuliaDynamics/InteractiveDynamics.jl/blob/54deb6ea88be2e510faa4fba4ab1e32a32cb095c/src/agents/interactive_parameters.jl#L144

**Comment by marcelovmaciel** [comment]
But let's say I was using abm_play, which does return a stepper. How would I go on with hooking the update of the observable into the interactive figure? In the sugarscape example one simply updates the observable right after  Agents.step!(abmstepper, someotherstuff) in a loop, but now the loop happens when I press the button in fig so I don't know where should I add this observable updating.

**Comment by Datseris** [comment]
Can you dev a branch and make it return the `abmstepper` as well, and then try to do whatever sugarscape does? just modify the return signature to `return figure, df_agent, df_model, abmstepper`. As you have seen, there is an `abmstepper` in the function I just didn't have the forsight to return it.

**Comment by marcelovmaciel** [comment]
ok! I'll try that

**Comment by marcelovmaciel** [comment]
So, following the previous question I tried to modify `abm_play!` and see if making it work in this procedure I could translate that to `abm_data_exploration`. That is, I created the fig, stepper with `abm_play` and tried some ugly hack in `abm_play!`.  No luck. I tried to add an observable and modify it in the `on(step)` parts such as [this](https://github.com/JuliaDynamics/InteractiveDynamics.jl/blob/54deb6ea88be2e510faa4fba4ab1e32a32cb095c/src/agents/interactive_parameters.jl#L96), kinda like what is done in the Sugarscape example, but it still does not update the figure when I click step or run.

**Comment by Datseris** [comment]
yeah but how do you create the new plot? If you don't plot **Observables** that are lifted from `abmstepper`, why would it update...?

**Comment by marcelovmaciel** [comment]
Sorry, I don't understand. In the sugarscape example, the only thing being lifted is a supertitle. I'll come back later with a mwe.

**Comment by Datseris** [comment]
Yeah, a MWE would make the situation much easier. I'm also quite short on time so I haven't delved deeply enough here... I may be suggesting nonsense. Nevertheless, the actual suggestion of this post is surely wanted: to be able to add more plots in the exploration app.

**Comment by marcelovmaciel** [comment]
The [MWE](https://github.com/marcelovmaciel/AddPlotMWE/blob/main/test/repltest.jl ).

**Comment by marcelovmaciel** [comment]
The code is small so I'll post it here. First define the model: 
````
using Agents
using Distributions
using GLMakie
using InteractiveDynamics




mutable struct  DummyAgent{n} <: AbstractAgent
    id::Int
    pos::NTuple{n,Float64}
    othervar::Vector{Float64}
end

function model_initialize(nagents,n)
    space = ContinuousSpace(ntuple(x -> float(1),n))

    model = ABM(DummyAgent{n}, space, properties = Dict(:n=> n,
                                                        :othervars => Dict{Int64, Array{Float64}}()))

        for i in 1:nagents
        pos = Tuple(rand(Uniform(0,1), n))
        othervar =  rand(Uniform(0.4,0.5),n)
        add_agent_pos!(DummyAgent{n}(i, pos,othervar), model)
    end

    model.properties[:othervars] =  Dict((model[x].id => model[x].othervar)
                                        for x in allids(model))
    return model
end


function model_step!(model)
    # Ill write a step that changes only the second plot
    for i in allids(model)
        randombound = rand(Uniform(0.5,1)) # so the second plot changes
        model[i].othervar = rand(Uniform(0.4, randombound),model.properties[:n])
        model.properties[:othervars][i] = model[i].othervar
    end
````

Then a test  to see if I can get the plot to be updated:

````


m = model_initialize(500, 2)

fig,stepper = abm_play(m,dummystep,model_step!)

foo = Observable([Point{2}(x) for x in values(m.properties[:othervars])])

scatter(fig[1,2], foo)

fig # the second plot indeed appears. Lets click step a few times

foo[] = [Point{2}(x) for x in values(m.properties[:othervars])] #update the observable

fig #voila the second plot changed.

# Now try to make it change when I click stuff

m = model_initialize(500, 2)

fig,stepper = abm_play(m,dummystep,model_step!)

foo = Observable([Point{2}(x) for x in values(m.properties[:othervars])])

scatter(fig[1,2], foo)

# Maybe adding a new step function?
function newstep(m, foo = foo)
    model_step!(m)
    foo[] = [Point{2}(x) for x in values(m.properties[:othervars])]
end

InteractiveDynamics.abm_play!(fig,stepper, m, dummystep,
                              newstep, spu = 1:10)

fig # nope, doesn't work
````

**Comment by fbanning** [comment]
I'm not 100% sure what you're aiming to do (probably I'm missing the point here) but why don't you just define the second plot already when running `abm_data_exploration`? Isn't it easy enough to add a new entry to the `adata` or `mdata` vectors (depending on which you need)?

Say you have the following simple example:

```julia
using Agents
using InteractiveDynamics
using GLMakie
using Statistics

model, agent_step!, model_step! = Models.schelling()

params = Dict(:min_to_be_happy => 1:1:5)

fig, adf, mdf = abm_data_exploration(model, agent_step!, model_step!, params; 
    adata=[(:mood, mean)])
```

If you then want to add a second plot tracking for example the number of unhappy agents, you can just write:

```julia
count_unhappy(model) = count(a.mood == false for a in allagents(model))
fig, adf, mdf = abm_data_exploration(model, agent_step!, model_step!, params; 
    adata=[(:mood, mean)], mdata=[count_unhappy])
```

Does this solve your problem? If not, in how far does your use case differ from what I described here?

**Comment by marcelovmaciel** [comment]
@fbanning thank you for taking your time. It does not because the code you posted adds a new time series to the "time series column" in the figure. Say the first "column" is the scatterplot of agents and the buttons. The second is the time series. I want to be able to add an arbitrary third column next to the time series with say a histogram of some variable or a scatterplot (like in the sugarscape example) and so on. The code I posted does add the additional figure, but it is hacky AND the additional plot is not updated like the ones provided by the package.

**Comment by fbanning** [comment]
So I've finally found the time to look at this issue again. It's actually easy to solve and you were on the right track.

What you've missed in your approach was, that `abm_play` already takes `model_step!` as an argument and thus saves it in memory. If you later on create a new stepping function `newstep` to wrap the updating of your `foo` observable's values, then you already need to pass this function to `abm_play` instead. With your MWE above, you can do the following:

```julia
m = model_initialize(500, 2)

foo = Observable([Point{2}(x) for x in values(m.properties[:othervars])])

function newstep(m, foo = foo)
    model_step!(m)
    foo[] = [Point{2}(x) for x in values(m.properties[:othervars])]
end

fig,stepper = abm_play(m, dummystep, newstep)

scatter(fig[1,2], foo)
```

Now click on step a few times and you can see how the newly created plot updates itself.

Hope this answers your question.

**Comment by Datseris** [comment]
That's worth putting in the docs. I guess it is an even simpler approach than what we do in the Sugarscape example.

**Comment by fbanning** [comment]
Sure, I can do that. We would need to update the Sugarscape example on Agents docs and add a small section on creating new plots on the InteractiveDynamics docs.

On a sidenote: I'm still trying to figure out how to directly access the model properties via the already existing model observable that's now accessible through our new `ABMPlot` type. This would allow us to skip creation of the `foo` observable and the `newstep` function. Then also no reinitialisation of `fig` and `stepper` with a wrapped stepping function would be necessary. Didn't get it to work so far, though. I think I'm missing a crucial point somewhere. (Anyways, I think this discussion goes a bit too far and is more suited for the InteractiveDynamics.jl repo.)

**Comment by marcelovmaciel** [comment]
@fbanning this is so cool!!! Thank you! I'll have lots of fun with this newfound power hahahah @Datseris may I close this issue?

**Comment by Datseris** [comment]
![image](https://user-images.githubusercontent.com/19669089/144509144-1090b189-7f63-4b21-9b87-49a29bd14d4b.png)
