### ISSUE TITLE
Failed to compile ProtoBuf and OpenStreetMapX

### ISSUE THREAD

**Issue by SudoMishra** [JuliaDynamics/Agents.jl#555]
I just cloned the repo and tried to precompile the package but I'm getting errors.
```
LoadError: LoadError: LoadError: Failed to precompile ProtoBuf [3349acd9-ac6a-5e09-bcdb-63829b23a429] to C:\Users\sudha\.julia\compiled\v1.6\ProtoBuf\jl_3F73.tmp
```
```
LoadError: LoadError: InitError: could not load library "C:\Users\sudha\.julia\artifacts\51687438ed08ae061b2b96f18d0b569df3201a0e\bin\libprotoc-26.dll"
The specified module could not be found.
```
```
LoadError: LoadError: Failed to precompile OpenStreetMapX [86cd37e6-c0ff-550b-95fe-21d72c8d4fc9] to C:\Users\sudha\.julia\compiled\v1.6\OpenStreetMapX\jl_583B.tmp.
```
Is this happening with others?

**Comment by AayushSabharwal** [comment]
Try deleting that subfolder under `artifacts`, running `instantiate` and then `precompile`? I've faced an issue a couple times where things didn't download correctly.

**Comment by SudoMishra** [comment]
Okay, I think what happened was there was some error during downloading so I had the folder with the corresponding hash but there wasn't anything in there. Deleting the folder and instantiating again solved it. Thank you @AayushSabharwal
