### ISSUE TITLE
Nearby_ids missing some agents in ContinuousSpace

### ISSUE THREAD

**Issue by mbruna** [JuliaDynamics/Agents.jl#560]
**Describe the bug**
I am getting some unexpected behavior from nearby_ids in ContinuousSpace. In particular, it is not returning all the ids of agents nearby. 

**Minimal Working Example**
Please find that attached (apologies that it is not that "minimal", but it is as far as I could get it to). I have explained in comments what the issue is for a particular configuration (from line 123)

If the code is **runnable**, it will help us identify the problem faster.

**Agents.jl version** 

Please provide the version you use (you can do `Pkg.status("Agents")`.
Agents v4.5.6
[ABM_minimal.jl.zip](https://github.com/JuliaDynamics/Agents.jl/files/7295526/ABM_minimal.jl.zip)

**Comment by Datseris** [comment]
Probably related with #565 . There might be indeed a bug in our exact filtering.

**Comment by Datseris** [comment]
This should be fixed in current `main` branch, soon to be 5.4 release. Feel free to reopen if it isnt'.
