### ISSUE TITLE
Update LightGraphs.jl to Graphs.jl dependency

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#562]
See https://discourse.julialang.org/t/lightgraphs-jl-transition/69526/17

**Comment by Pistrix** [comment]
`GraphSpace(::G)` is failing instantiation with graph objects made with the `Graphs.jl` package (and `MetaGraphs.jl`.) Seems to work fine with final `LightGraphs.jl` graph objects. 

Package Versions:
> Agents v4.5.7
> Graphs v1.4.1
> LightGraphs v1.3.5

Code to Generate Error:
> `using Agents, Graphs; GraphSpace(complete_digraph(5))`

Error:
> `ERROR: MethodError: no method matching GraphSpace(::SimpleDiGraph{Int64})`
`Closest candidates are:`
  `GraphSpace(::G, ::Vector{Vector{Int64}}) where G at C:\Users\User\.julia\packages\Agents\h9Ls1\src\spaces\graph.jl:7`
  `GraphSpace(::G) where G<:LightGraphs.AbstractGraph at C:\Users\User\.julia\packages\Agents\h9Ls1\src\spaces\graph.jl:26`
`Stacktrace:`
 `[1] top-level scope`
   `@ REPL[2]:1`

Did something get missed in the transition?

**Comment by AayushSabharwal** [comment]
That's absurd. Somehow, 4.5.7 doesn't have the changes from #564 even though it's listed in [the release](https://github.com/JuliaDynamics/Agents.jl/releases/tag/v4.5.7).

**Comment by Datseris** [comment]
It's very odd that this was listed in the release, because Graphs.jl is supposed to be enabled only after 5.0. 

This is fixed on master, issue is closed. You can either wait for 5.0 release to use Graphs.jl, or use master branch (development version of Agents.jl).

**Comment by Datseris** [comment]
ah: autogenerated release notes are just listing open and closed PRs, they do not know from which branch a release was tagged. So please just use CHANGELOG which is human written and curated.
