### ISSUE TITLE
Understanding the ```r``` parameter in ```nearby_ids```

### ISSUE THREAD

**Issue by marcelovmaciel** [JuliaDynamics/Agents.jl#565]
I am trying to understand what the r parameter does in the ```nearby_ids``` procedure, specifically in the continuous case. In the docs the following is said: " Standard distance according to the space metric." Could someone elaborate to someone whose mathematical training is limited to calculus and linear algebra (I completely understand if y'all are busy!!) ? What is the change in behavior that changing r will have in the procedure?

 I am writing a simulation in which I set some "central" points and want to get nearby points. So,  I wrote some code to explore it. However, when I set r to 1, and exact to true, and test the euclidean distance (from the central points) I get a distance of ~1.2, which is not the behavior I was expecting. However, when I set r to 2 I still get a distance of  1.2! Doubling r does not change the euclidean distance of the points sampled using the nearby_ids procedure. 

```julia
using Agents, Distances, Distributions

mutable struct  DummyAgent{n} <: AbstractAgent
    id::Int
    pos::NTuple{n,Float64}
end

function sample_Centerpoints_to_nearbydummies(npoints, model)
    ids = collect(allids(model))

    centerids= sample(ids,npoints,replace = false)

    centerpoints_nearbydummies = Dict(Pair(k,  -1) for k in centerids)

    return(centerpoints_nearbydummies)

end

function set_nearbies!(model)
    pointsdict = model.properties[:pointsdict]
    r = model.properties[:r]
    get_nearbypointid(pointid)= sample(collect(
        nearby_ids(model[pointid],
                       model, r,
                       exact = true)))

    centerpoint_nearbypoint_pairs = Dict(Pair(pid,
                                              get_nearbypointid(pid))
                                         for pid in keys(pointsdict))

    for (cid, nid) in centerpoint_nearbypoint_pairs
        pointsdict[cid] = nid
    end
end


function model_initialize(nagents,n, ncs,  r = 1)
    space = ContinuousSpace(ntuple(x -> float(1),n))

    model = ABM(DummyAgent{n}, space, properties = Dict(:n=> n,
                                                        :r => r,
                                                        :pointsdict => Dict{}()))

        for i in 1:nagents
        pos = Tuple(rand(Uniform(0,1), n))
                add_agent_pos!(DummyAgent{n}(i, pos), model)
                end


    model.properties[:pointsdict] = sample_Centerpoints_to_nearbydummies(ncs, model)
    set_nearbies!(model)
    return model
end


r=1
for i in 1:10
    m = model_initialize(1000,2, 100, r)
    maximum([Distances.euclidean(m[cid].pos,m[nid].pos)
             for (cid,nid) in m.properties[:pointsdict]]) |> println
end

#=
1.0600469817653908
1.1146469931411775
1.1382090904186484
1.043741312973825
0.975082751450818
1.0846058257611162
1.228164192811571
1.1257033374510226
1.180173316553839
1.142794281626783
=#



r=2
for i in 1:10
    m = model_initialize(1000,2, 100, r)
    maximum([Distances.euclidean(m[cid].pos,m[nid].pos)
             for (cid,nid) in m.properties[:pointsdict]]) |> println
end


#=
1.230712318455345
1.1299289372658443
1.2296617406308241
1.1649147171916512
1.171758995244182
1.0287872874615116
1.0844658585268767
1.0700902907578802
1.0112842966992845
1.041351684524605
=#
```
So, the code above shows what I'm saying. I admit I don't really understand what the r parameter does here and changing it doesn't seem to change the radius of what is being sampled in that code.

**Comment by marcelovmaciel** [comment]
I think the problem was that periodic was true! Now it all makes sense. If I'm going around the space doubling the r won't change a thing, since we already wrapped the space. The exact keyword still does not give the exact bound, but that may be due to floating-point errors, and for my application, it is not a problem.

**Comment by Datseris** [comment]
c.f. also #566
