### ISSUE TITLE
Turn schedulers into function-like objects

### ISSUE THREAD

**Issue by AayushSabharwal** [JuliaDynamics/Agents.jl#576]
Scheduler's are currently normal functions. Turning them into function-like objects has the main benefit of allowing them to be serialized with the model using the `AgentsIO` submodule. It would end up being something like this:

```julia
abstract type AbstractScheduler end

struct Fastest <: AbstractScheduler end

(::Fastest)(model::ABM) = keys(model.agents)
```

and so on. It also makes schedulers that store data a bit easier, so `partially` can be

```julia
struct Partially <: AbstractScheduler
    p::Float64
end

(sched::Partially)(model::ABM) = randomsubseq(model.rng, collect(keys(model.agents)), sched.p)
```
It's a breaking change, so should be good to get in before v5

**Comment by Datseris** [comment]
@AayushSabharwal why is this a breaking change? It really isn't. Remember, the API is defined _by the documentation_ not by the source code. You can change internally wahtever you want if user code doesn't break. And to my understanding this doesn't break anything. 

Now, the problem with your approach is that you'd force all users to make schedulers function-like objects as well, right? Or can we define
```julia
UserScheduler{F} <: AbstractScheduler
f::F
end
```
and wrap any function the user uses as a scheduler into `UserScheduler`?

**Comment by AayushSabharwal** [comment]
> why is this a breaking change?

I assumed renaming would be necessary (`Schedulers.fastest` => `Schedulers.Fastest`) but I guess there's the option of doing `const fastest = Fastest`

> Now, if with your approach is you'd force all users to make schedulers function-like objects as well, then yes indeed this is truly a breaking change.

This was my idea. Although not strictly necessary (`UserScheduler` is a nice idea), it enables more of the model to be serialized and I think is a better way of storing state.

> and wrap any function the user uses as a scheduler into UserScheduler?

Yeah. This would maintain part of the API, and allow custom schedulers to be transferred over without them breaking. The serializer can check if it is a `UserScheduler` type and not bother saving it in that situation.

**Comment by Datseris** [comment]
> The serializer can check if it is a UserScheduler type and not bother saving it in that situation.

So we can save function-like objects but we can't save functions? That's so random.

**Comment by AayushSabharwal** [comment]
JLD2 doesn't save functions particularly well

**Comment by Datseris** [comment]
Pfff, so weird. This makes a bit of a wonky interface though, for user-defined schedulers.

**Comment by AayushSabharwal** [comment]
We can still accept functions as schedulers, and wrap it internally. When deserializing, the `scheduler` keyword is only required for user-defined schedulers. Which was already the case anyway.

**Comment by Datseris** [comment]
Okay, okay, I accept. Can you make a PR for this? Also add a warning on the load function if a user scheduler is detected, both on load and save.
