### ISSUE TITLE
Allocations during stepping

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#581]
### Discussed in https://github.com/JuliaDynamics/Agents.jl/discussions/559

<div type='discussions-op-text'>

<sup>Originally posted by **fbanning** September 28, 2021</sup>
Here's a broader question that's been boggling my mind for a while now:  
Is there any way for us to get rid of allocations during stepping an ABM?

Say we have the following:

```julia
using Agents

model, agent_step!, model_step! = Models.schelling()
```

If we then track allocations during stepping, we can see that there are new allocations every time:

```julia
julia> @allocated step!(model, agent_step!, model_step!, 1)
115760

julia> @allocated step!(model, agent_step!, model_step!, 1)
40160

julia> @allocated step!(model, agent_step!, model_step!, 1)
15776

julia> @allocated step!(model, agent_step!, model_step!, 1)
7328

julia> @allocated step!(model, agent_step!, model_step!, 1)
4784
```

(Of course the number of allocations decreases here because there's less and less movement happening during the simulation.)

I normally would expect that we have done all the necessary pre-allocations during creation of *this* model because we only have `id::Int`, `pos::Dims{D}`, `mood::Bool` and `group::Int` as agent variables. All of those fields have a fixed length in memory unlike for example a mutable vector that might grow over the course of the simulation.

Regular stepping in this case (i.e. no removing/adding of agents) should therefore not result in new allocations, or am I hugely mistaken here? Why do we still observe allocations?</div>

**Comment by Datseris** [comment]
@fbanning raises a good point here. I think `nearby_agents` is allocating. And this shouldn't be, because we tried hard to design this function with iterators instead of collecting data. So, a proper profiling of the `step!` function needs to be done, so that we identify which function allocates.

**Comment by fbanning** [comment]
> I think `nearby_agents` is allocating.

Could be the case but I think the issue lies deeper within the structure of our agents container.
Trying to replicate it in a MWE could look sth like this:

```julia
julia> mutable struct MyType
           id::Int
       end

julia> d = Dict(1 => MyType(1), 2 => MyType(1))
Dict{Int64, MyType} with 2 entries:
  2 => MyType(1)
  1 => MyType(1)

julia> @allocated d[2].id = 2
875338
```

As you can see, this simple value change allocates.
This doesn't happen when we change values of a simpler dictionary:

```julia
julia> d = Dict(1 => 1, 2 => 1)
Dict{Int64, Int64} with 2 entries:
  2 => 1
  1 => 1

julia> @allocated d[2] = 2
0
```

So the problem seems to be with modifying values of a mutable struct?

```julia
julia> a = MyType(1)
MyType(1)

julia> @allocated a.id = 2
0
```

It seems not! So what is happening here in the background that causes allocations to happen? Any ideas from you? I'm a bit at a loss here. 😅

**Comment by Datseris** [comment]
Wait, are the allocations just because of `@alloc`?
```
using BenchmarkTools

julia> @btime d[2].id = 2
  97.725 ns (0 allocations: 0 bytes)
```

**Comment by Datseris** [comment]
benchmark tools is a much better way to measure allocations

**Comment by Datseris** [comment]
actually, no, you were just measuring the allocations due to code compilation...
```
julia> @allocated d[2].id = 2
0
```

**Comment by fbanning** [comment]
> actually, no, you were just measuring the allocations due to code compilation...
> 
> ```
> julia> @allocated d[2].id = 2
> 0
> ```

Oh, man. You're right. Such a rookie error.

> So, a proper profiling of the `step!` function needs to be done, so that we identify which function allocates.

This is definitely the way forward, otherwise we just keep on guessing. 😆

**Comment by AayushSabharwal** [comment]
I ran schelling for 1000 steps with `julia --track-allocation=all`

![image](https://user-images.githubusercontent.com/23384717/163533653-836e9ae6-3716-4da2-82e9-2d3f28544a62.png)

It seems basically all the allocations are in the scheduling

**Comment by Datseris** [comment]
I guess this is only the case for the randomly scheduler though, right? `fastest` shouldn't allocate. You can do the PR that does this, but what worries is me is that for some schedulers or scnearios that many agents die/birth in a step, I belive it will be simply faster to compute the vector instead of trying to fill a preallocated one.

**Comment by AayushSabharwal** [comment]
> I guess this is only the case for the randomly scheduler though, right? fastest shouldn't allocate.

I'll try benchmarking that

> what worries is me is that for some schedulers or scnearios that many agents die/birth in a step, I belive it will be simply faster to compute the vector instead of trying to fill a preallocated one

I might be wrong here, but wouldn't resizing a vector be about as costly as allocating a new one? In the worst case, it simply allocates a new vector and copies over the data. Is that not equivalent to allocating a new vector? On the flip side, reducing the size should be very cheap, and in cases when there's not a drastic change in the number of agents, it saves a lot of work.

Even if allocating every time ends up being faster in some scenarios, the user has the allocating version available to them.

**Comment by Datseris** [comment]
I think you might be right.

**Comment by AayushSabharwal** [comment]
Looks like `fastest` doesn't allocate at all, as expected

**Comment by Datseris** [comment]
we don't need a `schedule!` function. We only need to make the schedulers function-like objects, as you have suggested in the past. They can have their own dedicated field for the id vector. And when you call them like functions, they can access this field.

**Comment by Datseris** [comment]
this way, schedulers that don't really need this non-allocating version, such as `fastest`, can just stay as they currently are, simple functions.
