### ISSUE TITLE
Better documentation of `test_map()`

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#587]
At the moment the ddocstring says:
"  Using this map requires network_type = :none to be passed as a keyword to OSMSpace."

But in the zombies example this is *not* done, and yet the example works. So is the statement true?

Also, can you please add what is the distance unit for the default map?

**Comment by AayushSabharwal** [comment]
> But in the zombies example this is not done, and yet the example works. So is the statement true?

Ah, I must have missed that. It's half-true. The `network_type` looks like it is a filter on the edges/nodes to include. If it's not provided, it uses the default filter which doesn't include all the edges. It still works, just on a subset of the edges.

> Also, can you please add what is the distance unit for the default map?

It's time, I'll add it to the docstring
