### ISSUE TITLE
`try` codeblock in `OSM.distance` is bad for performance

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#589]
https://github.com/JuliaDynamics/Agents.jl/blob/master/src/spaces/openstreetmap.jl#L431-L441

this really shouldn't be happening. It is bad design from the side of LightOSM.jl. If no path exists `nothing` should be returned, not an error. We should do a Pull Request at LightOSM.jl to fix that. Julia developers spend years making this optimization possible (that returning `nothing` is okay) so we should really use it.

**Comment by AayushSabharwal** [comment]
https://github.com/DeloitteDigitalAPAC/LightOSM.jl/issues/61

**Comment by Datseris** [comment]
After the update to LightOSM .2 we can now fix this, right? I see the source code of OSM still has a `try` keyword: https://github.com/JuliaDynamics/Agents.jl/blob/main/src/spaces/openstreetmap.jl#L414
