### ISSUE TITLE
Make space optional

### ISSUE THREAD

**Issue by kavir1698** [JuliaDynamics/Agents.jl#59]
Not all models have spatial structure. It would be better to default the space field  of the `ABM` function to `nothing`. Of course, none of the agent-space interaction functions will work when there is no space. But that is not an issue for a model that has no spatial structure.

**Comment by Datseris** [comment]
So, what can a user of Agents.jl do without a space?

**Comment by kavir1698** [comment]
When all the agents are in a single node, there is no point in creating a graph. The user benefits from all the functionality in `step!`, but will not use the agent-space interaction functions.

**Comment by Datseris** [comment]
Can you paste some example here? Like an actual example system? (At the moment there is no constrant in using `nothing` as a space, you just have to use the low level constructor)

**Comment by kavir1698** [comment]
See the Boltzmann wealth distribution in the `examples`. It is an agent based model without spatial structure.

**Comment by Datseris** [comment]
well okay then. Just allow `S` to be anything, instead of `<: AbstractSpace`, ad make it a keyword argument that defaults to `nothing`? 

(but then please add a comment in the documentation string that `nothing` means that all agents are just in one node and spatial structure does not matter)

**Comment by kavir1698** [comment]
Isn't it better to make it a union of `nothing` and `AbstractSpace`?

**Comment by kavir1698** [comment]
https://github.com/JuliaDynamics/Agents.jl/commit/5efa4991051782e0169870e53df3fdc4f4564a1b does this.
