### ISSUE TITLE
Rename `OSM.intersection` and `OSM.road`

### ISSUE THREAD

**Issue by AayushSabharwal** [JuliaDynamics/Agents.jl#593]
I realised the names are misnomers. They no longer return intersections/roads. What about `OSM.nearest_node` and `OSM.nearest_edge`?

**Comment by Datseris** [comment]
`OSM.nearest_edge` is also not true though, as it returns a location on an edge (while edge of a graph as a mathematical concept has no length). Nearest `road` may be better
