### ISSUE TITLE
heatmap is not updated with abm_video and abm_play

### ISSUE THREAD

**Issue by fwsq** [JuliaDynamics/Agents.jl#598]
Some simulations on the Agents.jl website are not working properly, is it a known problem ? If you look at Daisyworld or Forest fire you will see that heatmaps are not updated. Also the flocking simulation doesn't show up, but that's another problem. I think it comes from the polygons. When I replace them with points or other default markers in the given script, it works.

**Comment by Datseris** [comment]
Yeah, sorry about that, we are currently transitioning in a new interface for animations and plotting, and also releasing Agents.jl 5.0. There are some things not working at the moment but we will soon fix them!

**Comment by fwsq** [comment]
Awesome! Looking forward to seeing the 5.0!
