### ISSUE TITLE
Problem with: Schelling's segregation model

### ISSUE THREAD

**Issue by klangner** [JuliaDynamics/Agents.jl#599]
Hello,
I was trying to follow the tutorial and recreate the example: [Schelling's segregation model](https://juliadynamics.github.io/Agents.jl/stable/examples/schelling/#Schelling's-segregation-model-1)

But when I try to visualize data using the example code:
```julia
using InteractiveDynamics
using CairoMakie # choosing a plotting backend

groupcolor(a) = a.group == 1 ? :blue : :orange
groupmarker(a) = a.group == 1 ? :circle : :rect
figure, _ = abmplot(model; ac = groupcolor, am = groupmarker, as = 10)
figure # returning the figure displays it
```

I get the error:
```
PlotMethodError: no abmplot method for arguments (::AgentBasedModel{GridSpace{2, false}, SchellingAgent, typeof(Agents.Schedulers.randomly), Dict{Symbol, Int64}, MersenneTwister})
To support these arguments, define
  plot!(::Combined{InteractiveDynamics.abmplot, S} where S<:Tuple{AgentBasedModel{GridSpace{2, false}, SchellingAgent, typeof(Agents.Schedulers.randomly), Dict{Symbol, Int64}, MersenneTwister}})
```
It looks like I need to implement special version of the plot! function. But since there is no such function in the tutorial I was wandering if I'm missing something?

**Comment by Datseris** [comment]
hi there, yeap something seems wrong here. Can you please state your package versions, as was also requested by the issue template?

**Comment by klangner** [comment]
Ops, sorry. I thought it will be question not bug report.
Package version: 5.0.0
System: macos

**Comment by Datseris** [comment]
version of which package? what about InteractiveDynamics? Do note that the exact same thing is being built online without any problem: https://juliadynamics.github.io/Agents.jl/stable/examples/schelling/#Visualizing-the-data-1   which means that it is exceptionally likely that this is not an Agents.jl problem.

**Comment by klangner** [comment]
Yes, you are right. The problem was with InteractiveDynamics. I had version 0.18. After upgrading it to 0.20 it works.

Thank you for the help!
