### ISSUE TITLE
Some things should be more convenient

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#60]
At the moment the public API has some rough edges, expecting the user to do operations that I think should be quite simple to support generically. I am writing some examples here, but please feel free to edit this comment to add more.

# Adding agents
from the forest fire:
```julia
p = rand()
      if p ≤ forest.properties[:p]
        bigest_id = maximum(keys(forest.agents))
        treeid = bigest_id +1
        tree = Tree(treeid, (1,1), true)
        add_agent!(tree, node, forest)
      end
```
it seems that to add a new Agent the user should always try to find the `biggest_id` and add one. But in these 4 lines of code, what I want to do is just add one "alive" agent at the `node`. This should require only one line of code, not 4.

# Iterating through the nodes of the space
from forest fire:
```julia
 shuffled_nodes = Random.shuffle(1:gridsize(forest))
  for node in shuffled_nodes  # randomly go through the cells and
```
I don't think the user should do the first line, and should definitely not have to use the undocumented function `gridsize`. I think we should have some high level functions that iterate through nodes:

1. Randomly
2. Sequentially (by node ID)
3. By population; sort the nodes by the amount of agents they have, having the most populated first (this could be very useful for social models on arbitrary graphs)

# Empty nodes
We should define `isempty(node, model)` that returns internally checks `length(model.space.agent_positions[node]) == 0 `.

In general I do not find it great design if a user has to access a field of a field of a field and check if it is empty.

# Reexport `nv`, `ne` or define somefunctions that do that
It is useful to know how many grid points there are. and in the end of the day they are displayed when the model is printed. We should re-export `nv`, `ne` from LightGraphs.

**Comment by Datseris** [comment]
For solving the first, why dont we define
```julia
add_agent!(node::Int, model, properties...)
```
which internally creates creates the agent (we know its type from the model), calculates its ID, adjusts it, sets its position to `node`, and then adds the agent to the node? The `properties...` are propagated into the Agent constructor.

**Comment by kavir1698** [comment]
> add_agent!(node::Int, model, properties...)

This is a good idea and could be used frequently.

**Comment by kavir1698** [comment]
> should definitely not have to use the undocumented function gridsize.

It's a useful function. We should add some documentation to it.

> We should define isempty(node, model) 

All these helper functions are good, especially with easy to remember names.

**Comment by Datseris** [comment]
> It's a useful function. We should add some documentation to it.

I don;t think so. I think its name is just confusing. What's a grid size? Is it the amount of modes? Is i the amount of dimensions? Is it a tuple like `(20,20)`? I vote to completely remove it and use `nv` instead.

**Comment by kavir1698** [comment]
Ok I agree.
