### ISSUE TITLE
Highlight using GLMakie for an interactive abmplot()

### ISSUE THREAD

**Issue by xlxs4** [JuliaDynamics/Agents.jl#615]
In the [`Plotting and Interactivity`](https://juliadynamics.github.io/Agents.jl/stable/agents_visualizations/) documentation page, and more specifically, e.g. the section [`Interactive ABM Applications`](https://juliadynamics.github.io/Agents.jl/stable/agents_visualizations/#Interactive-ABM-Applications-1), it is mentioned how the static ABM plot can turn into an interactive app by simply passing the stepping functions as arguments to the `abmplot()` call:
> Continuing from the Daisyworld plots above, we can turn them into interactive interactive applications straightforwardly, simply by providing the stepping functions as illustrated in the documentation of [abmplot](https://juliadynamics.github.io/Agents.jl/stable/agents_visualizations/#InteractiveDynamics.abmplot).
```julia
fig, ax, abmobs = abmplot(model; agent_step! = daisy_step!, model_step! = daisyworld_step!,
    plotkwargs...)
fig
```
As you can see, the image generated is more akin to a static plot:
![image](https://user-images.githubusercontent.com/54778816/164111566-757e4ca2-b37d-47d0-ae75-a481e5e97576.png)

This is due to using the `CairoMakie` `Makie` backend, as seen in [`Static plotting of ABMs`](https://juliadynamics.github.io/Agents.jl/stable/agents_visualizations/#Static-plotting-of-ABMs-1). While this makes sense for an online documentation page, it wasn't clear to me that in order to actually produce said interactive app I must use the `GLMakie` backend instead. I'm using VSCode, and [here](https://discourse.julialang.org/t/the-vs-code-plot-navigator-and-makie/67967) is a discourse thread explaining that when the `CairoMakie` backend is used, the plot is rendered inside code's plot navigator, contrasted to using `GLMakie`, where you get that desired, separate `Makie` windowed app.

Would it make sense to add a little note in the respective documentation, clarifying that `GLMakie` has to be used instead in that use case, considering that a good chunk of Julia coders use VSCode as their editor/IDE of choice?

I can provide a MWE and some screenshots, if need be. Thanks!

**Comment by Datseris** [comment]
yes, sure, this sounds super simple to fix with a 1 line PR :)

**Comment by xlxs4** [comment]
Something like that?
