### ISSUE TITLE
issue with allagents/positions functions

### ISSUE THREAD

**Issue by askhari139** [JuliaDynamics/Agents.jl#621]
**Describe the bug**
I have a model setup where multiple agents are being created at some positions in the grid space. I want to identify such positions and keep only one agent at those positions. So I have written a function (see the code below) that gets all positions in the model, gets the agents at each position and removes additional agents if found. I am getting a weird error. Same error repeats if I use allagents function in place of positions. 

**Minimal Working Example**
```
using FileIO, JLD2, Agents
function multiAgent(model)
    pos = positions(model)
    multiPos = []
    for p in pos
        x = collect(agents_in_position(p, model))
        if length(x) > 1
            # for i in 2:length(x)
            #     kill_agent!(x[i], model)
            # end
            println(x.id)
        end
    end
    return multiPos
end

model = FileIO.load("modelVar.jld2","model") 
multiAgent(model)
```
[modelVar.jld2](https://drive.google.com/file/d/1vVZjuyijszLRXoYEXrq-ItME3hwQlZ8h/view?usp=sharing)

```
LoadError: KeyError: key 3313 not found
Stacktrace:
 [1] getindex
   @ .\dict.jl:482 [inlined]
 [2] getindex
   @ ~\.julia\packages\Agents\HGute\src\core\model.jl:110 [inlined]
 [3] #65
   @ .\none:0 [inlined]
 [4] iterate
   @ .\generator.jl:47 [inlined]
 [5] collect(itr::Base.Generator{Vector{Int64}, Agents.var"#65#66"{AgentBasedModel{GridSpace{2, true}, divisible, typeof(fastest), Dict{Symbol, Real}, MersenneTwister}}})
   @ Base .\array.jl:678
 [6] multiAgent(model::AgentBasedModel{GridSpace{2, true}, divisible, typeof(fastest), Dict{Symbol, Real}, MersenneTwister})
   @ Main ~\kill_agent_example.jl:5
 [7] top-level scope
   @ ~\kill_agent_example.jl:17
 [8] include(fname::String)
   @ Base.MainInclude .\client.jl:444
 [9] top-level scope
   @ REPL[113]:1
in expression starting at ~\kill_agent_example.jl:17
```

**Agents.jl version**

v4.5.6, Julia version 1.6.2

**Comment by Datseris** [comment]
`x` is a vector and you do `println(x.id)` ...?

**Comment by Datseris** [comment]
Also, please consider making an actual MWE where I don't have to download and load a file. Just 3 lines of code to make the most basic model should be enough.

**Comment by Datseris** [comment]
Also, please update to Agents 5.0+.
