### ISSUE TITLE
Simplest Schelling implementation about 2x as fast as our example

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#640]
Below I will attach two code snippets that create an ABM of the Schelling model. One is pure Julia, written in as simple possible way, and the other is in Agents.jl. As you will see, the pure/simple Julia version is about 2x fast. Before anyone gets too panicked: **it is completely expected that the pure version is faster**. Many reasons exist, the ones that come to mind immediatelly: 
1. simple version is actually a cellular automaton, so it utilizes a defacto knowledge of one agent per position (this gives many benefits such as much more efficient iteration over neighbors because of dropping nested `flatten` calls)
2. Due to the above, the simple version does not need the two extra fields of id and position in the agent struct.
3. simple version doesn't do generalized neighborhood searches, does a hardcoded Moore neighborhood.

Still, the pieces of code should be compared in detail. While it is true that we cannot expect to match the pure performance, we can ask: how close can we get? Which are the parts that actually differ more? 

(I haven't analyzed the codes in detail yet and just compared stepping. It is a todo to see in more detail which parts has the most performance difference. Is it finding neighbors? Is it moving agents?)

Here is the code:

```julia
using Random # reproducibility
# shared constants
const min_to_be_happy = 3 # how many nearby agents you need of same group
const grid_occupation = 0.8 # percentage of space occupied by agents
const grid_size = (30, 30)

######## PURE VERSION
# model is a dictionary, mapping filled positions (i, j) to agents
Random.seed!(1234)
mutable struct ExampleAgent
    group::Int
    happy::Bool
end

function initialize_pure()
    model = Dict{NTuple{2, Int}, ExampleAgent}()
    N = grid_size[1]*grid_size[2]*grid_occupation
    for n in 1:N
        group = n < N / 2 ? 1 : 2
        pos = (rand(1:grid_size[1]), rand(1:grid_size[2]))
        while haskey(model, pos)
            pos = (rand(1:grid_size[1]), rand(1:grid_size[2]))
        end
        agent = ExampleAgent(group, false)
        model[pos] = agent
    end
    return model
end

function simulation_step!(model)
    # crucial to collect keys here
    filled_positions = collect(keys(model))
    for pos in filled_positions # loop over all locations on grid
        agent = model[pos]
        same = 0
        neighboring_indices = [pos .+ n for n in neighborhood]
        for npos in neighboring_indices
            if !haskey(model, npos)
                continue
            end
            neighbor = model[npos]
            if neighbor.group == agent.group
                same += 1
            end
        end
        if same ≥ min_to_be_happy
            agent.happy = true
        else # generate new unoccupied position
            newpos = (rand(1:grid_size[1]), rand(1:grid_size[2]))
            while haskey(model, newpos) # careful here, use `newpos`, not `pos`!
                newpos = (rand(1:grid_size[1]), rand(1:grid_size[2]))
            end
            model[newpos] = agent
            delete!(model, pos)
        end
    end
end

model_pure = initialize_pure()
println("benchmarking pure step")
@btime simulation_step!($model)

######## AGENTS.JL VERSION
mutable struct SchellingAgent <: AbstractAgent
    id::Int
    pos::NTuple{2, Int} # Notice that position type depends on space-to-be-used
    group::Int
    happy::Bool
end

function initialize_agents()
    space = GridSpace(grid_size; periodic = false)
    properties = Dict(:min_to_be_happy => min_to_be_happy)
    rng = Random.Xoshiro(1234)
    model = ABM(SchellingAgent, space; properties, rng)
    N = grid_size[1]*grid_size[2]*grid_occupation
    for n in 1:N
        group = n < N / 2 ? 1 : 2
        agent = SchellingAgent(n, (1, 1), group, false)
        add_agent_single!(agent, model)
    end
    return model
end

function agent_step!(agent, model)
    nearby_same = 0
    for neighbor in nearby_agents(agent, model)
        if agent.group == neighbor.group
            nearby_same += 1
        end
    end
    if nearby_same ≥ model.min_to_be_happy
        agent.happy = true
    else
        move_agent_single!(agent, model)
    end
    return
end

model_agents = initialize_agents()
println("Benchmarking Agents.jl version")
@btime step!($model_agents, agent_step!)
```

with output
```
benchmarking pure step
  140.000 μs (721 allocations: 146.38 KiB)
Benchmarking Agents.jl version
  288.500 μs (5448 allocations: 255.38 KiB)
```

**Comment by AayushSabharwal** [comment]
I think it's probably worth tracking down where those allocations are happening, since GC time contributes heavily to overall runtime, and 5448 is a bit excessive. Off the top of my head, the following two possible culprits come to mind:
- pushing and popping to `space.s` in `move_agent_single!` 
- `Iterators.flatten` in `nearby_ids`

As you mentioned, there's also the fact that the simple implementation knows there's only one agent in a grid cell so it can use a simple dictionary for the space, and does faster nearest neighbour lookups. I think if this scenario of having at most one agent per grid cell is a common enough occurence in ABMs, we should consider adding a variant of `GridSpace` optimized specifically for this.

And following this train of thought, what if we have variants of `ABM`? Schelling doesn't need to kill agents, like many other models, so being able to store them as a `Vector` indexed by `id` instead of a `Dict` would be better.

**Comment by Datseris** [comment]
I agree on adding a variant of GridSpace with one agent per location. I thought the same as well. Although that's kind of already what DynamicGrids.jl does. Maybe we can use this backend somehow.

> Schelling doesn't need to kill agents, like many other models, so being able to store them as a Vector indexed by id instead of a Dict would be better.

Yes, that's another thing we should test out, I am not sure how much performance benefit this would have. `ABM` is modular as it is, so it would be straightforward to change the data structure that stores the agents without affecting the rest of the code.

I want to make the above code first divided into small functions so I can see whether adding or moving or finding neighbors is what takes up the most of the time. But I am so much swamped with other stuff at the moment :(

**Comment by AayushSabharwal** [comment]
I'll play around with this in some time and see what I can find.

> Although that's kind of already what DynamicGrids.jl does. Maybe we can use this backend somehow.

I haven't used DynamicGrids.jl much, but that does sound like a cool idea.

**Comment by AayushSabharwal** [comment]
I think a `StaticGridSpace` and `UnkillableAgentBasedModel` (names WIP :P) might be useful:

```julia
mutable struct Agent
    group::Int
    pos::Tuple{Int,Int}
end

struct Model
    agents::Vector{Agent}
    space::Matrix{Int}
end

function init_simple(grid_size = (30, 30), grid_occupation = 0.8)
    model = Model(Agent[], fill(0, grid_size...))
    N = floor(Int, grid_size[1] * grid_size[2] * grid_occupation * 0.5)

    for i in 1:2N
        grp = i <= N ? 1 : 2
        pos = (rand(1:grid_size[1]), rand(1:grid_size[2]))
        while model.space[pos...] > 0
            pos = (rand(1:grid_size[1]), rand(1:grid_size[2]))
        end

        push!(model.agents, Agent(grp, pos))
        model.space[pos...] = length(model.agents)
    end

    return model
end

const neighbors = [(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1)]
const min_to_be_happy = 3

function simulate!(model)
    for i in eachindex(model.agents)
        agent = model.agents[i]
        same_count = 0
        for offset in neighbors
            new_pos = agent.pos .+ offset
            if checkbounds(Bool, model.space, new_pos...) && model.space[new_pos...] == agent.group
                same_count += 1
            end
        end

        same_count >= min_to_be_happy && continue

        grid_dims = size(model.space)
        new_pos = (rand(1:grid_dims[1]), rand(1:grid_dims[2]))
        while model.space[new_pos...] > 0
            new_pos = (rand(1:grid_dims[1]), rand(1:grid_dims[2]))
        end
        model.space[agent.pos...] = 0
        agent.pos = new_pos
        model.space[agent.pos...] = i
    end
end
```

```julia
julia> model = init_simple()
julia> @benchmark simulate!($model)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  48.852 μs … 98.460 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     54.399 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   54.601 μs ±  2.265 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

                 ▁▄▅▇██▆▄▂▁                                    
  ▂▂▂▂▂▂▃▃▃▃▄▄▅▆▇███████████▆▆▄▄▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▂ ▃
  48.9 μs         Histogram: frequency by time        65.2 μs <

 Memory estimate: 0 bytes, allocs estimate: 0
```

**Comment by AayushSabharwal** [comment]
_All_ the allocations are in `move_agent_single!`

**Comment by Datseris** [comment]
The median is 54 microseconds in your example, but what about the other two cases? I bet you have different computer than mine so we can't compare :D In any case, it looks promising. I agree, we should go for the idea. I am still not sure how much gain we have from an "UnkillableABM", in terms of performance, but I guess we should try it. It is completely clear that a "StaticGridSpace" (bad name by the way!) has performance benefits. Quite large as well.

**Comment by AayushSabharwal** [comment]
>  I bet you have different computer than mine so we can't compare

Ah yes why didn't I think of that

> bad name by the way!

:P

**Comment by Datseris** [comment]
I had a different implementation with matrix as the space, where it was `Matrix{Union{Missing, Int}}` so that locations that didn't exist where `missing`, so that this didn't enforce ID 0 to be "no agent". But I never benchmarked it... However, we can consider doing this, enforcing users to only use positive IDs and non zero. On the other hand, if it isn't a big performance drawback to use `missing`, maybe we can go for that?

**Comment by AayushSabharwal** [comment]
I redid the benchmarks for this case:
Normally:
```julia
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  61.869 μs … 230.909 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     65.576 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   67.254 μs ±   7.264 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▂▅▇██▇▅▄▂▁                                                  ▂
  ▆████████████▇▇▆▆▆▆▃▅▆▆▇▇▇▇▇▇▇▇▇▇▇▅▆▆▅▆▅▅▆▆▆▅▅▄▄▄▃▅▅▆▄▆▅▄▄▄▆ █
  61.9 μs       Histogram: log(frequency) by time       105 μs <

 Memory estimate: 0 bytes, allocs estimate: 0.
```
With `@inbounds`:
```julia
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  53.604 μs … 217.269 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     57.581 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   58.846 μs ±   6.511 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▂▅▇██▆▄▂                                                   ▂
  ▃▅█████████▇▇▆▄▅▅▆▆▄▅▅▄▅▆▇▇▆▆▆▆▅▆▆▆▆▅▅▃▄▅▆▄▆▅▅▅▆▄▅▅▄▄▅▆▅▄▅▅▄ █
  53.6 μs       Histogram: log(frequency) by time      94.4 μs <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

It's a notable slowdown

**Comment by Datseris** [comment]
which is "this case"?

**Comment by AayushSabharwal** [comment]
Should've been more specific. I used `Union{Missing,Int}` for the space.

Additionally, `@code_warntype` does highlight type instabilities as a result.

**Comment by Datseris** [comment]
Okay, let's simply enforce positive integers. I am looking over your code and I am a bit confused. Where do you do the operation `found_id == 0` for skipping this position? I don't see it anywhere in
```julia
for offset in neighbors
            new_pos = agent.pos .+ offset
            if checkbounds(Bool, model.space, new_pos...) && model.space[new_pos...] == agent.group
                same_count += 1
            end
        end

```

**Comment by AayushSabharwal** [comment]
What's `found_id`?

**Comment by Datseris** [comment]
Ah yeah, you don't do it that way. I mean where do you check that `model.space[new_pos...]` is actually an agent? It could be an unoccupied position, i.e., ID zero.

**Comment by AayushSabharwal** [comment]
Ah, I see what you mean. I forgot to update the condition. My initial implementation simply had a `Matrix{Int}` for the `group` of each agent (0 for missing) but I realised that is a cellular automata not an ABM, so I refactored it into a vector of agents and a matrix for the space.

**Comment by Datseris** [comment]
Actually, now I am confused. You are benchmarking different things in your version. `model.space[new_pos...] == agent.group` is not what I was doing in my previous versions. Here it seems that your "model space" stores directly the groups of the schelling simulation. But of course this is too specific to the schelling model and we can't do it like that in a general framework.

**Comment by Datseris** [comment]
Okay, to clarify can you either post the new code or point to an updated comment that has the "agent based model" code instead of the "cellular automaton"?

**Comment by AayushSabharwal** [comment]
I'll update the code and benchmarks in this comment: https://github.com/JuliaDynamics/Agents.jl/issues/640#issuecomment-1166330815

**Comment by AayushSabharwal** [comment]
Updated. Turns out it's way faster, probably because previously every agent was unhappy.

**Comment by Datseris** [comment]
Okay, then we have to implement it. The only thing that worries me is that the current example is "the fastest possible way to make the schelling model", not really the fastest way to do it in a generic framework. It combines two approaches at the same time: both a "one-agent-per-position" space, and an UnkillableModel. But does not do so modularly. The way it checks for the absence of neighbors is by checking id > 0. 

Actually, perhaps its okay to have id = 0 mean NO agent **in general**. Because of countability, the positive integers can always be mapped to the whole integers. So I am happy to do this, but for starters it can only be on this new type of space. Furthermore, we can use `UInt8` now if we force all positive, so we get the same amount of "total" agents even though only positive IDs are allowed.

**Comment by Datseris** [comment]
But then again, maybe it is simpler to leave things at `Int` for coherence with the rest of the library... unlikely we can support a simulation with `typemax(Int)/2` total agents anyways :D

**Comment by Datseris** [comment]
@AayushSabharwal once again, I don't think your code is comparing / computing the same things. You do `same_count >= min_to_be_happy && continue`. Where do you keep track which agents are happy? Think of the data collection step. How would you collect timeseries of happines for each of the two groups?

**Comment by Datseris** [comment]
Okay, we need to get a bit organized here. Which means, writing some code and opening a pull request. Here are the actionable points I can imagine:

- There is no reason for us to do what DynamicGrids.jl is doing. So let's not waste too much energy and effort creating this combination of both "unkillable agents" and "one agent per position" all in the same time, without any modularity. The code in [this comment](https://github.com/JuliaDynamics/Agents.jl/issues/640#issuecomment-1166330815) has no modularity, it explicitly assumes that both of these clauses happen at the same time, and cannot work otherwise.
- A `GridSpace` with 1 agent per position is something to try for. It can explicitly use `0` as the id of missing agents. We are happy with that. This would remove the `flatten` calls and increase performance, we suspect.

I'll start a PR that implements such a space, and add scripts that compare to the existing implementations I posted originally. @AayushSabharwal you said you already benchamrked using `missing` for empty locations, and it was worse, so I won't do that.

**Comment by AayushSabharwal** [comment]
> . unlikely we can support a simulation with typemax(Int)/2 total agents anyways :D

Yeah. `UInt8` also gets annoying with having to convert types everywhere, and using `Int` allows people to change their space in effectively one line of code, instead of changing their agent struct, and anything that uses `id`.

> I don't think your code is comparing / computing the same things. You do same_count >= min_to_be_happy && continue. Where do you keep track which agents are happy? Think of the data collection step. How would you collect timeseries of happines for each of the two groups?

It doesn't explicitly store the count, because it's not needed for the simulation to function. I didn't actually think of the data collection, but it's a 2-line change at best and I doubt it would change the performance all that much.

> So let's not waste too much energy and effort creating this combination of both "unkillable agents" and "one agent per position" all in the same time, without any modularity.

I agree, it probably doesn't make sense.

> A GridSpace with 1 agent per position is something to try for. It can explicitly use 0 as the id of missing agents. We are happy with that. This would remove the flatten calls and increase performance, we suspect.

Apart from the flatten calls, it also improves memory locality.
