### ISSUE TITLE
Update InteractiveDynamics / CairoMakie dependency 

### ISSUE THREAD

**Issue by reyman** [JuliaDynamics/Agents.jl#646]
Hi,

Thanks for all your work,

Is it possible to update the `InteractiveDynamics` dependency () to latest that bump the Cairo Makie dependency ? 

Moving from v0.21.3 to v0.21.5 on InteractiveDynamics degrade Agents to v4.5.7

That solve lot of problems :)

Best regards

**Comment by Datseris** [comment]
> It seems there is some sort of dependency because when i update InteractiveDynamics to latest on github with Pka.add(url= ...github link...) => (to correct a bug), Agents.jl was downgraded to v4.x ...

Yeah but I am not sure how I can understand this, given that I am using InteractiveDynamics and Agents latest versions together right now as we speak. I think you can get a bit precise with these error reports and **show here the actual, full, report of what happens when you do Pkg.add, and exactly the status of the environment you do the add, before you add**. Vague descriptions of _approximately_ what you did are not useful to actually solve specific problems :D

And in fact, before that, you should try to do this in a clean environment where you only add Agents, InteractiveDynamics and then Cairo.

**Comment by reyman** [comment]
Ok i see, on a clean install on a docker env, using julia 1.6.6 i run : 

```
using Pkg
Pkg.update()
Pkg.add("CairoMakie")
```
return CairoMakie v0.8.8

Now adding InteractiveDynamics to the list : 
 
```
Pkg.add(url="https://github.com/JuliaDynamics/InteractiveDynamics.jl")
```

return 

```
  [13f3f980] CairoMakie v0.8.8
  [ec714cd0] InteractiveDynamics v0.21.5 `https://github.com/JuliaDynamics/InteractiveDynamics.jl#main`
```

Now adding `Pkg.add("Agents")` this is not the latest version : 

```
  [46ada45e] + Agents v4.5.7
```

Adding `Pkg.add("Makie")` 

```
  [46ada45e] Agents v4.5.7
  [13f3f980] CairoMakie v0.8.8
  [ec714cd0] InteractiveDynamics v0.21.5 `https://github.com/JuliaDynamics/InteractiveDynamics.jl#main`
  [ee78f7c6] Makie v0.17.8
```
**Now** restarting my environnement by `rm -r ~/.julia`

- Adding `Pkg.add("Agents")`

Install Agents v5.3.0 

Now i add InteractiveDynamics : 

- Adding `Pkg.add(url="https://github.com/JuliaDynamics/InteractiveDynamics.jl")`

return 

```
  [46ada45e] Agents v4.5.7
  [ec714cd0] InteractiveDynamics v0.21.5 `https://github.com/JuliaDynamics/InteractiveDynamics.jl#main`
```

So there is a downgrade of Agents v4.5.7 by getting the latest version of InteractiveDynamics from github.

**Comment by reyman** [comment]
> `Pkg.add(url="https://github.com/JuliaDynamics/InteractiveDynamics.jl")` ...? Why do you install this package this way? Can you please repeat exactly what you have done above, but now with `Pkg.add("InteractiveDynamics")`?

Because i need a recent version of InteractiveDynamics (v) that use a recent version of Makie/CairoMakie that correct bugs. 

If i install Pkg.add("InteractiveDynamics") : 

```
  [46ada45e] Agents v5.3.0
  [13f3f980] CairoMakie v0.7.5
  [ec714cd0] InteractiveDynamics v0.21.3
```

 CairoMakie is equal to v0.7.5, this is old if you look at my first install with Agents v4.xx that call CairoMakie v0.8.8 (latest available) that correct lot of things (a bug in heatmap drawing in my case).

**Comment by Datseris** [comment]
Ooooooooooh now I remember the problem. Yeah, you can only get latest stuff on Julia 1.7 or later. Sorry about that, I have forgotten that you can't get this in Julia 1.6, because one of the dependencies, specifically OSMMakie, does not work on Julia 1.6.

**Comment by Datseris** [comment]
Closing this as the only resolution to this issue is that you update to Julia 1.7, sorry if that is not possible for you, but nothing else I can do from my side.
