### ISSUE TITLE
`walk!` can be made generic and space agnostic with a simple normalizing function

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#654]
If we define a simple function `normalize_position(pos, space)` that takes in a position, and normalizes it so that it is appropriate for the space's extents, then the walk function becomes the trivial:
```julia
function walk!(agent, direction, model)
    newpos = agent.pos .+ direction
    newpos = normalize_position(newpos, model.space)
    move_agent!(agent, newpos, model)
end
```

and works for any space that defines `normalize_position`. Furthermore, it appears to me that we can reduce source code duplications by defining this `normalize_position` function. We should also make it part of the public api.

**Comment by Datseris** [comment]
(and yes, we would also need to have a check for `ifempty` by just using `isempty(newpos, model)` as a clause)

**Comment by AayushSabharwal** [comment]
I'm working on this in `fix_api`, possibly along with a couple other issues with unnecessary functions and API. On a related node, should `spacesize` also be made part of the public API? I think it would be useful to be able to get the size of a space without knowing the internals

**Comment by Datseris** [comment]
YES!!!

**Comment by Datseris** [comment]
can't beleive i didn't do this already in the 5.4 pR!

**Comment by AayushSabharwal** [comment]
Suppose `a=(1.3, 2.5)`, `b=(1.2, 2.3)`. So it turns out `clamp.(a, (zero(eltype(b)) for _ in 1:length(b)), b)` allocates because of generating the second argument (a tuple of zeros of the appropriate type and length). Is there a better way to do this?

**Comment by Datseris** [comment]
yes, use `map` ! In general prefer `map` when working with tuples, unless it is straightforward to do with broadcasting `.`

**Comment by AayushSabharwal** [comment]
That turns out to be slower by 3x if we cast the result to `Tuple`, but faster by 2x if we leave it as a `Vector`

**Comment by Datseris** [comment]
I am confused, what was initialy a `Vector` to begin with? Nothing should be a vector, everything is a tuple. Can we please move the suggestion to the PR and on specific code lines, so I can see where things become a vector to begin with?
