### ISSUE TITLE
Better API to access internals

### ISSUE THREAD

**Issue by AayushSabharwal** [JuliaDynamics/Agents.jl#657]
Along the lines of `spacesize`, I thought we should discuss the details that a user may want from our spaces/other structs, and create utility functions to retrieve this information. Not only does this prevent users from depending on struct fields that we don't document, it also allows us to modify the internals at will without breaking changes.

**Comment by Datseris** [comment]
`ids_in_position` exist, as well as `isempty`. I can't think of something else at the moment.

**Comment by AayushSabharwal** [comment]
Yeah, looks like it. I added the issue as a passing thought when I suggested `spacesize` be added to the public API, just in case we miss something.
