### ISSUE TITLE
node_neighbors(node_number::Integer, model::ABM, radius::Integer) is unclear

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#66]
The documentation
```
 Returns a list of neighboring nodes to the node node_number within the radius.
```
is unclear. What does the radius mean?

**Comment by kavir1698** [comment]
radius defines higher degree neighbors. E.g, neighbors with a radius=2 include first and second degree neighbors, that is, neighbors and neighbors of neighbors.

**Comment by Datseris** [comment]
Okay, simple enough but should be said in the docstring.

**Comment by kavir1698** [comment]
https://github.com/JuliaDynamics/Agents.jl/commit/cead67c72c2a3c98e1f2d30f3a5fbf1cfa401c49
