### ISSUE TITLE
"Edit on github" button not working

### ISSUE THREAD

**Issue by franfram** [JuliaDynamics/Agents.jl#666]
The "edit on github" button on the website https://juliadynamics.github.io/Agents.jl/stable/agents_visualizations/ isn't working. 
after clicking on it, I get:
![image](https://user-images.githubusercontent.com/18502770/181828963-85ab201d-36a3-4e8b-8b84-5dbdeb1908f7.png)

**Comment by Tortar** [comment]
this problem should be solved in latest main
