### ISSUE TITLE
The social distancing model does not look like elastic collision

### ISSUE THREAD

**Issue by sosiristseng** [JuliaDynamics/Agents.jl#675]
https://juliadynamics.github.io/AgentsExampleZoo.jl/dev/examples/social_distancing/

It seems the balls are going faster and faster.

**Comment by Datseris** [comment]
(fyi @sosiristseng I've transferred the issue to Agents.jl as this seems to be a problem with the source code)

**Comment by sosiristseng** [comment]
I compared the old code to the new one. It seems that this line
https://github.com/JuliaDynamics/Agents.jl/blob/83129042f01673f832e4a32de53b93ecd6af80ab/src/spaces/continuous.jl#L349

should be

```diff
- b.vel = v2 .- f2 .* (dot(dv, r2) / n) .* (r2)
+ b.vel = v2 .+ f2 .* (dot(dv, r2) / n) .* (r2) 
```

because the signs were opposite for velocities of a and b.

**Comment by Datseris** [comment]
Thank you very much, would you like to open a PR for this?

**Comment by sosiristseng** [comment]
Yes, please see #676
