### ISSUE TITLE
nearby_ids output changes with translated positions; wrong output

### ISSUE THREAD

**Issue by hbsmith** [JuliaDynamics/Agents.jl#684]
**Describe the bug**
`nearby_ids` and `nearby_ids_exact` produce incorrect output in some situations, although I can't figure out what triggers it

**Minimal Working Example**
```julia
using Revise
using Agents, Plots, Random
using Test

mutable struct TestAgent <: AbstractAgent
    id::Int
    pos::NTuple{2,Float64}
end

distance(a1::TestAgent,a2::TestAgent) = let δ = a1.pos .- a2.pos
  hypot(δ...)
end
  
positions = [
  (122.91984594569145, 129.27537099976024),
  (119.8316511853557, 120.63347075797228),
  (120.88133497820543, 122.44001918308183),
  (118.33581146746528, 121.94704974817539),
  (120.22776179237353, 121.74193334411757)]

space = ContinuousSpace((300,300),periodic=true)
model = ABM(TestAgent, space)

for i in positions
  add_agent!(i,model)
end
```
Now looking at the calculated distances between agents compared to the what is returned by `Agents.nearby_ids` and `Agents.nearby_ids_exact`
```julia

julia> for a in 1:4
  d = distance(model[5],model[a])
  println("Distance between 5 and $a: $d")
end

Distance between 5 and 1: 8.000000000000027
Distance between 5 and 2: 1.1771121093064787
Distance between 5 and 3: 0.9562853903521156
Distance between 5 and 4: 1.9030367235379475

julia> collect(Agents.nearby_ids_exact(model[5],model,2))
1-element Vector{Int64}:
 3
## Expecting this to be [2, 3, 4]

julia> collect(Agents.nearby_ids(model[5],model,2))
2-element Vector{Int64}:
 1
 3
## Expecting this to be [2, 3, 4] (or [1, 2, 3, 4] based on the ContinuousSpace docstring)
```

Changing to `periodic=false` gives the same results.

But sometimes translating the positions gives the expected answer...
```julia
positions = [i .- 100 for i in positions]

## Rerun initialization

julia> for a in 1:4
  d = distance(model[5],model[a])
  println("Distance between 5 and $a: $d")
end

Distance between 5 and 1: 8.000000000000027
Distance between 5 and 2: 1.1771121093064787
Distance between 5 and 3: 0.9562853903521156
Distance between 5 and 4: 1.9030367235379475

julia> collect(Agents.nearby_ids_exact(model[5], model, 2))
3-element Vector{Int64}:
 2
 3
 4

julia> collect(Agents.nearby_ids(model[5], model, 2))
4-element Vector{Int64}:
 1
 2
 3
 4
```

Or is this how this is supposed to work, and me just not understanding what's going on under the hood with the grid system? 

**Agents.jl version**
5.4.3

**Comment by Datseris** [comment]
bu hu hu this seems like a bug to me... I need to run the code and check it out in detail. bu hu hu i cry.

**Comment by Datseris** [comment]
It may be as simple as increasing slightly the arbitrary scaling constant I've devised with a bit of circle geometry and lots of hocus pocus on "how large it should be".

**Comment by hbsmith** [comment]
What scaling constant are you talking about? 

For the `exact` version, mightn't it better to just calculate the euclidean distances directly without first having to invoke any hocus-pocus, if the user is intentionally focusing on reliability over speed anyways?

**Comment by Datseris** [comment]
well, _which_ euclidean distances? There are internal compartments that have the agents to accelerate the search. You first have to find which cells to include in the search...

**Comment by Datseris** [comment]
https://github.com/JuliaDynamics/Agents.jl/blob/main/src/spaces/continuous.jl#L200-L201

For the exact: https://github.com/JuliaDynamics/Agents.jl/blob/main/src/spaces/continuous.jl#L200-L201


it may be that the `r` isn't high enough and has to increase...

**Comment by hbsmith** [comment]
Now that I've been staring at the source code and trying to make sure I understand the geometry, I think the fix should be as simple as L201 becoming:
`grid_r = (r + δ) / (model.space.spacing/2)`
Because you're trying to convert to units of grid cell _radii_, which is what `offset_within_radius` expects, not units of grid cell length, which is what it's converting to now.

**Comment by hbsmith** [comment]
This only breaks one current test--one I wrote a long time ago: https://github.com/JuliaDynamics/Agents.jl/blob/255b300e580cbe4d0ec1f0a1add4ee81e6522ba7/test/continuous_space_tests.jl#L218
The reason it breaks is because there are 2 agents tied for nearest neighbor, and it only returns one of them. With this update, and the way that `nearby_ids` works, it's now returning the other one it didn't return before. 

Two thoughts come out of this (can open to separate issues if they warrant enough discussion):
1. How should `nearest_neighbor` choose which neighbor is chosen in the event of a tie? (I think we should just return all that are equal)
2. If `periodic==true`, `nearby_ids` can end up returning the same IDs many times if the radius is big enough. I guess I can think of weird edge cases where the user might want this? But most of the time it seems kind of confusing/unnecessary. Should we just return unique values?

**Comment by Datseris** [comment]
Can you please open a PR with your fix that alters the test accordingly as well?

Answers:

1. No, `nearest_neighbor` must return only one neighbor. That's the function definition. We don't care what happens in turns of tie, I guess random chance of the order of agents in the dictionary would give 50% one or the other.
2. Unfortunately not. Unique is a very expensive operation. We can't do anything here for performance reasons. There was another issue where another user pointed this out. The solution was to just state in the docstring that in cases of periodic continuous space and very large radii agents will be included several times. At least, that was my decision: to not sacrifice performance to fix the edge case, because the overwhelming majority of users don't really have reason to use `nearby_ids` with radius more than half the space. The original issue: https://github.com/JuliaDynamics/Agents.jl/issues/566

**Comment by hbsmith** [comment]
1. Of course you don't want a breaking change, but with the way the function is written right now, there wouldn't be any performance cost to allowing an optional argument like `find_ties`, and just keep a vector of closest agents. Then if the user wanted ties, they would just get a vector of agents instead of an agent. If you don't like changing output type based on an arg, then there's no downside to making a new function that keeps ties, and have `nearest_neighbor` call that and return the first element of that vector. 

2. Ok, good to know

Re: PR--I wrote some tests, and `nearby_ids_exact` is working fine. But `nearby_ids` isn't giving me the output I would expect based on my understanding of `Agents.offsets_within_radius`, so maybe you can explain.

Shouldn't I be able to visualize `Agents.offsets_within_radius` as basically telling me which grid spaces overlap with a circle of radius r (where r=spacing/2), when that circle's origin is in the center of a grid cell? [(see digram)](https://imgur.com/a/W2CcJZN)

If that understanding is correct, then I don't understand the below pattern of outputs.

```
julia> Agents.offsets_within_radius(space2d.grid,.99)
1-element Vector{Tuple{Int64, Int64}}:
 (0, 0) 
# good, the circle fits entirely within one cell

julia> Agents.offsets_within_radius(space2d.grid,1)
5-element Vector{Tuple{Int64, Int64}}:
 (0, -1)
 (-1, 0)
 (0, 0)
 (1, 0)
 (0, 1) 
# good, the circle is tangent to 4 other cells

julia> Agents.offsets_within_radius(space2d.grid,sqrt(2)-.01)
5-element Vector{Tuple{Int64, Int64}}:
 (0, -1)
 (-1, 0)
 (0, 0)
 (1, 0)
 (0, 1) 
# good, the circle still only overlaps with 5 cells

julia> Agents.offsets_within_radius(space2d.grid,sqrt(2))
9-element Vector{Tuple{Int64, Int64}}:
 (-1, -1)
 (0, -1)
 (1, -1)
 (-1, 0)
 (0, 0)
 (1, 0)
 (-1, 1)
 (0, 1)
 (1, 1) 
# good, the circle is tangent to 4 corner cells, and overlaps with 5 of them

julia> Agents.offsets_within_radius(space2d.grid,2)
13-element Vector{Tuple{Int64, Int64}}:
 (0, -2)
 (-1, -1)
 (0, -1)
 (1, -1)
 (-2, 0)
 (-1, 0)
 (0, 0)
 (1, 0)
 (2, 0)
 (-1, 1)
 (0, 1)
 (1, 1)
 (0, 2) 
# Now I'm confused, if 2 is in units of (spacing/2), why doesn't this return the same thing as Agents.offsets_within_radius(space2d.grid,sqrt(2))
```

**Comment by Datseris** [comment]
> there wouldn't be any performance cost to allowing an optional argument like find_ties, and just keep a vector of closest agents

The current function doesn't even make a vector, so this definitely comes at a performance cost. 

> Then if the user wanted ties, they would just get a vector of agents instead of an agent

That's type unstable.

> then there's no downside to making a new function that keeps ties, and have nearest_neighbor call that and return the first element of that vector.

There are **several downsides**, 1) the performance of `nearest_neighbor` will drop massively due to the vector allocation and 2) we have to write, test, and document one more exported API function.

If you really need this functionality, perhaps start by writing an implementation for it so that we see how it performs.

---

For the second part: there is extensive plotting code here: https://github.com/JuliaDynamics/Agents.jl/blob/main/test/continuous_space_tests.jl#L339 I've used it to test the functionality a lot. I knew it wasn't perfect, but I had to strike a balance between performance and accuracy. 

---

I've saved this issue on my TODOs, at the moment I am short on time to add more. Will come back in the future!

**Comment by hbsmith** [comment]
Thanks for sharing the location of the plotting code. Not sure how much time I'll have to dig deeper into this issue soon, so I'll probably hold off until you have some more time to look over what I've brought up so far.

**Comment by Tortar** [comment]
I ran the code in the first comment and now the problem seems fixed, the code returns the expected outputs

**Comment by Tortar** [comment]
Do you still see the problem @hbsmith ? :-)
