### ISSUE TITLE
Predator-prey(Wolf,Sheep, Grass) dynamics example not working without correct walk! function 

### ISSUE THREAD

**Issue by mrchaos** [JuliaDynamics/Agents.jl#689]
The basic operation of the `walk!(wolf, rand, model)` function is that if there is a sheep or a wolf in the position to be moved, it does not move. So even if there are sheep where the wolf is trying to move, they can't move, so they can't eat the sheep, so they starve to death.
A way to solve this is to use `walk!(sheep, rand, model)` for sheep and `walk!(wolf, direction, model;ifempty=false)` for wolfs.

Another method is not to move if there is an agent of the same type in the location to be moved.
If there are different kinds of agents, it is to make it possible to move them. The `walk2!` below is the solution.
```
function walk2!(agent::A, model) where {A<:AbstractAgent}           
    direction = Tuple(rand(model.rng, -1:1, 2))    
    target = normalize_position(agent.pos .+ direction, model)    
   
    ids = ids_in_position(target, model)
    
    j = findfirst(id -> model[id] isa A, ids)
    
    isnothing(j) && move_agent!(agent, target, model)
end
```

The gridspace size was also increased to (50,50), the number of sheep and wolfs was increased to 50,100, respectively, and the energy of the wolfs was increased to 30, and it worked well.

See the link below for more details.

https://julialang.kr/?p=3700

**Comment by Datseris** [comment]
We solved this, right?
