### ISSUE TITLE
Simplify `position_delta` function for periodic

### ISSUE THREAD

**Issue by mrchaos** [JuliaDynamics/Agents.jl#695]
Below is the current `position delta` function for periodic.
```
position_delta(pathfinder::GridPathfinder{D,true}, from::Dims{D}, to::Dims{D}) where {D} =
    min.(abs.(to .- from), size(pathfinder.walkmap) .- abs.(to .- from))
    
```

I suggest a simpler and more clear code.
Suggested code below
```
position_delta(pathfinder::GridPathfinder{D,true}, from::Dims{D}, to::Dims{D}) where {D} =
    mod1.(abs.(to .- from), size(pathfinder.walkmap))
```

And the above suggested code referenced `mod1.(n .+ pos, space_size)` of `nearby_positions` of `grid_general.jl`.
```
function nearby_positions(
        pos::ValidPos, space::AbstractGridSpace{D,true}, r = 1,
        get_indices_f = offsets_within_radius_no_0 # NOT PUBLIC API! For `ContinuousSpace`.
    ) where {D}
    nindices = get_indices_f(space, r)
    space_size = size(space)
    return (mod1.(n .+ pos, space_size) for n in nindices)
end
```

And judge by looking at the results of both functions. Why are the two results different?

![image](https://user-images.githubusercontent.com/5639226/199292365-45c0ff45-ca0c-4973-a53c-08b7d19336a3.png)

[related PR link]( https://github.com/JuliaDynamics/Agents.jl/pull/692)

**Comment by Datseris** [comment]
the results are different because the functions do different operations. ?

**Comment by fbanning** [comment]
Since #692 was closed after discussion, I think it's safe to assume that this issue can also be closed? If that's not the case, please feel free to reopen it.
