### ISSUE TITLE
`paramscan` doesn't support a terminating function `n::Function`

### ISSUE THREAD

**Issue by saumil-sh** [JuliaDynamics/Agents.jl#706]
**Describe the bug**
The `paramscan` documentation mentions
> Furthermore, `agent_step!`, `model_step!`, `n` are also keywords here, that are given to [`run!`](https://juliadynamics.github.io/Agents.jl/stable/tutorial/#Agents.run!) as arguments.

  This leads me to believe that since `run!` supports a function as `n`, `paramscan` will too. However there is only one definition with `n::Int` in the [source](https://github.com/JuliaDynamics/Agents.jl/blob/be647b8d5ab9ad2c1b5ca91bcacfcfdb80a72366/src/simulations/paramscan.jl#L75)

**Minimal Working Example**

```julia
]st Agents
```
```
 Status `/Volumes/shah/projects/glioblastoma/Project.toml`
[46ada45e] Agents v5.6.1 `~/.julia/dev/Agents`
```

```julia
using Random
using Agents
```

```julia
@agent myAgent NoSpaceAgent begin
end
```

```julia
function init(;seed=42)
    model = ABM(myAgent, nothing; rng=Random.MersenneTwister(seed))
    add_agent!(model)
    return model
end

function agent_step!(agent, model)
    return dummystep
end
```
```
    agent_step! (generic function with 1 method)
```

```julia
parameters = Dict(:seed => collect(rand(UInt8, 5)))
adf, mdf = paramscan(parameters, init; agent_step!, n=3,adata=[])
```
works as expected :)

```julia
function terminate(model, s)
    return s > 3
end
```
```
    terminate (generic function with 1 method)
```

```julia
adf, mdf = paramscan(parameters, init; agent_step!, n=terminate,adata=[])
```
```
    TypeError: in keyword argument n, expected Int64, got a value of type typeof(terminate)
```

**Suggested solution**
I can add a new function definition that would accept `n::Function` and pas it to `run!`

EDIT: added a bold heading.

**Comment by fbanning** [comment]
Closed by #707
