### ISSUE TITLE
How to deal with parametric types and subtyping?

### ISSUE THREAD

**Issue by mastrof** [JuliaDynamics/Agents.jl#725]
I need to define a number of agent types that can be used in principle for any value of a parameter `D` which sets the dimensionality of the agent (in practice `D` is usually to limited to 1, 2 and 3).
They all share some fields and each has fields of its own, all of which are independent of `D`.
`D` only sets the dimensionality (`pos` and `vel` fields for a `ContinuousAgent{D}`).

The stepping is composed of two stages, one that is identical for all agents, but depends on `D` (i.e. I need to dispatch on `D`), and another one that is specialised on the particular agent type (this second step can be `D`-agnostic but I don't think it matters).
So what I thought is that I need to have an abstract parametric type which supertypes all the (parametric) subtypes.

A minimal example if I didn't know about the `@agents` macro would be something like the following
```julia
abstract type AbstractFoo{D} <: AbstractAgent where D end

mutable struct Foo1{D} <: AbstractFoo{D}
    id::Int
    pos::NTuple{D,Float64}
    vel::NTuple{D,Float64}
    a
    b1
end

mutable struct Foo2{D} <: AbstractFoo{D}
    id::Int
    pos::NTuple{D,Float64}
    vel::NTuple{D,Float64}
    a
    b2
    c2
end

mutable struct Foo3{D} <: AbstractFoo{D}
    id::Int
    pos::NTuple{D,Float64}
    vel::NTuple{D,Float64}
    a
    b3
    c3
    d3
end
```
and the stepping would go like
```
function agent_step!(agent, model)
    step_1!(agent, model) # depends on D but not on particular subtype
    step_2!(agent, model) # depends on particular subtype but not on D
end

step_1!(agent::AbstractFoo{1}, model) = #= do something =# return;
step_1!(agent::AbstractFoo{2}, model) = #= do something =# return;
step_1!(agent::AbstractFoo{3}, model) = #= do something =# return;
#= ... =#
step_2!(agent::Foo1, model) = #= do something =# return;
step_2!(agent::Foo2, model) = #= do something =# return;
step_2!(agent::Foo3, model) = #= do something =# return;
```

Now this works, and although there is some boilerplate with all the repeat `id`, `pos`, `vel` and other shared fields, I could be happy with it.

However, it is stated that the `@agent` macro is the only supported way to create agent types.
Using the macro would conveniently allow me to define common traits `CommonFoo` that can be inherited by all the subtypes, and also allow me / other users to quickly extend the `Foo` types by building on these common traits.
But I fail to see how to recreate this same setup with the macro, which does not allow parametric types.

Is this just bad design on my side? A fundamental limitation of the macro and I should just stick with defining the types by hand? Or am I just missing something?

**Comment by AayushSabharwal** [comment]
This is... interesting.

For now, you could probably get around this by defining
```julia
const AbstractFoo{D} = Union{Foo1{D},Foo2{D},Foo3{D}}
```

I guess this can get tedious for more agent types, but multi-agent models are also not great for performance, so I'm not sure if it's something worth explicitly supporting.

**Comment by mastrof** [comment]
> but multi-agent models are also not great for performance, so I'm not sure if it's something worth explicitly supporting
Convenient integration of multi-agent models is indeed one application of this, but my question was really more about how to "properly" design such an interface.
That is, I can have a library that exports various agents with defined steppers, then you can just initialize the model (with only one agent type or many of them) and run it without having to deal with the fact that each of these agent has a different stepper.

**Comment by AayushSabharwal** [comment]
I think the `Union` method is really the only way for now. It's likely possible to modify the macro so it accepts a different abstract supertype, but I'm not sure how that works in the first place. If you have an idea for how to implement it, please feel free to PR.

**Comment by mastrof** [comment]
I'm still at a stage where metaprogramming feels like witchcraft so can't really help.
Just wanted to put the problem out there for the moment

**Comment by mastrof** [comment]
> in any case, now that `@agent` supports `const` and keywords, it must be established as THE and ONLY way to make agents in Agents.jl

_Originally posted by @Datseris in https://github.com/JuliaDynamics/Agents.jl/issues/835#issuecomment-1646523305_

I know this PR has already been merged (and that's great indeed) but I want to argue (in relation to this post I made some time ago) that the `@agent` macro is not yet ready to be claimed as the only way to make agents.
It works well in "simple" scenarios but makes it impossible to create an _extensible_ interface based on parametric types.

I have a step function defined for an `AbstractFoo{D} <: AbstractAgent` supertype, which depend on the parameter `D`.
Having an abstract supertype means that I can define behavior that must be shared across all its subtypes, and you, user, only need to include eventual extra behavior that you want on top of it. But there is no way to subtype `AbstractFoo{D}` using `@agent`.

The workaround of using a `Union` to create the "supertype" after defining the agent types
> ```julia
> const AbstractFoo{D} = Union{Foo1{D},Foo2{D},Foo3{D}}
> ```
can only work if the set of subtypes is finite and non extensible, which is not what I need here.

Even if I make my own version of the `@agent` macro to override the default subtyping to `AbstractAgent`, I still cannot find a way to subtype a parametric type.
I'm definitely a beginner in metaprogramming world but I think the problem is that this line
https://github.com/JuliaDynamics/Agents.jl/blob/3ac17b88f3cca4c73a008f9303ce943c29ca64b5/src/core/agents.jl#L233C1-L233C67
cannot handle parameters.

**Comment by Datseris** [comment]
Can you explain what is the problem with doing `const AbstractFoo{D} = Union{Foo1{D},Foo2{D},Foo3{D}}`?

**Comment by Datseris** [comment]
I also don't understand your problem with `@agent`, as it allows you to do anyways what you would be able to do with the normal usage of `mutable struct`. 

What is it that you can do with `mutable struct` and not with `@agent` at the moment? It allows you to use arbitrary super types instead of `AbstractAgent`.

**Comment by Datseris** [comment]
> I still cannot find a way to subtype a parametric type.

Of course you can, first define the abstract parameteric type and then use it as 4th argument in the macro:

```julia
@agent YourAgentType{X} AnotherAgentType [OptionalSupertype] begin
```

put it in `[OptionalSupertype]`.

**Comment by mastrof** [comment]
This is specifically relevant for a package I'm developing, MicrobeAgents.jl, which aims to provide a unified interface for agent-based simulations of bacterial behavior.
No need to go look into it, but you can think of it as there being different "species" (in a very broad sense) of bacteria.
On one side, I don't care about the species, because their motion will be integrated the exact same way.
On the other there are internal states, unique to each species, which need to be integrated in different ways.

Now, the "problem": there are hundreds of existing models to represent certain sets of behaviors. What I want is to allow users to write their own favorite model of such internal states (or define their own), and just plug it on top of the existing base behavior.

Using the `const` trick in the package would avoid users to tap into the existing behaviors when creating new types.

Using a plain mutable struct is still a huge pain because everytime anyone wants to implement their own model. they would need to copy-paste the fields from the base type, basically rewriting the struct from scratch, hence tons of boilerplate... (And it's what I'm doing now...)


```julia
@agent YourAgentType{X} AnotherAgentType [OptionalSupertype] begin
```
On Agents#main, this is not working if the supertype is parametric (or I'm an idiot, which honestly might be...)

**Comment by Datseris** [comment]
> On Agents#main, this is not working if the supertype is parametric (or I'm an idiot, which honestly might be...)

Can you post a MWE? This sounds like a fixable bug that would also solve your problem.

> Using a plain mutable struct is still a huge pain because everytime anyone wants to implement their own model. they would need to copy-paste the fields from the base type, basically rewriting the struct from scratch, hence tons of boilerplate... (And it's what I'm doing now...)

This argues that you should be using `@agent` instead, right?

**Comment by mastrof** [comment]
Ah yes sure, I was totally not arguing against the use of `@agent`, I would love to be able to use it as intended, just it was not yet working for my use case.

Here some attempts I made with the parametric subtype. Maybe I am not using the right syntax but I tried quite some variations... `MyFoo1` and `MyFoo2` are there to confirm everything goes as expected if the supertype is not parametric.
```julia
julia> abstract type AbstractFoo{D} <: AbstractAgent where D end

julia> abstract type AbstractFooNonPar <: AbstractAgent end

julia> @agent MyFoo1{D} ContinuousAgent{D} where D begin; end

julia> @agent MyFoo2{D} ContinuousAgent{D} where D AbstractFooNonPar begin; end

julia> @agent MyFoo3{D} ContinuousAgent{D} where D AbstractFoo{T} where T begin; end
ERROR: invalid subtyping in definition of MyFoo3: can only subtype data types.
Stacktrace:
 [1] macro expansion
   @ util.jl:589 [inlined]
 [2] top-level scope
   @ ~/.julia/packages/Agents/Q6jIy/src/core/agents.jl:233
 [3] eval(m::Module, e::Any)
   @ Core ./boot.jl:370
 [4] top-level scope
   @ ~/.julia/packages/Agents/Q6jIy/src/core/agents.jl:240

julia> @agent MyFoo3 ContinuousAgent{2} AbstractFoo begin; end
ERROR: invalid subtyping in definition of MyFoo3: can only subtype data types.
Stacktrace:
 [1] macro expansion
   @ util.jl:589 [inlined]
 [2] top-level scope
   @ ~/.julia/packages/Agents/Q6jIy/src/core/agents.jl:233
 [3] eval(m::Module, e::Any)
   @ Core ./boot.jl:370
 [4] top-level scope
   @ ~/.julia/packages/Agents/Q6jIy/src/core/agents.jl:240

julia> @agent MyFoo3 ContinuousAgent{D} where D AbstractFoo{D} where D begin; end
ERROR: invalid subtyping in definition of MyFoo3: can only subtype data types.
Stacktrace:
 [1] macro expansion
   @ util.jl:589 [inlined]
 [2] top-level scope
   @ ~/.julia/packages/Agents/Q6jIy/src/core/agents.jl:233
 [3] eval(m::Module, e::Any)
   @ Core ./boot.jl:370
 [4] top-level scope
   @ ~/.julia/packages/Agents/Q6jIy/src/core/agents.jl:240
```

**Comment by Datseris** [comment]
why do you do `where {D}`? There is no `where` in type definitions.

What does 
```julia
@agent MyFoo3{D} ContinuousAgent{D} AbstractFoo{D} begin; end
```
do?

**Comment by mastrof** [comment]
`D` not defined (even without the optional supertype)

**Comment by Datseris** [comment]
@Tortar any chance we can make 
```julia
@agent MyFoo3{D} ContinuousAgent{D} AbstractFoo{D} begin; end
```
work?

**Comment by Tortar** [comment]
thanks @mastrof to point out (again) this flaw of the agents macro, this seems a really important one to me, I will let you know the result of my investigation on this: for what I understand though the method with `where D` seems more promising (because it compiles while without it, it throws a `D` is not defined which seems impossible to circumvent). I think that one of the version you mentioned should hopefully work (in the end) though !
