### ISSUE TITLE
allow `const` syntax in the `@agent` macro

### ISSUE THREAD

**Issue by thevolatilebit** [JuliaDynamics/Agents.jl#728]
I use a variant of Agents.jl `@agent` macro in [AlgebraicAgents.jl](https://github.com/Merck/AlgebraicAgents.jl). @slwu89 recently suggested to me the following idea ([issue 4, AlgebraicAgents.jl](https://github.com/Merck/AlgebraicAgents.jl/issues/4)) which clearly applies also to Agents.jl:

*Any agent type being made from calling `@agent` is mutable, but with Julia versions >= 1.8 now we can specify particular fields as being const, which can help bring performance closer to immutable structs (see https://docs.julialang.org/en/v1/manual/types/#Mutable-Composite-Types). It would be nice to let users to specify fields as const if they like, to improve performance.*

To the best of my knowledge, `@agent` macro syntax is not compatible with `const field` declarations - at least I have been getting some parsing errors, as we need the `struct` wrap.

As a workaround, I proposed that the syntax of `@agent` could change to the following:

```julia
@agent AnotherAgentType [OptionalSupertype] struct YourAgentType{X}
        extra_property::X
        other_extra_property::Int
        const immutable_property::X
        # etc...
end
```

You may review a candidate implementation [there](https://github.com/Merck/AlgebraicAgents.jl/blob/8b7d05a462cd1ee8303fecbf77f01e7fa13b7d07/src/agent_macros.jl#L8).

Would it be possible to achieve the same functionality without the change of syntax?

**Comment by Datseris** [comment]
Hm, unfortunately this syntax is a breaking change. But maybe there is a simple way to modify `@agent` so that it can parse `const` the way it is now. (I dont know this way at the moment). Have you asked for help in discourse? 

Allow the `cost` decleration is definitely desirable

**Comment by thevolatilebit** [comment]
So far I asked in slack - the suggestion was to look at `Base.@kwdef`, which uses the `struct` syntax, so this does not really apply here. I will ask on discourse as well.

**Comment by thevolatilebit** [comment]
https://discourse.julialang.org/t/const-syntax-outside-of-struct/93173

**Comment by fbanning** [comment]
This would indeed be very nice. Also to be able to use `Base.@kwdef` (see #709) would be great. If we start to work on (or possibly rewrite) the `@agent` macro, then we should consider implementing that at the same time.

**Comment by Datseris** [comment]
I've thought about this a lot and I think I will revert the decision of `@agent` macro being the only way to make agent types, and allow types to be made also directly by the users. Instead `@agent` macro will be _the recommended_ way. At the moment there are some problems with `@agent` we do not know how to resolve. If in the future they are resolved, then we can enforce its usage, but for now, it is better to relax it I guess.

**Comment by Tortar** [comment]
And with #831 we have a sort of solution also for this one:

use something like 

```
@agent A NoSpaceAgent begin
           f1::Int = 40
           f2::Int
           constants = f1, f2
       end
```

and rework a little the macro, no breaking changes

**Comment by Tortar** [comment]
Actually I think the decision requires some thoughts, we can do it with what I mentioned in the previous comment:

```julia
@agent A NoSpaceAgent begin
           f1::Int
           f2::Int
           consts = (:f1, )
       end
```

or something like

```julia
@agent A NoSpaceAgent begin
           const_f1::Int # or any other prefix instead of const_
           f2::Int
       end
```

The first seems more elegant to me, but then we need to find a suitable more complex regex than in the first case to restructure the result in the struct before interpolation (which means be more careful about edge cases)

```julia
@kwdef mutable struct A
           id::Int
           const f1::Int
           f2::Int
       end
```

thoughts @Datseris ?
