### ISSUE TITLE
Simplify code for `@agent`

### ISSUE THREAD

**Issue by fbanning** [JuliaDynamics/Agents.jl#729]
https://github.com/JuliaDynamics/Agents.jl/blob/f05a17aca2242df26423df1dc890f10d150658b1/src/core/agents.jl#L205-L207

How about doing it like this:

```jl
julia> macro testmacro(numba)
           quote
               @testmacro($numba, 4)
           end
       end
@testmacro (macro with 1 method)

julia> macro testmacro(numba, poppa)
           quote
               Core.eval($(__module__), ($numba * $poppa))
           end
       end
@testmacro (macro with 2 methods)

julia> @testmacro 2
8

julia> @testmacro 2 4
8

julia> @testmacro 2 6
12

julia> @testmacro 3
12
```

This seems to work as expected? I didn't test it yet within our actual macro, just thought that maybe this would work and indeed it seems as if it does? Have you already tried this approach @Datseris and if so, what was the problem with it? If not, I can write a PR for this and see whether it actually works.

**Comment by Datseris** [comment]
I haven't tried it yet!
