### ISSUE TITLE
Add plots and visualization into the documentation

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#73]
- [ ] Cellular automata plots
- [ ] Fire forest plots (they are actually cellular automata)
- [ ] Quantity distribution plots (e.g. wealth distribution)
- [ ] 2D quantity distribution plots, like in MESA
- [ ] Timeseries plot: E.g. wealth of agent versus time or gini coefficient versus time

---

*add more as you see fit*

**Comment by kavir1698** [comment]
Should these be added after we register the AgentsPlots.jl?

**Comment by Datseris** [comment]
Yes. This is not an issue for 2.0, it is just a list of things that would be nice to have. Although, some of them do not require AgentPlots, but just any plotting package (I already have an example of wealth distribution done with PyPlot)
