### ISSUE TITLE
Numbering of columns. Shouldn't it start from 0 ?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#74]
```
julia> data
2000×6 DataFrames.DataFrame
│ Row  │ id     │ wealth_1 │ wealth_3 │ wealth_5 │ wealth_7 │ wealth_9 │
│      │ Int64⍰ │ Int64⍰   │ Int64⍰   │ Int64⍰   │ Int64⍰   │ Int64⍰   │
├──────┼────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 1    │ 1      │ 1        │ 0        │ 3        │ 4        │ 2        │
│ 2    │ 2      │ 1        │ 1        │ 2        │ 0        │ 1        │
│ 3    │ 3      │ 1        │ 2        │ 0        │ 1        │ 1        │
│ 4    │ 4      │ 1        │ 0        │ 1        │ 0        │ 1        │
│ 5    │ 5      │ 1        │ 1        │ 0        │ 1        │ 0        │
│ 6    │ 6      │ 1        │ 0        │ 0        │ 1        │ 2        │
│ 7    │ 7      │ 1        │ 0        │ 0        │ 0        │ 0        │
```
this is what I see when I play around with the wealth distribution example. The problem is, the column `wealth_1` is clearly the distribution _before_ running the model. I think this `1` is misleading, as it denotes the "step number". The step number in this case is 0 not one. If we save the initial state of the model before stepping, then we should be consistent and use this number to denote "how many steps are taken".

**Comment by kavir1698** [comment]
https://github.com/JuliaDynamics/Agents.jl/commit/6d21ba41b18746a3cf8829f275b23172fc45de53 fixes it.

**Comment by Datseris** [comment]
Wait, with your change does `when = 1:5` include collecting data for the initial condition?

@kavir1698 similar with my suggestion on the max characters per line of code, can you please start adding things using Pull Requests, instead of just "pushing" to the `2.0` branch? Not only this improves collaboration experience (as I always have to pull your changes to my development branches), but most importantly makes it possible to review things _before_ they are merged into the main branch. I think that you can agree to the fact that it is likely that any change will have mistakes, and being seen by a second pair of eyes is helpful.

**Comment by kavir1698** [comment]
> with your change does when = 1:5 include collecting data for the initial condition?
Yes, it does.

> can you please start adding things using Pull Requests, instead of just "pushing" to the 2.0 branch?
Sure, sorry for the inconvenience so far.

**Comment by Datseris** [comment]
No problem. Then I am keeping this open simply to remind us to document that the "zero" step is always collected.

**Comment by kavir1698** [comment]
> document that the "zero" step is always collected

Do you want a PR branch for small changes like this?

**Comment by Datseris** [comment]
If you plan to also implement

> add an option so that the zero step is not collected automatically.

then yes please. Otherwise it is indeed something simple enough that I don't mind doing auto-pulling :)

**Comment by kavir1698** [comment]
I have updated the documentation. Maybe we can leave the optional data collection at step 0 to after version 2 release?

**Comment by kavir1698** [comment]
#80 solves this.
