### ISSUE TITLE
Use OrderedDict for agents container in StandardABM for better reproducibility

### ISSUE THREAD

**Issue by Tortar** [JuliaDynamics/Agents.jl#752]
Currently we are using a normal Dict as agents container in StandardABM, but what about avoiding reproducibility issues using OrderedDicts instead? I asked [a question on SO](https://stackoverflow.com/questions/75632333/are-julia-dictionaries-and-sets-stable-between-runs) and it seems that people agree that it's better for reproducibility to use them in Julia. A good reason I see mentioned in one of the answers is that the ordering of keys can change **across machines** (I think it is referred to the 32/64 bit architectures after looking at the implemantion of the hash functions in Base). For the differences across versions instead I don't think it is really important for us since also RNGs are not assured to be stable across them. From the performance standpoint there shouldn't be regressions I think, the ordered version seems to perform almost always at least as good as the unordered one even if the comparisons I found are a bit old, we could run some benchmarks to check

**Comment by Datseris** [comment]
we don't do that because it is slower I think. If it isn't slower, then sure!

I am not sure whether "reproducibility" can be an argument here: use an `rng` with a given seed and the current dict is perfectly reproducible, or it isn't...?

**Comment by Tortar** [comment]
on a single machine I guess it is but on different machines I think it can produce different results if the architecture matters: asked for clarifications on that matter on SO, but looking at https://github.com/JuliaLang/julia/blob/master/base/hashing.jl in Base it seems that the hashing is the same for all types of integers so dicts with integer keys should be reproducible even across machines, will try to benchmark them anyways

**Comment by Datseris** [comment]
Yes, I understand this, but what I meant is: if you care about making a reproducible ABM then you don't use the fastest scheduler. You use e.g., Randomy with a given seed. Or by property.

Oh, I think you are saying e.g., even the by_propery scheduling would give different results in different machines even with the same seed, right? In this case then yes we should go to the ordered version unless there is some strong performance defecit.

**Comment by Tortar** [comment]
exactly, but it seems that the implementation of the hashing of integers types is still consistent across machines but this is an implementation detail which can change (for other types e.g. it seems that this is instead not consistent)

**Comment by Tortar** [comment]
experimenting a bit I'm finding these results but doing it very quick and dirty I could have made some mistakes: 2.2x faster access and iteration, 1.7x slower add new key, 1.4 faster remove key. Will try anyway to change Dict in OrderedDict in Agents.jl and see the speed-up/slowdown for some models

**Comment by Tortar** [comment]
Closing since it doesn't seem necessary
