### ISSUE TITLE
Efficient `random_nearby_position`

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#756]
We have all this nice code for functions like `random_nearby_agent` that efficiently give a random pick without doing any allocations. But the simpler function `random_nearby_position` is missing. Would be very nice if we could add it!

(I'm giving this a good first issue because the code for `random_nearby_agent` can be directly re-used!)

(cc @jacobusmmsmit  or @Tortar or @AayushSabharwal  you guys did imrpovements in the random agent like functions)

**Comment by MA-Ramirez** [comment]
Hello, I have already implemented this function, I will create a PR soon

**Comment by MA-Ramirez** [comment]
I just created the pull request #762

**Comment by Datseris** [comment]
GitHub automatically crosslinks PRs to issues if you state this in the PR. When opening a PR write something "Closes #756" and the PR will crosslink here automatically, and when merged, will close the issue automatically.
