### ISSUE TITLE
Implementing the Gillespie Algorithm

### ISSUE THREAD

**Issue by MA-Ramirez** [JuliaDynamics/Agents.jl#759]
Hello, 

Implementing the Gillespie Algorithm in the agents.jl framework is more complex than I thought.
I realized this by coding a new example for `AgentsExampleZoo.jl`, the Spatial Rock-Paper-Scissors game.
I opened an issue [here](https://github.com/JuliaDynamics/Agents.jl/issues/760) to explain the problem in more detail. 

In the issue, I outline the algorithm, the attempted implementation, and the problem. Hopefully, someone comes up with an idea to implement the algorithm, given that it is a common stochastic algorithm used for modelling.

**Comment by Datseris** [comment]
closing in favor of #760
