### ISSUE TITLE
Renaming the `genocide!` function

### ISSUE THREAD

**Issue by MA-Ramirez** [JuliaDynamics/Agents.jl#764]
Hello, 

I propose changing the name of the function `genocide!`.
This is because the word genocide is linked to heinous events in history and in our current times.
Therefore, to not normalise the word's meaning and the human suffering it signifies, I propose changing the name to something like `remove_all!`.

Similarly, the function `kill_agent!`could be renamed `remove_agent!`.

**Comment by Datseris** [comment]
sure!
