### ISSUE TITLE
Internal links in api.md not working

### ISSUE THREAD

**Issue by MA-Ramirez** [JuliaDynamics/Agents.jl#774]
Hello, 

**Describe the bug**
I was browsing the api.md file in Github. When I click on the links that redirect to internal parts of the repo, I get a 404 error with the message: 
```
The 'JuliaDynamics/Agents.jl' repository doesn't contain the 'docs/src/@ref' path in 'main'.  
```

**Minimal Working Example**
The API of Agents.jl is defined on top of the fundamental structures [AgentBasedModel](https://github.com/JuliaDynamics/Agents.jl/blob/main/docs/src/@ref), [Space](@ref Space), [AbstractAgent](https://github.com/JuliaDynamics/Agents.jl/blob/main/docs/src/@ref) which are described in the [Tutorial](https://github.com/JuliaDynamics/Agents.jl/blob/main/docs/src/@ref) page. In this page we list the remaining API functions, which constitute the bulk of Agents.jl functionality.

When I click on any of the links, I get the error.

**Agents.jl version**
5.8.0

Cheers

**Comment by Tortar** [comment]
I think it's actually related to the fact that the docs folder is used to build the documentation pages, for example the page you are referring to is https://juliadynamics.github.io/Agents.jl/stable/api/ and here all links works as expected, the fact that on github it's part of them being part of the building process. So, I close this issue, if I'm missing something, let me know :-)
