### ISSUE TITLE
State that GLMakie.activate!() should be called in the docs for interactive apps

### ISSUE THREAD

**Issue by phigas13** [JuliaDynamics/Agents.jl#800]
In the examples tutorials regarding the interactivity of ABM models given in interactiveDynamics.jl and Agents.jl, (Schelling, etc...)  it is clearly specified that GLMakie backend should be used instead of CairoMakie, but that is not enough (at least for me withVSCode). The figure appears but I have no interactivity (buttons and sliders inop).
One must also run: GLMakie.activate!() to obtain proper reactivity of the figure.
Hope it may save time to some...

**Comment by Datseris** [comment]
It'll save time to some if you make a Pull Request to the documentation so that this information is shown ;)

**Comment by fbanning** [comment]
> One must also run: GLMakie.activate!() to obtain proper reactivity of the figure.

As long as you only run `using GLMakie` and not `using CairoMakie` as well, there should be no need to explicitly do this. If there's only one backend loaded then that should be automatically activated. Except if something has changed on the Makie side of which I'm not aware.

**Comment by Tortar** [comment]
I don't really see this issue with the current main, also if you use `using GLMakie` after using any other backend GLMakie will be used
