### ISSUE TITLE
Schoolyard Example throws  "Specifying `spacing` by position is deprecated"

### ISSUE THREAD

**Issue by GMGassner** [JuliaDynamics/Agents.jl#810]
Dear Agents.jl Team,
First I wanted to thank you for this absolutely fantastic package! I just started to build my first ABM, which fascinates me.

**Describe the bug**
Schoolyard Example gives the following error:

┌ Warning: Specifying `spacing` by position is deprecated. Use keyword `spacing` instead.
└ @ Agents C:\Users\Username\.julia\packages\Agents\PhazO\src\deprecations.jl:11

The problem seems to be:

ContinuousSpace((100, 100), spacing; periodic = false);

a solution seems to be:

ContinuousSpace((100, 100); spacing=spacing, periodic=false);

**Minimal Working Example**
```julia
model = ABM(
    Student,
    ContinuousSpace((100, 100); spacing=spacing, periodic=false);
    properties = Dict(
        :teacher_attractor => teacher_attractor,
        :noise => noise,
        :buddies => SimpleWeightedDiGraph(numStudents),
        :max_force => max_force,
    ),
    rng = MersenneTwister(seed)
)
```
If the code is **runnable**, it will help us identify the problem faster.

Knowing that this fix is almost given by the error message, I just wanted help to update this tutorial.
Thanks again for everything you do for an ABM interested community.

Best

**Comment by Tortar** [comment]
Thanks for the report! you can open a PR to fix the example if you want, you are surely correct on the way to fix the problem

If you don't have experience with opening PRs, you can do it in a simple (but not advisable in general :-)) way, go to the example file in this repository and click the edit in place on the right top of the screen, this way you can modify the relevant line directly on github
