### ISSUE TITLE
Docs: highlight the zoo a bit more?

### ISSUE THREAD

**Issue by cormullion** [JuliaDynamics/Agents.jl#812]
I didn't realize that there was an "Agent Zoo" while reading the documentation for the first time. The first parts of the documentation don't mention it, nor does the main github page, and it's only later on in the documentation (the last subsection of Examples) that it gets a quick mention.

So it could be beneficial to future users if you added up front some kind of promo that links to the zoo docs - a picture of a few would probably be sufficient!

Documentation is pretty good, by the way!

**Comment by Datseris** [comment]
thanks, sure, we could highlight this more, but where? What picture do you envision, and where should this picture be put?

**Comment by Datseris** [comment]
I can add a link to the Features list of the main doc page.

**Comment by cormullion** [comment]
Just a picture of a few in the Introduction (before or after Getting Help) would be useful. I was thinking of a "small multiple" teaser image. Like this:

![agentsmodelzoo](https://github.com/JuliaDynamics/Agents.jl/assets/52289/595ffc00-9df0-4ffb-a026-30b9cca47adc)

only not so silly... :)

**Comment by Datseris** [comment]
I hope this is good enough because it took me too many hours to put together

https://github.com/JuliaDynamics/Agents.jl/assets/19669089/7437f1ab-ee4e-462c-bad2-40ace476a6c3
