### ISSUE TITLE
Game of life example _and_ visualization

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#84]
The game of life is arguably the most known ABM. After we announce Agents v2.0 users will certainly try to find this example. At the moment it doesn't exist.

To make sure we give a good impression right from the get go, this example must exist before the announcement, along with visualizations.

I think the plan would be to tag Agents 2.0, then tag AgentPlots 0.1, then add the game of life example and then announce.

**Comment by kavir1698** [comment]
Sounds good. Currently, AgentsPlots creates an image for each frame of the game of life. It would be good to find a solution that outputs a gif or a video.

**Comment by kavir1698** [comment]
Shall we close this?
