### ISSUE TITLE
Implement `swap_agents!` function

### ISSUE THREAD

**Issue by Tortar** [JuliaDynamics/Agents.jl#849]
This is a simple function to implement, but useful e.g. https://github.com/JuliaDynamics/AgentsExampleZoo.jl/pull/17/files#diff-9c3064755f3ed751008e1dc79736a32e52bece1744e1c80f80688b43a4d4169bR189, it would swap the positions of two agents,
Mesa has one https://github.com/projectmesa/mesa/blob/main/mesa/space.py#L435

**Comment by Jay-sanjay** [comment]
Hello sir , I would be happy to contribute for this issue, here the function must swap agents and must be similar to mesa ,(space.py) majorly implementing the same in Julia.
Is this what can be done sir  ?? , can you please assist me further.

**Comment by Tortar** [comment]
Very glad that you are interested!

That's exactly what's need to be done. 

In practice you should implement this function for discrete spaces, which means that the function should go inside `src/spaces/discrete.jl`. The function signature should be something like `swap_agents!(agent1, agent2, model::ABM{<:DiscreteSpace})` and then you basically need to do the swapping between the positions of the agents first removing both of them with `remove_agent_from_space!(a, model)` and then readding them with `add_agent_to_space!(a, model)`. Then you need to export the function and update the `docs/source/api.md` file referencing the function. Then, if you can implement some tests, it would be great! Hope it's helpful :-)

**Comment by Jay-sanjay** [comment]
Sir , one doubt before proceeding , how to get the position of the agents a and b , can I use the get_position function present in Julia  ?

**Comment by Jay-sanjay** [comment]
Also , I am not getting how to interpret below similar line in Julia
https://github.com/projectmesa/mesa/blob/main/mesa/space.py#L442#L444

**Comment by Jay-sanjay** [comment]
Also , should the test cases be added only in
https://github.com/JuliaDynamics/Agents.jl/blob/f21211bdf861b3242aa4d877394eb9afa37cc471/test/api_tests.jl#L7

**Comment by Tortar** [comment]
> Sir , one doubt before proceeding , how to get the position of the agents a and b , can I use the get_position command present in Julia ?

you should simply do `agent1.pos`


> Also , I am not getting how to interpret below similar line in Julia https://github.com/projectmesa/mesa/blob/main/mesa/space.py#L442C1-L444C77

these lines are not important in our case



> Also , should the test cases be added only in
> 
> https://github.com/JuliaDynamics/Agents.jl/blob/f21211bdf861b3242aa4d877394eb9afa37cc471/test/api_tests.jl#L7

yes, they could be added there, but under a new testset: `@testset "swap_agents!" begin ....`
