### ISSUE TITLE
Final call before 2.0

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#86]
Let's take a day and think whether we want to consider any other change before we tag 2.0. If we think of something let's write it here, otherwise tomorrow i'll make the tag!

**Comment by Datseris** [comment]
@kavir1698 I've noticed our main figure has a typo: it says AgentBasetModel (with t instead of d)

**Comment by kavir1698** [comment]
I've fixed it.

**Comment by Datseris** [comment]
@kavir1698 I am looking at the documentation, specifically the Schelling example here: https://juliadynamics.github.io/Agents.jl/dev/tutorial/#Running-the-model-and-collecting-data-1

you will see that the collected `pos` information is an Integer, even though the agent positions are `NTuple`. Is this correct / intended? I would expect `pos` to have the same type as the Agent's field.

**Comment by kavir1698** [comment]
I see that I have intentionally recorded all positions as node id. But I don't remember why I had made that decision. Anyway, this can be simply reversed and all the tests pass.

**Comment by Datseris** [comment]
@kavir1698 Agents 2.0 is out, please go ahead with registering AgentPlots.
