### ISSUE TITLE
Disable manual assignment of ID in version 6.

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#861]
Since we are going to a breaking 6.0 release due to the continuous space SVector change, we might as well ensure that there is no way for the user to manually add id to agents. cc @Tortar and discussions in #445 and #841

**Comment by Datseris** [comment]
This means we need to deprecate the `add_agent!(a::Agent, ....)` function, as this is the only way to add user-created agents ot the model. Otherwise `add_agent!(model, ...)` does the trick.

**Comment by Tortar** [comment]
I think this would be best! More we have control of the fields used internally the better

**Comment by Tortar** [comment]
Implemented in #871
