### ISSUE TITLE
Finalize update messages

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#890]
- Latest news in the documentation
- Update print message in the repl
- changelog

Continuation of #839 .

**Comment by Tortar** [comment]
to be updated: https://github.com/JuliaDynamics/Agents.jl/blob/main/docs/src/index.md

**Comment by Tortar** [comment]
wops! Forgot to update changelog and news for `EventqueueABM`, another things to be done before release for sure :D

**Comment by Datseris** [comment]
Sorry I have been on holidays and I will return soon to Agents.jl!

**Comment by Tortar** [comment]
Hope you enjoyed them!

**Comment by Datseris** [comment]
Well, I went to the hospital 4 times in the last 30 days, so it wasn't the best holidays of my life... :( 

Anyways, today I am working on Agents.jl. Nevertheless, you have a much better overview of what the v6 changelog should be, so you should be the one that finishes this issue!

**Comment by Tortar** [comment]
Ohh, I'm really sorry for that, hope you feel better now.

Yes, you are right, then I will finish this up when the time comes :-)
