### ISSUE TITLE
execute `run!()` or `paramscan()` multiple times using the same parameters

### ISSUE THREAD

**Issue by yunhwankim2** [JuliaDynamics/Agents.jl#892]
In many cases, experiments using ABM are executed multiple times using the same parameters and results of their averages and/or confidence intervals are usually reported.
Thus, I would like to request a functionality in `run!()` and `paramscan()` functions to execute multiple times using the same parameters and record all the data. 
Many thanks in advance.

**Comment by Tortar** [comment]
This is a very useful feature!

**Comment by Datseris** [comment]
Yes, it is possible, using `paramscan`, and making the varied parameter the RNG seed. It is also mentioned in the docstring of `paramscan`: 

![image](https://github.com/JuliaDynamics/Agents.jl/assets/19669089/1701bb33-432f-4138-a4c0-fb8d89ea4070)


simply don't change any other parameter besides the seed.

To report confidence intervals this is a standard processing of the resulting data frame and the `quantile` function.

**Comment by yunhwankim2** [comment]
Thank you for the reply. I tried to find the docstring, and it was found in the `ensemblerun!` (https://juliadynamics.github.io/Agents.jl/stable/api/#Agents.ensemblerun!) rather than `paramscan`. Is it `ensemblerun!` that you intended to refer to?

**Comment by Datseris** [comment]
It doesn't matter. Either can work for you. Either can run many simulations changing parameters. Just make the seed the changing parameter.

**Comment by yunhwankim2** [comment]
Okay. I see. Thank you so much.
