### ISSUE TITLE
Deprecate UnremovableABM in v6

### ISSUE THREAD

**Issue by Tortar** [JuliaDynamics/Agents.jl#918]
Since we will have a new ABM type (`EventQueueABM`) which could work with both a Dict or Vector container for the Agents, I think it would be better to uniformize this feature: this means deprecating `UnremovableABM` (so actually not really breaking). Instead of it I would propose to allow the user to choose a `StandardABM(...; ..., agent_container=Vector)` which is actually already available, it is just not documented. It seems even more natural since this is just a little optimization, so it doesn't make much sense in my opinion to have a different type, we will just say that if you choose a Vector as container you won't be able to remove agents.

cc @Datseris

**Comment by Datseris** [comment]
yes i agree

**Comment by Tortar** [comment]
With #919
