### ISSUE TITLE
Invalid argument `agents_step!` uncaught by `abmplot`.

### ISSUE THREAD

**Issue by iago-lito** [JuliaDynamics/Agents.jl#925]
Hello, the minor issue I'm opening here follows a few hours that we've just spent screening all our code to eventually figure out that the error was in the following line:
```julia
fig, _ = abmplot(model; agents_step! = my_agent_step_function!, model_step! = my_model_step_function!, ...)
```
The error above is that the true argument name must be `agent_step!` and not `agents_step!` (with a spurious `s`). Our bad ^ ^

This being said, the behaviour of the above erroneous invocation of `abmplot` was **not** to yield an error complaining about the typo. This is unfortunate. Instead, `abmplot` ran almost-fine and was just behaving as if no `agent_step!` function had been provided at all, which has been very confusing.

Could some sort of check be added within `abmplot` to not pass typos silently?

**Comment by fbanning** [comment]
I've also added the documentation label. In the PR following #914 I would like to include a short notice in the docs that tell people about this behaviour in the recipe system. After that has been done, we can close this issue.
