### ISSUE TITLE
Schelling model is not in examples

### ISSUE THREAD

**Issue by sbacelar** [JuliaDynamics/Agents.jl#94]
It should be useful if the `Schelling` model that is in the `tutorial` was also in the `examples` folder.

**Comment by Datseris** [comment]
Here is how I think we should tackle this

1. Remove the example part of the code from tutorial.md
2. Make into a literate-format file `.jl`.
3. Add this as a standard example.
4. Also add it in the tutorial page by including the produced markdown file. We have done this in TimeseriesPrediction: https://github.com/JuliaDynamics/TimeseriesPrediction.jl/blob/master/docs/make.jl#L8-L20
