### ISSUE TITLE
Error plotting Schelling model

### ISSUE THREAD

**Issue by sbacelar** [JuliaDynamics/Agents.jl#95]
I am trying to run Schelling model from the tutorial (in Juno). I got the following error:

```
using AgentsPlots
for i in 1:2
  p = plot2D(data, :group, t=i, nodesize=10)
end
```

`ArgumentError: column name :group not found in the data frame`

**Comment by kavir1698** [comment]
The properties you collect should be
```jl
properties = [:pos, :mood, :group]
```

Which is [here](https://juliadynamics.github.io/Agents.jl/stable/tutorial/#Running-the-model-and-collecting-data-1).

**Comment by Datseris** [comment]
My suggestion would be to re-write this codeblock 
```
using AgentsPlots
for i in 1:2
  p = plot2D(data, :group, t=i, nodesize=10)
end
```
to be
```
using AgentsPlots
p = plot2D(data, :group, t=1, nodesize=10)
```
```
p = plot2D(data, :group, t=2, nodesize=10)
```
so that both plots are actually shown.

**Comment by Datseris** [comment]
Just as a warning @sbacelar the _plotting_ part of Agents.jl is not stable, because AgentsPlots.jl is not on version 1.0 yet, but 0.2. We are still figuring out how things should be and what is the optimal way to do plots of ABMs. There was some discussion in #92 that proposed one more interface that takes the `model` as an input and plots it. (the current interface thtat takes the `dataframe` as an input is mostly unaffected)

**Comment by sbacelar** [comment]
I used `properties = [:pos, :mood, :group]`. 
I also tried `p = plot2D(data, :group, t=1, nodesize=10)`but I got the same error. I understand the problem with `AgentsPlots.jl`and I hope you will find a solution.

**Comment by kavir1698** [comment]
> I used properties = [:pos, :mood, :group].

After you define the properties to be collected, you should run the model again, that is initialize the model and collect data.

**Comment by sbacelar** [comment]
I think that's what I do when running:
```
model = initialize(numagents=370, griddims=(20,20), min_to_be_happy=3);
properties = Dict(:mood => [sum])
n = 5; when = 1:n
data = step!(model, agent_step!, 5, properties, when=when)
```
before `using AgentsPlots`.

**Comment by kavir1698** [comment]
Yes, but in this block, you are using `properties = Dict(:mood => [sum])`. Instead, properties should be `properties = [:pos, :mood, :group]`.

**Comment by sbacelar** [comment]
I understand. It works now. You mean that before `using AgentsPlots` I have to re-run:
```
model = initialize()
# An array of Symbols for the agent fields that are to be collected.
properties = [:pos, :mood, :group]
# Specifies at which steps data should be collected.
n = 5  # number of time steps to run the simulation
when = 1:n  # At which steps to collect data
# Use the step function to run the model and collect data into a DataFrame.
data = step!(model, agent_step!, n, properties, when=when)
data[1:10, :] # print only a few rows
```
I think this should be clear in the tutorial given that it is a crucial example.
