### ISSUE TITLE
Problem with parallel computing on Schelling model

### ISSUE THREAD

**Issue by sbacelar** [JuliaDynamics/Agents.jl#96]
I am following the Schelling example and when I run 
```
using Distributed
addprocs(2)

data = step!(model, agent_step!, 2, properties,
             when=when, replicates=5, parallel=true)
```
I get `On worker 2: KeyError: key Agents [46ad....] not found`
I am using a MacBookpro with 2 cores.

**Comment by kavir1698** [comment]
You need to define everything on all the cores. `@everywhere` should go before defining agent type, model initialization, etc.

**Comment by Datseris** [comment]
This is a good opportunity to document an example that is really parallel. So everything is properly prefaced with `@everywhere`.

@sbacelar let me also take this opportunity to thank you for all the valuable feedback you provide. It is exceptionally useful to have an "outside eye" from someone that has not been looking at the code for too long ! :D

**Comment by sbacelar** [comment]
In my opinion there should be two Schelling examples: one "simple" and the other more complex with parallel processing.
@Datseris Thank you for your kind words. I am a `Julia` fan, a `NetLogo` and `R`user and my research uses `ABM`. I sincerely hope to use `Agents.jl` on it.

**Comment by Datseris** [comment]
@kavir1698 I am reading the error message that is reported here and you see it is not about an undefined _function_ on some other core. Have we actually tested distributed ABMs? I am looking at the test but at first glance I don't see anything about distributed stuff.

**Comment by kavir1698** [comment]
We don't have tests for parallel computations, partly because I am not sure how that would work on travis. Otherwise, I have used parallel computation for my own research and it works well.

**Comment by Datseris** [comment]
Closing in favor of #243
