### ISSUE TITLE
Scheduler function & number of steps

### ISSUE THREAD

**Issue by NV2019** [JuliaDynamics/Agents.jl#98]
I have two issues specific to my model. 

1. Right now, among the scheduler functions there is one that picks agents for update uniformly at random. How can I instead choose them according to a predetermined distribution?
2. What if I want the step function to run as long as a certain condition is satisfied? Without mentioning the number of steps beforehand?

**Comment by kavir1698** [comment]
> Right now, among the scheduler functions there is one that picks agents for update uniformly at random. How can I instead choose them according to a predetermined distribution?

You can define your own scheduler function. A scheduler takes the model object as input and returns an list of agent IDs to be activated in turn. For example, the `random_activation` function is just this:

```jl
function random_activation(model::ABM)
  order = shuffle(collect(keys(model.agents)))
end
```

> What if I want the step function to run as long as a certain condition is satisfied? Without mentioning the number of steps beforehand?

This is not implemented. But I think it should be easy to add.

**Comment by Datseris** [comment]
@NV2019 to asnswer 1, something like this (but needs to be tested!):

```julia
function by_weight(model)
w = [(a.id, a.weight) for a in model.agents]
s = sortperm(w, by = x -> x[2])
return [x[1] for x in w[s]]
end
```

**Comment by Datseris** [comment]
Seems useful enough to be added to the existing schedulers, if you are up for it, and want to obtain a contributor status to Agents.jl, you can do a Pull Request @NV2019 .

**Comment by Datseris** [comment]
@NV2019 I actually just implemented the point 1 that you ask in PR #101 . Once this is merged and a new version is tagged you can do:

```
model(AgentType; scheduler = property_activation(:property)
```
(with `:property` the actual field of the agents you want to compare, e.g. `:weight`)

**Comment by NV2019** [comment]
Can I know if this modification is available and if the documentation has been updated regarding this and this issue[issue](https://github.com/JuliaDynamics/Agents.jl/issues/102#issue-535967690)

**Comment by Datseris** [comment]
Huh? I don't understand the question. Everything is implemented, you can find it at the documentation of `step!` or at the API page: https://juliadynamics.github.io/Agents.jl/stable/api/#Schedulers-1   or    https://juliadynamics.github.io/Agents.jl/stable/examples/schelling/#Creating-an-ABM-1
